/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.pin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Categoria service. Represents a row in the &quot;Categoria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.pin.model.impl.CategoriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.pin.model.impl.CategoriaImpl}.
 * </p>
 *
 * @author arodriguez
 * @see Categoria
 * @see com.ext.portlet.pin.model.impl.CategoriaImpl
 * @see com.ext.portlet.pin.model.impl.CategoriaModelImpl
 * @generated
 */
public interface CategoriaModel extends BaseModel<Categoria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a categoria model instance should use the {@link Categoria} interface instead.
	 */

	/**
	 * Returns the primary key of this categoria.
	 *
	 * @return the primary key of this categoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this categoria.
	 *
	 * @param primaryKey the primary key of this categoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the categoria ID of this categoria.
	 *
	 * @return the categoria ID of this categoria
	 */
	public long getCategoriaId();

	/**
	 * Sets the categoria ID of this categoria.
	 *
	 * @param categoriaId the categoria ID of this categoria
	 */
	public void setCategoriaId(long categoriaId);

	/**
	 * Returns the id imagen of this categoria.
	 *
	 * @return the id imagen of this categoria
	 */
	public long getIdImagen();

	/**
	 * Sets the id imagen of this categoria.
	 *
	 * @param idImagen the id imagen of this categoria
	 */
	public void setIdImagen(long idImagen);

	/**
	 * Returns the nombre of this categoria.
	 *
	 * @return the nombre of this categoria
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this categoria.
	 *
	 * @param nombre the nombre of this categoria
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the estado of this categoria.
	 *
	 * @return the estado of this categoria
	 */
	public boolean getEstado();

	/**
	 * Returns <code>true</code> if this categoria is estado.
	 *
	 * @return <code>true</code> if this categoria is estado; <code>false</code> otherwise
	 */
	public boolean isEstado();

	/**
	 * Sets whether this categoria is estado.
	 *
	 * @param estado the estado of this categoria
	 */
	public void setEstado(boolean estado);

	/**
	 * Returns the descripcion of this categoria.
	 *
	 * @return the descripcion of this categoria
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this categoria.
	 *
	 * @param descripcion the descripcion of this categoria
	 */
	public void setDescripcion(String descripcion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Categoria categoria);

	public int hashCode();

	public CacheModel<Categoria> toCacheModel();

	public Categoria toEscapedModel();

	public String toString();

	public String toXmlString();
}