/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.pin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Persona service. Represents a row in the &quot;Persona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.pin.model.impl.PersonaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.pin.model.impl.PersonaImpl}.
 * </p>
 *
 * @author arodriguez
 * @see Persona
 * @see com.ext.portlet.pin.model.impl.PersonaImpl
 * @see com.ext.portlet.pin.model.impl.PersonaModelImpl
 * @generated
 */
public interface PersonaModel extends BaseModel<Persona> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persona model instance should use the {@link Persona} interface instead.
	 */

	/**
	 * Returns the primary key of this persona.
	 *
	 * @return the primary key of this persona
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persona.
	 *
	 * @param primaryKey the primary key of this persona
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this persona.
	 *
	 * @return the user ID of this persona
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this persona.
	 *
	 * @param userId the user ID of this persona
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persona.
	 *
	 * @return the user uuid of this persona
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this persona.
	 *
	 * @param userUuid the user uuid of this persona
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the nombres of this persona.
	 *
	 * @return the nombres of this persona
	 */
	@AutoEscape
	public String getNombres();

	/**
	 * Sets the nombres of this persona.
	 *
	 * @param nombres the nombres of this persona
	 */
	public void setNombres(String nombres);

	/**
	 * Returns the apellido paterno of this persona.
	 *
	 * @return the apellido paterno of this persona
	 */
	@AutoEscape
	public String getApellidoPaterno();

	/**
	 * Sets the apellido paterno of this persona.
	 *
	 * @param apellidoPaterno the apellido paterno of this persona
	 */
	public void setApellidoPaterno(String apellidoPaterno);

	/**
	 * Returns the apellido materno of this persona.
	 *
	 * @return the apellido materno of this persona
	 */
	@AutoEscape
	public String getApellidoMaterno();

	/**
	 * Sets the apellido materno of this persona.
	 *
	 * @param apellidoMaterno the apellido materno of this persona
	 */
	public void setApellidoMaterno(String apellidoMaterno);

	/**
	 * Returns the dni of this persona.
	 *
	 * @return the dni of this persona
	 */
	@AutoEscape
	public String getDni();

	/**
	 * Sets the dni of this persona.
	 *
	 * @param dni the dni of this persona
	 */
	public void setDni(String dni);

	/**
	 * Returns the tipo documento of this persona.
	 *
	 * @return the tipo documento of this persona
	 */
	public int getTipoDocumento();

	/**
	 * Sets the tipo documento of this persona.
	 *
	 * @param tipoDocumento the tipo documento of this persona
	 */
	public void setTipoDocumento(int tipoDocumento);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Persona persona);

	public int hashCode();

	public CacheModel<Persona> toCacheModel();

	public Persona toEscapedModel();

	public String toString();

	public String toXmlString();
}