/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditoriaPerfilador service. Represents a row in the &quot;T_AUDITORIA_PERFILADOR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.AuditoriaPerfiladorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.AuditoriaPerfiladorImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see AuditoriaPerfilador
 * @see com.ext.portlet.halcon.model.impl.AuditoriaPerfiladorImpl
 * @see com.ext.portlet.halcon.model.impl.AuditoriaPerfiladorModelImpl
 * @generated
 */
public interface AuditoriaPerfiladorModel extends BaseModel<AuditoriaPerfilador> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditoria perfilador model instance should use the {@link AuditoriaPerfilador} interface instead.
	 */

	/**
	 * Returns the primary key of this auditoria perfilador.
	 *
	 * @return the primary key of this auditoria perfilador
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditoria perfilador.
	 *
	 * @param primaryKey the primary key of this auditoria perfilador
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id auditoria per of this auditoria perfilador.
	 *
	 * @return the id auditoria per of this auditoria perfilador
	 */
	public long getIdAuditoriaPer();

	/**
	 * Sets the id auditoria per of this auditoria perfilador.
	 *
	 * @param idAuditoriaPer the id auditoria per of this auditoria perfilador
	 */
	public void setIdAuditoriaPer(long idAuditoriaPer);

	/**
	 * Returns the tipo documento of this auditoria perfilador.
	 *
	 * @return the tipo documento of this auditoria perfilador
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this auditoria perfilador.
	 *
	 * @param tipoDocumento the tipo documento of this auditoria perfilador
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the numero documento of this auditoria perfilador.
	 *
	 * @return the numero documento of this auditoria perfilador
	 */
	@AutoEscape
	public String getNumeroDocumento();

	/**
	 * Sets the numero documento of this auditoria perfilador.
	 *
	 * @param numeroDocumento the numero documento of this auditoria perfilador
	 */
	public void setNumeroDocumento(String numeroDocumento);

	/**
	 * Returns the perfilador of this auditoria perfilador.
	 *
	 * @return the perfilador of this auditoria perfilador
	 */
	@AutoEscape
	public String getPerfilador();

	/**
	 * Sets the perfilador of this auditoria perfilador.
	 *
	 * @param perfilador the perfilador of this auditoria perfilador
	 */
	public void setPerfilador(String perfilador);

	/**
	 * Returns the session of this auditoria perfilador.
	 *
	 * @return the session of this auditoria perfilador
	 */
	@AutoEscape
	public String getSession();

	/**
	 * Sets the session of this auditoria perfilador.
	 *
	 * @param session the session of this auditoria perfilador
	 */
	public void setSession(String session);

	/**
	 * Returns the transaccion of this auditoria perfilador.
	 *
	 * @return the transaccion of this auditoria perfilador
	 */
	@AutoEscape
	public String getTransaccion();

	/**
	 * Sets the transaccion of this auditoria perfilador.
	 *
	 * @param transaccion the transaccion of this auditoria perfilador
	 */
	public void setTransaccion(String transaccion);

	/**
	 * Returns the monto of this auditoria perfilador.
	 *
	 * @return the monto of this auditoria perfilador
	 */
	public Double getMonto();

	/**
	 * Sets the monto of this auditoria perfilador.
	 *
	 * @param monto the monto of this auditoria perfilador
	 */
	public void setMonto(Double monto);

	/**
	 * Returns the tipo credito of this auditoria perfilador.
	 *
	 * @return the tipo credito of this auditoria perfilador
	 */
	@AutoEscape
	public String getTipoCredito();

	/**
	 * Sets the tipo credito of this auditoria perfilador.
	 *
	 * @param tipoCredito the tipo credito of this auditoria perfilador
	 */
	public void setTipoCredito(String tipoCredito);

	/**
	 * Returns the i p of this auditoria perfilador.
	 *
	 * @return the i p of this auditoria perfilador
	 */
	@AutoEscape
	public String getIP();

	/**
	 * Sets the i p of this auditoria perfilador.
	 *
	 * @param IP the i p of this auditoria perfilador
	 */
	public void setIP(String IP);

	/**
	 * Returns the fecha hora of this auditoria perfilador.
	 *
	 * @return the fecha hora of this auditoria perfilador
	 */
	public Date getFechaHora();

	/**
	 * Sets the fecha hora of this auditoria perfilador.
	 *
	 * @param fechaHora the fecha hora of this auditoria perfilador
	 */
	public void setFechaHora(Date fechaHora);

	/**
	 * Returns the u t m source of this auditoria perfilador.
	 *
	 * @return the u t m source of this auditoria perfilador
	 */
	@AutoEscape
	public String getUTMSource();

	/**
	 * Sets the u t m source of this auditoria perfilador.
	 *
	 * @param UTMSource the u t m source of this auditoria perfilador
	 */
	public void setUTMSource(String UTMSource);

	/**
	 * Returns the u t m medium of this auditoria perfilador.
	 *
	 * @return the u t m medium of this auditoria perfilador
	 */
	@AutoEscape
	public String getUTMMedium();

	/**
	 * Sets the u t m medium of this auditoria perfilador.
	 *
	 * @param UTMMedium the u t m medium of this auditoria perfilador
	 */
	public void setUTMMedium(String UTMMedium);

	/**
	 * Returns the u t m campaing of this auditoria perfilador.
	 *
	 * @return the u t m campaing of this auditoria perfilador
	 */
	@AutoEscape
	public String getUTMCampaing();

	/**
	 * Sets the u t m campaing of this auditoria perfilador.
	 *
	 * @param UTMCampaing the u t m campaing of this auditoria perfilador
	 */
	public void setUTMCampaing(String UTMCampaing);

	/**
	 * Returns the u t m content of this auditoria perfilador.
	 *
	 * @return the u t m content of this auditoria perfilador
	 */
	@AutoEscape
	public String getUTMContent();

	/**
	 * Sets the u t m content of this auditoria perfilador.
	 *
	 * @param UTMContent the u t m content of this auditoria perfilador
	 */
	public void setUTMContent(String UTMContent);

	/**
	 * Returns the pregunta01 of this auditoria perfilador.
	 *
	 * @return the pregunta01 of this auditoria perfilador
	 */
	@AutoEscape
	public String getPregunta01();

	/**
	 * Sets the pregunta01 of this auditoria perfilador.
	 *
	 * @param pregunta01 the pregunta01 of this auditoria perfilador
	 */
	public void setPregunta01(String pregunta01);

	/**
	 * Returns the pregunta02 of this auditoria perfilador.
	 *
	 * @return the pregunta02 of this auditoria perfilador
	 */
	@AutoEscape
	public String getPregunta02();

	/**
	 * Sets the pregunta02 of this auditoria perfilador.
	 *
	 * @param pregunta02 the pregunta02 of this auditoria perfilador
	 */
	public void setPregunta02(String pregunta02);

	/**
	 * Returns the pregunta03 of this auditoria perfilador.
	 *
	 * @return the pregunta03 of this auditoria perfilador
	 */
	@AutoEscape
	public String getPregunta03();

	/**
	 * Sets the pregunta03 of this auditoria perfilador.
	 *
	 * @param pregunta03 the pregunta03 of this auditoria perfilador
	 */
	public void setPregunta03(String pregunta03);

	/**
	 * Returns the pregunta04 of this auditoria perfilador.
	 *
	 * @return the pregunta04 of this auditoria perfilador
	 */
	@AutoEscape
	public String getPregunta04();

	/**
	 * Sets the pregunta04 of this auditoria perfilador.
	 *
	 * @param pregunta04 the pregunta04 of this auditoria perfilador
	 */
	public void setPregunta04(String pregunta04);

	/**
	 * Returns the respuesta01 of this auditoria perfilador.
	 *
	 * @return the respuesta01 of this auditoria perfilador
	 */
	@AutoEscape
	public String getRespuesta01();

	/**
	 * Sets the respuesta01 of this auditoria perfilador.
	 *
	 * @param respuesta01 the respuesta01 of this auditoria perfilador
	 */
	public void setRespuesta01(String respuesta01);

	/**
	 * Returns the respuesta02 of this auditoria perfilador.
	 *
	 * @return the respuesta02 of this auditoria perfilador
	 */
	@AutoEscape
	public String getRespuesta02();

	/**
	 * Sets the respuesta02 of this auditoria perfilador.
	 *
	 * @param respuesta02 the respuesta02 of this auditoria perfilador
	 */
	public void setRespuesta02(String respuesta02);

	/**
	 * Returns the respuesta03 of this auditoria perfilador.
	 *
	 * @return the respuesta03 of this auditoria perfilador
	 */
	@AutoEscape
	public String getRespuesta03();

	/**
	 * Sets the respuesta03 of this auditoria perfilador.
	 *
	 * @param respuesta03 the respuesta03 of this auditoria perfilador
	 */
	public void setRespuesta03(String respuesta03);

	/**
	 * Returns the respuesta04 of this auditoria perfilador.
	 *
	 * @return the respuesta04 of this auditoria perfilador
	 */
	@AutoEscape
	public String getRespuesta04();

	/**
	 * Sets the respuesta04 of this auditoria perfilador.
	 *
	 * @param respuesta04 the respuesta04 of this auditoria perfilador
	 */
	public void setRespuesta04(String respuesta04);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AuditoriaPerfilador auditoriaPerfilador);

	public int hashCode();

	public CacheModel<AuditoriaPerfilador> toCacheModel();

	public AuditoriaPerfilador toEscapedModel();

	public String toString();

	public String toXmlString();
}