/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CargaDescuento service. Represents a row in the &quot;T_CARGA_DESCUENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.CargaDescuentoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.CargaDescuentoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see CargaDescuento
 * @see com.ext.portlet.halcon.model.impl.CargaDescuentoImpl
 * @see com.ext.portlet.halcon.model.impl.CargaDescuentoModelImpl
 * @generated
 */
public interface CargaDescuentoModel extends BaseModel<CargaDescuento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a carga descuento model instance should use the {@link CargaDescuento} interface instead.
	 */

	/**
	 * Returns the primary key of this carga descuento.
	 *
	 * @return the primary key of this carga descuento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this carga descuento.
	 *
	 * @param primaryKey the primary key of this carga descuento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id carga desc of this carga descuento.
	 *
	 * @return the id carga desc of this carga descuento
	 */
	public long getIdCargaDesc();

	/**
	 * Sets the id carga desc of this carga descuento.
	 *
	 * @param idCargaDesc the id carga desc of this carga descuento
	 */
	public void setIdCargaDesc(long idCargaDesc);

	/**
	 * Returns the local of this carga descuento.
	 *
	 * @return the local of this carga descuento
	 */
	@AutoEscape
	public String getLocal();

	/**
	 * Sets the local of this carga descuento.
	 *
	 * @param local the local of this carga descuento
	 */
	public void setLocal(String local);

	/**
	 * Returns the descuento general of this carga descuento.
	 *
	 * @return the descuento general of this carga descuento
	 */
	@AutoEscape
	public String getDescuentoGeneral();

	/**
	 * Sets the descuento general of this carga descuento.
	 *
	 * @param descuentoGeneral the descuento general of this carga descuento
	 */
	public void setDescuentoGeneral(String descuentoGeneral);

	/**
	 * Returns the condiciones restricciones of this carga descuento.
	 *
	 * @return the condiciones restricciones of this carga descuento
	 */
	@AutoEscape
	public String getCondicionesRestricciones();

	/**
	 * Sets the condiciones restricciones of this carga descuento.
	 *
	 * @param condicionesRestricciones the condiciones restricciones of this carga descuento
	 */
	public void setCondicionesRestricciones(String condicionesRestricciones);

	/**
	 * Returns the direccion of this carga descuento.
	 *
	 * @return the direccion of this carga descuento
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this carga descuento.
	 *
	 * @param direccion the direccion of this carga descuento
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the id distrito of this carga descuento.
	 *
	 * @return the id distrito of this carga descuento
	 */
	@AutoEscape
	public String getIdDistrito();

	/**
	 * Sets the id distrito of this carga descuento.
	 *
	 * @param idDistrito the id distrito of this carga descuento
	 */
	public void setIdDistrito(String idDistrito);

	/**
	 * Returns the distrito of this carga descuento.
	 *
	 * @return the distrito of this carga descuento
	 */
	@AutoEscape
	public String getDistrito();

	/**
	 * Sets the distrito of this carga descuento.
	 *
	 * @param distrito the distrito of this carga descuento
	 */
	public void setDistrito(String distrito);

	/**
	 * Returns the telefono of this carga descuento.
	 *
	 * @return the telefono of this carga descuento
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this carga descuento.
	 *
	 * @param telefono the telefono of this carga descuento
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the web of this carga descuento.
	 *
	 * @return the web of this carga descuento
	 */
	@AutoEscape
	public String getWeb();

	/**
	 * Sets the web of this carga descuento.
	 *
	 * @param web the web of this carga descuento
	 */
	public void setWeb(String web);

	/**
	 * Returns the fin vigencia of this carga descuento.
	 *
	 * @return the fin vigencia of this carga descuento
	 */
	public Date getFinVigencia();

	/**
	 * Sets the fin vigencia of this carga descuento.
	 *
	 * @param finVigencia the fin vigencia of this carga descuento
	 */
	public void setFinVigencia(Date finVigencia);

	/**
	 * Returns the categoria of this carga descuento.
	 *
	 * @return the categoria of this carga descuento
	 */
	@AutoEscape
	public String getCategoria();

	/**
	 * Sets the categoria of this carga descuento.
	 *
	 * @param categoria the categoria of this carga descuento
	 */
	public void setCategoria(String categoria);

	/**
	 * Returns the coordenada of this carga descuento.
	 *
	 * @return the coordenada of this carga descuento
	 */
	@AutoEscape
	public String getCoordenada();

	/**
	 * Sets the coordenada of this carga descuento.
	 *
	 * @param coordenada the coordenada of this carga descuento
	 */
	public void setCoordenada(String coordenada);

	/**
	 * Returns the u r l imagen of this carga descuento.
	 *
	 * @return the u r l imagen of this carga descuento
	 */
	@AutoEscape
	public String getURLImagen();

	/**
	 * Sets the u r l imagen of this carga descuento.
	 *
	 * @param URLImagen the u r l imagen of this carga descuento
	 */
	public void setURLImagen(String URLImagen);

	/**
	 * Returns the latitud of this carga descuento.
	 *
	 * @return the latitud of this carga descuento
	 */
	@AutoEscape
	public String getLatitud();

	/**
	 * Sets the latitud of this carga descuento.
	 *
	 * @param latitud the latitud of this carga descuento
	 */
	public void setLatitud(String latitud);

	/**
	 * Returns the longitud of this carga descuento.
	 *
	 * @return the longitud of this carga descuento
	 */
	@AutoEscape
	public String getLongitud();

	/**
	 * Sets the longitud of this carga descuento.
	 *
	 * @param longitud the longitud of this carga descuento
	 */
	public void setLongitud(String longitud);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CargaDescuento cargaDescuento);

	public int hashCode();

	public CacheModel<CargaDescuento> toCacheModel();

	public CargaDescuento toEscapedModel();

	public String toString();

	public String toXmlString();
}