/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CategoriaSubcategoria service. Represents a row in the &quot;T_CATEGORIA_SUBCATEGORIA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.CategoriaSubcategoriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.CategoriaSubcategoriaImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see CategoriaSubcategoria
 * @see com.ext.portlet.halcon.model.impl.CategoriaSubcategoriaImpl
 * @see com.ext.portlet.halcon.model.impl.CategoriaSubcategoriaModelImpl
 * @generated
 */
public interface CategoriaSubcategoriaModel extends BaseModel<CategoriaSubcategoria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a categoria subcategoria model instance should use the {@link CategoriaSubcategoria} interface instead.
	 */

	/**
	 * Returns the primary key of this categoria subcategoria.
	 *
	 * @return the primary key of this categoria subcategoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this categoria subcategoria.
	 *
	 * @param primaryKey the primary key of this categoria subcategoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id categoria sub cat of this categoria subcategoria.
	 *
	 * @return the id categoria sub cat of this categoria subcategoria
	 */
	public long getIdCategoriaSubCat();

	/**
	 * Sets the id categoria sub cat of this categoria subcategoria.
	 *
	 * @param idCategoriaSubCat the id categoria sub cat of this categoria subcategoria
	 */
	public void setIdCategoriaSubCat(long idCategoriaSubCat);

	/**
	 * Returns the id categoria sub cat padre of this categoria subcategoria.
	 *
	 * @return the id categoria sub cat padre of this categoria subcategoria
	 */
	public Integer getIdCategoriaSubCatPadre();

	/**
	 * Sets the id categoria sub cat padre of this categoria subcategoria.
	 *
	 * @param idCategoriaSubCatPadre the id categoria sub cat padre of this categoria subcategoria
	 */
	public void setIdCategoriaSubCatPadre(Integer idCategoriaSubCatPadre);

	/**
	 * Returns the descripcion of this categoria subcategoria.
	 *
	 * @return the descripcion of this categoria subcategoria
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this categoria subcategoria.
	 *
	 * @param descripcion the descripcion of this categoria subcategoria
	 */
	public void setDescripcion(String descripcion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CategoriaSubcategoria categoriaSubcategoria);

	public int hashCode();

	public CacheModel<CategoriaSubcategoria> toCacheModel();

	public CategoriaSubcategoria toEscapedModel();

	public String toString();

	public String toXmlString();
}