/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ConfiguracionProducto service. Represents a row in the &quot;T_CONFIGURACION_PRODUCTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.ConfiguracionProductoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.ConfiguracionProductoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see ConfiguracionProducto
 * @see com.ext.portlet.halcon.model.impl.ConfiguracionProductoImpl
 * @see com.ext.portlet.halcon.model.impl.ConfiguracionProductoModelImpl
 * @generated
 */
public interface ConfiguracionProductoModel extends BaseModel<ConfiguracionProducto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a configuracion producto model instance should use the {@link ConfiguracionProducto} interface instead.
	 */

	/**
	 * Returns the primary key of this configuracion producto.
	 *
	 * @return the primary key of this configuracion producto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this configuracion producto.
	 *
	 * @param primaryKey the primary key of this configuracion producto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id configuracion producto of this configuracion producto.
	 *
	 * @return the id configuracion producto of this configuracion producto
	 */
	public long getIdConfiguracionProducto();

	/**
	 * Sets the id configuracion producto of this configuracion producto.
	 *
	 * @param idConfiguracionProducto the id configuracion producto of this configuracion producto
	 */
	public void setIdConfiguracionProducto(long idConfiguracionProducto);

	/**
	 * Returns the id configuracion perfilador of this configuracion producto.
	 *
	 * @return the id configuracion perfilador of this configuracion producto
	 */
	public Long getIdConfiguracionPerfilador();

	/**
	 * Sets the id configuracion perfilador of this configuracion producto.
	 *
	 * @param idConfiguracionPerfilador the id configuracion perfilador of this configuracion producto
	 */
	public void setIdConfiguracionPerfilador(Long idConfiguracionPerfilador);

	/**
	 * Returns the id producto of this configuracion producto.
	 *
	 * @return the id producto of this configuracion producto
	 */
	public Long getIdProducto();

	/**
	 * Sets the id producto of this configuracion producto.
	 *
	 * @param idProducto the id producto of this configuracion producto
	 */
	public void setIdProducto(Long idProducto);

	/**
	 * Returns the nombre producto of this configuracion producto.
	 *
	 * @return the nombre producto of this configuracion producto
	 */
	@AutoEscape
	public String getNombreProducto();

	/**
	 * Sets the nombre producto of this configuracion producto.
	 *
	 * @param nombreProducto the nombre producto of this configuracion producto
	 */
	public void setNombreProducto(String nombreProducto);

	/**
	 * Returns the codigo siebel producto of this configuracion producto.
	 *
	 * @return the codigo siebel producto of this configuracion producto
	 */
	@AutoEscape
	public String getCodigoSiebelProducto();

	/**
	 * Sets the codigo siebel producto of this configuracion producto.
	 *
	 * @param codigoSiebelProducto the codigo siebel producto of this configuracion producto
	 */
	public void setCodigoSiebelProducto(String codigoSiebelProducto);

	/**
	 * Returns the estado configuracion of this configuracion producto.
	 *
	 * @return the estado configuracion of this configuracion producto
	 */
	public Integer getEstadoConfiguracion();

	/**
	 * Sets the estado configuracion of this configuracion producto.
	 *
	 * @param estadoConfiguracion the estado configuracion of this configuracion producto
	 */
	public void setEstadoConfiguracion(Integer estadoConfiguracion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ConfiguracionProducto configuracionProducto);

	public int hashCode();

	public CacheModel<ConfiguracionProducto> toCacheModel();

	public ConfiguracionProducto toEscapedModel();

	public String toString();

	public String toXmlString();
}