/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FondosMutuos service. Represents a row in the &quot;T_FONDOS_MUTUOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.FondosMutuosModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.FondosMutuosImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see FondosMutuos
 * @see com.ext.portlet.halcon.model.impl.FondosMutuosImpl
 * @see com.ext.portlet.halcon.model.impl.FondosMutuosModelImpl
 * @generated
 */
public interface FondosMutuosModel extends BaseModel<FondosMutuos> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fondos mutuos model instance should use the {@link FondosMutuos} interface instead.
	 */

	/**
	 * Returns the primary key of this fondos mutuos.
	 *
	 * @return the primary key of this fondos mutuos
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fondos mutuos.
	 *
	 * @param primaryKey the primary key of this fondos mutuos
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id valor cuota of this fondos mutuos.
	 *
	 * @return the id valor cuota of this fondos mutuos
	 */
	public long getIdValorCuota();

	/**
	 * Sets the id valor cuota of this fondos mutuos.
	 *
	 * @param idValorCuota the id valor cuota of this fondos mutuos
	 */
	public void setIdValorCuota(long idValorCuota);

	/**
	 * Returns the codigo moneda of this fondos mutuos.
	 *
	 * @return the codigo moneda of this fondos mutuos
	 */
	@AutoEscape
	public String getCodigoMoneda();

	/**
	 * Sets the codigo moneda of this fondos mutuos.
	 *
	 * @param codigoMoneda the codigo moneda of this fondos mutuos
	 */
	public void setCodigoMoneda(String codigoMoneda);

	/**
	 * Returns the tipo fondo of this fondos mutuos.
	 *
	 * @return the tipo fondo of this fondos mutuos
	 */
	@AutoEscape
	public String getTipoFondo();

	/**
	 * Sets the tipo fondo of this fondos mutuos.
	 *
	 * @param tipoFondo the tipo fondo of this fondos mutuos
	 */
	public void setTipoFondo(String tipoFondo);

	/**
	 * Returns the valor cuota of this fondos mutuos.
	 *
	 * @return the valor cuota of this fondos mutuos
	 */
	public Double getValorCuota();

	/**
	 * Sets the valor cuota of this fondos mutuos.
	 *
	 * @param valorCuota the valor cuota of this fondos mutuos
	 */
	public void setValorCuota(Double valorCuota);

	/**
	 * Returns the fecha of this fondos mutuos.
	 *
	 * @return the fecha of this fondos mutuos
	 */
	@AutoEscape
	public String getFecha();

	/**
	 * Sets the fecha of this fondos mutuos.
	 *
	 * @param fecha the fecha of this fondos mutuos
	 */
	public void setFecha(String fecha);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FondosMutuos fondosMutuos);

	public int hashCode();

	public CacheModel<FondosMutuos> toCacheModel();

	public FondosMutuos toEscapedModel();

	public String toString();

	public String toXmlString();
}