/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FondosMutuosZonas service. Represents a row in the &quot;T_FONDOS_MUTUOS_ZONAS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.FondosMutuosZonasModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.FondosMutuosZonasImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see FondosMutuosZonas
 * @see com.ext.portlet.halcon.model.impl.FondosMutuosZonasImpl
 * @see com.ext.portlet.halcon.model.impl.FondosMutuosZonasModelImpl
 * @generated
 */
public interface FondosMutuosZonasModel extends BaseModel<FondosMutuosZonas> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fondos mutuos zonas model instance should use the {@link FondosMutuosZonas} interface instead.
	 */

	/**
	 * Returns the primary key of this fondos mutuos zonas.
	 *
	 * @return the primary key of this fondos mutuos zonas
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fondos mutuos zonas.
	 *
	 * @param primaryKey the primary key of this fondos mutuos zonas
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id fondo mutuo zona of this fondos mutuos zonas.
	 *
	 * @return the id fondo mutuo zona of this fondos mutuos zonas
	 */
	public long getIdFondoMutuoZona();

	/**
	 * Sets the id fondo mutuo zona of this fondos mutuos zonas.
	 *
	 * @param idFondoMutuoZona the id fondo mutuo zona of this fondos mutuos zonas
	 */
	public void setIdFondoMutuoZona(long idFondoMutuoZona);

	/**
	 * Returns the codigo zona of this fondos mutuos zonas.
	 *
	 * @return the codigo zona of this fondos mutuos zonas
	 */
	@AutoEscape
	public String getCodigoZona();

	/**
	 * Sets the codigo zona of this fondos mutuos zonas.
	 *
	 * @param codigoZona the codigo zona of this fondos mutuos zonas
	 */
	public void setCodigoZona(String codigoZona);

	/**
	 * Returns the zona of this fondos mutuos zonas.
	 *
	 * @return the zona of this fondos mutuos zonas
	 */
	@AutoEscape
	public String getZona();

	/**
	 * Sets the zona of this fondos mutuos zonas.
	 *
	 * @param zona the zona of this fondos mutuos zonas
	 */
	public void setZona(String zona);

	/**
	 * Returns the puntaje inicial of this fondos mutuos zonas.
	 *
	 * @return the puntaje inicial of this fondos mutuos zonas
	 */
	public Integer getPuntajeInicial();

	/**
	 * Sets the puntaje inicial of this fondos mutuos zonas.
	 *
	 * @param puntajeInicial the puntaje inicial of this fondos mutuos zonas
	 */
	public void setPuntajeInicial(Integer puntajeInicial);

	/**
	 * Returns the puntaje final of this fondos mutuos zonas.
	 *
	 * @return the puntaje final of this fondos mutuos zonas
	 */
	public Integer getPuntajeFinal();

	/**
	 * Sets the puntaje final of this fondos mutuos zonas.
	 *
	 * @param puntajeFinal the puntaje final of this fondos mutuos zonas
	 */
	public void setPuntajeFinal(Integer puntajeFinal);

	/**
	 * Returns the descripcion zona of this fondos mutuos zonas.
	 *
	 * @return the descripcion zona of this fondos mutuos zonas
	 */
	@AutoEscape
	public String getDescripcionZona();

	/**
	 * Sets the descripcion zona of this fondos mutuos zonas.
	 *
	 * @param descripcionZona the descripcion zona of this fondos mutuos zonas
	 */
	public void setDescripcionZona(String descripcionZona);

	/**
	 * Returns the moneda of this fondos mutuos zonas.
	 *
	 * @return the moneda of this fondos mutuos zonas
	 */
	@AutoEscape
	public String getMoneda();

	/**
	 * Sets the moneda of this fondos mutuos zonas.
	 *
	 * @param moneda the moneda of this fondos mutuos zonas
	 */
	public void setMoneda(String moneda);

	/**
	 * Returns the riesgo of this fondos mutuos zonas.
	 *
	 * @return the riesgo of this fondos mutuos zonas
	 */
	@AutoEscape
	public String getRiesgo();

	/**
	 * Sets the riesgo of this fondos mutuos zonas.
	 *
	 * @param riesgo the riesgo of this fondos mutuos zonas
	 */
	public void setRiesgo(String riesgo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FondosMutuosZonas fondosMutuosZonas);

	public int hashCode();

	public CacheModel<FondosMutuosZonas> toCacheModel();

	public FondosMutuosZonas toEscapedModel();

	public String toString();

	public String toXmlString();
}