/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LogIncidencias service. Represents a row in the &quot;T_ERROR_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.LogIncidenciasModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.LogIncidenciasImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see LogIncidencias
 * @see com.ext.portlet.halcon.model.impl.LogIncidenciasImpl
 * @see com.ext.portlet.halcon.model.impl.LogIncidenciasModelImpl
 * @generated
 */
public interface LogIncidenciasModel extends BaseModel<LogIncidencias> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a log incidencias model instance should use the {@link LogIncidencias} interface instead.
	 */

	/**
	 * Returns the primary key of this log incidencias.
	 *
	 * @return the primary key of this log incidencias
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this log incidencias.
	 *
	 * @param primaryKey the primary key of this log incidencias
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id error of this log incidencias.
	 *
	 * @return the id error of this log incidencias
	 */
	public long getIdError();

	/**
	 * Sets the id error of this log incidencias.
	 *
	 * @param idError the id error of this log incidencias
	 */
	public void setIdError(long idError);

	/**
	 * Returns the mensaje error of this log incidencias.
	 *
	 * @return the mensaje error of this log incidencias
	 */
	@AutoEscape
	public String getMensajeError();

	/**
	 * Sets the mensaje error of this log incidencias.
	 *
	 * @param mensajeError the mensaje error of this log incidencias
	 */
	public void setMensajeError(String mensajeError);

	/**
	 * Returns the parametro of this log incidencias.
	 *
	 * @return the parametro of this log incidencias
	 */
	@AutoEscape
	public String getParametro();

	/**
	 * Sets the parametro of this log incidencias.
	 *
	 * @param parametro the parametro of this log incidencias
	 */
	public void setParametro(String parametro);

	/**
	 * Returns the id session visitante of this log incidencias.
	 *
	 * @return the id session visitante of this log incidencias
	 */
	@AutoEscape
	public String getIdSessionVisitante();

	/**
	 * Sets the id session visitante of this log incidencias.
	 *
	 * @param idSessionVisitante the id session visitante of this log incidencias
	 */
	public void setIdSessionVisitante(String idSessionVisitante);

	/**
	 * Returns the tipo num doc of this log incidencias.
	 *
	 * @return the tipo num doc of this log incidencias
	 */
	@AutoEscape
	public String getTipoNumDoc();

	/**
	 * Sets the tipo num doc of this log incidencias.
	 *
	 * @param tipoNumDoc the tipo num doc of this log incidencias
	 */
	public void setTipoNumDoc(String tipoNumDoc);

	/**
	 * Returns the i p of this log incidencias.
	 *
	 * @return the i p of this log incidencias
	 */
	@AutoEscape
	public String getIP();

	/**
	 * Sets the i p of this log incidencias.
	 *
	 * @param IP the i p of this log incidencias
	 */
	public void setIP(String IP);

	/**
	 * Returns the fecha hora error of this log incidencias.
	 *
	 * @return the fecha hora error of this log incidencias
	 */
	public Date getFechaHoraError();

	/**
	 * Sets the fecha hora error of this log incidencias.
	 *
	 * @param fechaHoraError the fecha hora error of this log incidencias
	 */
	public void setFechaHoraError(Date fechaHoraError);

	/**
	 * Returns the traza error of this log incidencias.
	 *
	 * @return the traza error of this log incidencias
	 */
	@AutoEscape
	public String getTrazaError();

	/**
	 * Sets the traza error of this log incidencias.
	 *
	 * @param trazaError the traza error of this log incidencias
	 */
	public void setTrazaError(String trazaError);

	/**
	 * Returns the pagina hija of this log incidencias.
	 *
	 * @return the pagina hija of this log incidencias
	 */
	@AutoEscape
	public String getPaginaHija();

	/**
	 * Sets the pagina hija of this log incidencias.
	 *
	 * @param paginaHija the pagina hija of this log incidencias
	 */
	public void setPaginaHija(String paginaHija);

	/**
	 * Returns the user ID of this log incidencias.
	 *
	 * @return the user ID of this log incidencias
	 */
	@AutoEscape
	public String getUserId();

	/**
	 * Sets the user ID of this log incidencias.
	 *
	 * @param userId the user ID of this log incidencias
	 */
	public void setUserId(String userId);

	/**
	 * Returns the user name of this log incidencias.
	 *
	 * @return the user name of this log incidencias
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this log incidencias.
	 *
	 * @param userName the user name of this log incidencias
	 */
	public void setUserName(String userName);

	/**
	 * Returns the recurso ID of this log incidencias.
	 *
	 * @return the recurso ID of this log incidencias
	 */
	@AutoEscape
	public String getRecursoId();

	/**
	 * Sets the recurso ID of this log incidencias.
	 *
	 * @param recursoId the recurso ID of this log incidencias
	 */
	public void setRecursoId(String recursoId);

	/**
	 * Returns the recurso name of this log incidencias.
	 *
	 * @return the recurso name of this log incidencias
	 */
	@AutoEscape
	public String getRecursoName();

	/**
	 * Sets the recurso name of this log incidencias.
	 *
	 * @param recursoName the recurso name of this log incidencias
	 */
	public void setRecursoName(String recursoName);

	/**
	 * Returns the recurso action of this log incidencias.
	 *
	 * @return the recurso action of this log incidencias
	 */
	@AutoEscape
	public String getRecursoAction();

	/**
	 * Sets the recurso action of this log incidencias.
	 *
	 * @param recursoAction the recurso action of this log incidencias
	 */
	public void setRecursoAction(String recursoAction);

	/**
	 * Returns the create date of this log incidencias.
	 *
	 * @return the create date of this log incidencias
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this log incidencias.
	 *
	 * @param createDate the create date of this log incidencias
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the cliente host of this log incidencias.
	 *
	 * @return the cliente host of this log incidencias
	 */
	@AutoEscape
	public String getClienteHost();

	/**
	 * Sets the cliente host of this log incidencias.
	 *
	 * @param clienteHost the cliente host of this log incidencias
	 */
	public void setClienteHost(String clienteHost);

	/**
	 * Returns the server name of this log incidencias.
	 *
	 * @return the server name of this log incidencias
	 */
	@AutoEscape
	public String getServerName();

	/**
	 * Sets the server name of this log incidencias.
	 *
	 * @param serverName the server name of this log incidencias
	 */
	public void setServerName(String serverName);

	/**
	 * Returns the server ID of this log incidencias.
	 *
	 * @return the server ID of this log incidencias
	 */
	@AutoEscape
	public String getServerId();

	/**
	 * Sets the server ID of this log incidencias.
	 *
	 * @param serverId the server ID of this log incidencias
	 */
	public void setServerId(String serverId);

	/**
	 * Returns the additional information of this log incidencias.
	 *
	 * @return the additional information of this log incidencias
	 */
	@AutoEscape
	public String getAdditionalInformation();

	/**
	 * Sets the additional information of this log incidencias.
	 *
	 * @param additionalInformation the additional information of this log incidencias
	 */
	public void setAdditionalInformation(String additionalInformation);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LogIncidencias logIncidencias);

	public int hashCode();

	public CacheModel<LogIncidencias> toCacheModel();

	public LogIncidencias toEscapedModel();

	public String toString();

	public String toXmlString();
}