/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Ocurrencia service. Represents a row in the &quot;T_PETICION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.OcurrenciaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.OcurrenciaImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see Ocurrencia
 * @see com.ext.portlet.halcon.model.impl.OcurrenciaImpl
 * @see com.ext.portlet.halcon.model.impl.OcurrenciaModelImpl
 * @generated
 */
public interface OcurrenciaModel extends BaseModel<Ocurrencia> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ocurrencia model instance should use the {@link Ocurrencia} interface instead.
	 */

	/**
	 * Returns the primary key of this ocurrencia.
	 *
	 * @return the primary key of this ocurrencia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ocurrencia.
	 *
	 * @param primaryKey the primary key of this ocurrencia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id gestion peticion of this ocurrencia.
	 *
	 * @return the id gestion peticion of this ocurrencia
	 */
	public long getIdGestionPeticion();

	/**
	 * Sets the id gestion peticion of this ocurrencia.
	 *
	 * @param idGestionPeticion the id gestion peticion of this ocurrencia
	 */
	public void setIdGestionPeticion(long idGestionPeticion);

	/**
	 * Returns the ip of this ocurrencia.
	 *
	 * @return the ip of this ocurrencia
	 */
	@AutoEscape
	public String getIp();

	/**
	 * Sets the ip of this ocurrencia.
	 *
	 * @param ip the ip of this ocurrencia
	 */
	public void setIp(String ip);

	/**
	 * Returns the codigo producto of this ocurrencia.
	 *
	 * @return the codigo producto of this ocurrencia
	 */
	@AutoEscape
	public String getCodigoProducto();

	/**
	 * Sets the codigo producto of this ocurrencia.
	 *
	 * @param codigoProducto the codigo producto of this ocurrencia
	 */
	public void setCodigoProducto(String codigoProducto);

	/**
	 * Returns the fecha of this ocurrencia.
	 *
	 * @return the fecha of this ocurrencia
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this ocurrencia.
	 *
	 * @param fecha the fecha of this ocurrencia
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the estado of this ocurrencia.
	 *
	 * @return the estado of this ocurrencia
	 */
	public Integer getEstado();

	/**
	 * Sets the estado of this ocurrencia.
	 *
	 * @param estado the estado of this ocurrencia
	 */
	public void setEstado(Integer estado);

	/**
	 * Returns the ocurrencia of this ocurrencia.
	 *
	 * @return the ocurrencia of this ocurrencia
	 */
	public Integer getOcurrencia();

	/**
	 * Sets the ocurrencia of this ocurrencia.
	 *
	 * @param ocurrencia the ocurrencia of this ocurrencia
	 */
	public void setOcurrencia(Integer ocurrencia);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Ocurrencia ocurrencia);

	public int hashCode();

	public CacheModel<Ocurrencia> toCacheModel();

	public Ocurrencia toEscapedModel();

	public String toString();

	public String toXmlString();
}