/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Pais service. Represents a row in the &quot;T_PAIS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.PaisModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.PaisImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see Pais
 * @see com.ext.portlet.halcon.model.impl.PaisImpl
 * @see com.ext.portlet.halcon.model.impl.PaisModelImpl
 * @generated
 */
public interface PaisModel extends BaseModel<Pais> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pais model instance should use the {@link Pais} interface instead.
	 */

	/**
	 * Returns the primary key of this pais.
	 *
	 * @return the primary key of this pais
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pais.
	 *
	 * @param primaryKey the primary key of this pais
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pais_ ID pais of this pais.
	 *
	 * @return the pais_ ID pais of this pais
	 */
	public long getPais_IdPais();

	/**
	 * Sets the pais_ ID pais of this pais.
	 *
	 * @param pais_IdPais the pais_ ID pais of this pais
	 */
	public void setPais_IdPais(long pais_IdPais);

	/**
	 * Returns the codigo of this pais.
	 *
	 * @return the codigo of this pais
	 */
	@AutoEscape
	public String getCodigo();

	/**
	 * Sets the codigo of this pais.
	 *
	 * @param codigo the codigo of this pais
	 */
	public void setCodigo(String codigo);

	/**
	 * Returns the nombre of this pais.
	 *
	 * @return the nombre of this pais
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this pais.
	 *
	 * @param nombre the nombre of this pais
	 */
	public void setNombre(String nombre);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Pais pais);

	public int hashCode();

	public CacheModel<Pais> toCacheModel();

	public Pais toEscapedModel();

	public String toString();

	public String toXmlString();
}