/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Parametro service. Represents a row in the &quot;T_PARAMETRO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.ParametroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.ParametroImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see Parametro
 * @see com.ext.portlet.halcon.model.impl.ParametroImpl
 * @see com.ext.portlet.halcon.model.impl.ParametroModelImpl
 * @generated
 */
public interface ParametroModel extends BaseModel<Parametro> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parametro model instance should use the {@link Parametro} interface instead.
	 */

	/**
	 * Returns the primary key of this parametro.
	 *
	 * @return the primary key of this parametro
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this parametro.
	 *
	 * @param primaryKey the primary key of this parametro
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id parametro of this parametro.
	 *
	 * @return the id parametro of this parametro
	 */
	public int getIdParametro();

	/**
	 * Sets the id parametro of this parametro.
	 *
	 * @param idParametro the id parametro of this parametro
	 */
	public void setIdParametro(int idParametro);

	/**
	 * Returns the id parametro padre of this parametro.
	 *
	 * @return the id parametro padre of this parametro
	 */
	public Integer getIdParametroPadre();

	/**
	 * Sets the id parametro padre of this parametro.
	 *
	 * @param idParametroPadre the id parametro padre of this parametro
	 */
	public void setIdParametroPadre(Integer idParametroPadre);

	/**
	 * Returns the valor monto1 of this parametro.
	 *
	 * @return the valor monto1 of this parametro
	 */
	@AutoEscape
	public String getValorMonto1();

	/**
	 * Sets the valor monto1 of this parametro.
	 *
	 * @param valorMonto1 the valor monto1 of this parametro
	 */
	public void setValorMonto1(String valorMonto1);

	/**
	 * Returns the valor monto2 of this parametro.
	 *
	 * @return the valor monto2 of this parametro
	 */
	@AutoEscape
	public String getValorMonto2();

	/**
	 * Sets the valor monto2 of this parametro.
	 *
	 * @param valorMonto2 the valor monto2 of this parametro
	 */
	public void setValorMonto2(String valorMonto2);

	/**
	 * Returns the valor monto3 of this parametro.
	 *
	 * @return the valor monto3 of this parametro
	 */
	@AutoEscape
	public String getValorMonto3();

	/**
	 * Sets the valor monto3 of this parametro.
	 *
	 * @param valorMonto3 the valor monto3 of this parametro
	 */
	public void setValorMonto3(String valorMonto3);

	/**
	 * Returns the dato1 of this parametro.
	 *
	 * @return the dato1 of this parametro
	 */
	@AutoEscape
	public String getDato1();

	/**
	 * Sets the dato1 of this parametro.
	 *
	 * @param dato1 the dato1 of this parametro
	 */
	public void setDato1(String dato1);

	/**
	 * Returns the dato2 of this parametro.
	 *
	 * @return the dato2 of this parametro
	 */
	@AutoEscape
	public String getDato2();

	/**
	 * Sets the dato2 of this parametro.
	 *
	 * @param dato2 the dato2 of this parametro
	 */
	public void setDato2(String dato2);

	/**
	 * Returns the dato3 of this parametro.
	 *
	 * @return the dato3 of this parametro
	 */
	@AutoEscape
	public String getDato3();

	/**
	 * Sets the dato3 of this parametro.
	 *
	 * @param dato3 the dato3 of this parametro
	 */
	public void setDato3(String dato3);

	/**
	 * Returns the dato4 of this parametro.
	 *
	 * @return the dato4 of this parametro
	 */
	@AutoEscape
	public String getDato4();

	/**
	 * Sets the dato4 of this parametro.
	 *
	 * @param dato4 the dato4 of this parametro
	 */
	public void setDato4(String dato4);

	/**
	 * Returns the num1 of this parametro.
	 *
	 * @return the num1 of this parametro
	 */
	public Integer getNum1();

	/**
	 * Sets the num1 of this parametro.
	 *
	 * @param num1 the num1 of this parametro
	 */
	public void setNum1(Integer num1);

	/**
	 * Returns the num2 of this parametro.
	 *
	 * @return the num2 of this parametro
	 */
	public Integer getNum2();

	/**
	 * Sets the num2 of this parametro.
	 *
	 * @param num2 the num2 of this parametro
	 */
	public void setNum2(Integer num2);

	/**
	 * Returns the num3 of this parametro.
	 *
	 * @return the num3 of this parametro
	 */
	public Integer getNum3();

	/**
	 * Sets the num3 of this parametro.
	 *
	 * @param num3 the num3 of this parametro
	 */
	public void setNum3(Integer num3);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Parametro parametro);

	public int hashCode();

	public CacheModel<Parametro> toCacheModel();

	public Parametro toEscapedModel();

	public String toString();

	public String toXmlString();
}