/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ProductoComplementario service. Represents a row in the &quot;T_PRODUCTO_COMPLEMENTARIO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.ProductoComplementarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.ProductoComplementarioImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see ProductoComplementario
 * @see com.ext.portlet.halcon.model.impl.ProductoComplementarioImpl
 * @see com.ext.portlet.halcon.model.impl.ProductoComplementarioModelImpl
 * @generated
 */
public interface ProductoComplementarioModel extends BaseModel<ProductoComplementario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a producto complementario model instance should use the {@link ProductoComplementario} interface instead.
	 */

	/**
	 * Returns the primary key of this producto complementario.
	 *
	 * @return the primary key of this producto complementario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this producto complementario.
	 *
	 * @param primaryKey the primary key of this producto complementario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id producto complementario of this producto complementario.
	 *
	 * @return the id producto complementario of this producto complementario
	 */
	public long getIdProductoComplementario();

	/**
	 * Sets the id producto complementario of this producto complementario.
	 *
	 * @param idProductoComplementario the id producto complementario of this producto complementario
	 */
	public void setIdProductoComplementario(long idProductoComplementario);

	/**
	 * Returns the id solicitud producto of this producto complementario.
	 *
	 * @return the id solicitud producto of this producto complementario
	 */
	public long getIdSolicitudProducto();

	/**
	 * Sets the id solicitud producto of this producto complementario.
	 *
	 * @param idSolicitudProducto the id solicitud producto of this producto complementario
	 */
	public void setIdSolicitudProducto(long idSolicitudProducto);

	/**
	 * Returns the principalidad of this producto complementario.
	 *
	 * @return the principalidad of this producto complementario
	 */
	@AutoEscape
	public String getPrincipalidad();

	/**
	 * Sets the principalidad of this producto complementario.
	 *
	 * @param principalidad the principalidad of this producto complementario
	 */
	public void setPrincipalidad(String principalidad);

	/**
	 * Returns the producto of this producto complementario.
	 *
	 * @return the producto of this producto complementario
	 */
	@AutoEscape
	public String getProducto();

	/**
	 * Sets the producto of this producto complementario.
	 *
	 * @param producto the producto of this producto complementario
	 */
	public void setProducto(String producto);

	/**
	 * Returns the id producto of this producto complementario.
	 *
	 * @return the id producto of this producto complementario
	 */
	@AutoEscape
	public String getIdProducto();

	/**
	 * Sets the id producto of this producto complementario.
	 *
	 * @param idProducto the id producto of this producto complementario
	 */
	public void setIdProducto(String idProducto);

	/**
	 * Returns the id grupo producto of this producto complementario.
	 *
	 * @return the id grupo producto of this producto complementario
	 */
	@AutoEscape
	public String getIdGrupoProducto();

	/**
	 * Sets the id grupo producto of this producto complementario.
	 *
	 * @param idGrupoProducto the id grupo producto of this producto complementario
	 */
	public void setIdGrupoProducto(String idGrupoProducto);

	/**
	 * Returns the email supervisor of this producto complementario.
	 *
	 * @return the email supervisor of this producto complementario
	 */
	@AutoEscape
	public String getEmailSupervisor();

	/**
	 * Sets the email supervisor of this producto complementario.
	 *
	 * @param emailSupervisor the email supervisor of this producto complementario
	 */
	public void setEmailSupervisor(String emailSupervisor);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProductoComplementario productoComplementario);

	public int hashCode();

	public CacheModel<ProductoComplementario> toCacheModel();

	public ProductoComplementario toEscapedModel();

	public String toString();

	public String toXmlString();
}