/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudContacto service. Represents a row in the &quot;T_SOLICITUD_CONTACTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.SolicitudContactoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.SolicitudContactoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see SolicitudContacto
 * @see com.ext.portlet.halcon.model.impl.SolicitudContactoImpl
 * @see com.ext.portlet.halcon.model.impl.SolicitudContactoModelImpl
 * @generated
 */
public interface SolicitudContactoModel extends BaseModel<SolicitudContacto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud contacto model instance should use the {@link SolicitudContacto} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud contacto.
	 *
	 * @return the primary key of this solicitud contacto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud contacto.
	 *
	 * @param primaryKey the primary key of this solicitud contacto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id solicitud contacto of this solicitud contacto.
	 *
	 * @return the id solicitud contacto of this solicitud contacto
	 */
	public long getIdSolicitudContacto();

	/**
	 * Sets the id solicitud contacto of this solicitud contacto.
	 *
	 * @param idSolicitudContacto the id solicitud contacto of this solicitud contacto
	 */
	public void setIdSolicitudContacto(long idSolicitudContacto);

	/**
	 * Returns the es cliente of this solicitud contacto.
	 *
	 * @return the es cliente of this solicitud contacto
	 */
	public Integer getEsCliente();

	/**
	 * Sets the es cliente of this solicitud contacto.
	 *
	 * @param esCliente the es cliente of this solicitud contacto
	 */
	public void setEsCliente(Integer esCliente);

	/**
	 * Returns the nombres of this solicitud contacto.
	 *
	 * @return the nombres of this solicitud contacto
	 */
	@AutoEscape
	public String getNombres();

	/**
	 * Sets the nombres of this solicitud contacto.
	 *
	 * @param nombres the nombres of this solicitud contacto
	 */
	public void setNombres(String nombres);

	/**
	 * Returns the apellidos of this solicitud contacto.
	 *
	 * @return the apellidos of this solicitud contacto
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this solicitud contacto.
	 *
	 * @param apellidos the apellidos of this solicitud contacto
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the email of this solicitud contacto.
	 *
	 * @return the email of this solicitud contacto
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this solicitud contacto.
	 *
	 * @param email the email of this solicitud contacto
	 */
	public void setEmail(String email);

	/**
	 * Returns the tipo documento of this solicitud contacto.
	 *
	 * @return the tipo documento of this solicitud contacto
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this solicitud contacto.
	 *
	 * @param tipoDocumento the tipo documento of this solicitud contacto
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the ndocumento of this solicitud contacto.
	 *
	 * @return the ndocumento of this solicitud contacto
	 */
	@AutoEscape
	public String getNdocumento();

	/**
	 * Sets the ndocumento of this solicitud contacto.
	 *
	 * @param ndocumento the ndocumento of this solicitud contacto
	 */
	public void setNdocumento(String ndocumento);

	/**
	 * Returns the direccion of this solicitud contacto.
	 *
	 * @return the direccion of this solicitud contacto
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this solicitud contacto.
	 *
	 * @param direccion the direccion of this solicitud contacto
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the departamento of this solicitud contacto.
	 *
	 * @return the departamento of this solicitud contacto
	 */
	@AutoEscape
	public String getDepartamento();

	/**
	 * Sets the departamento of this solicitud contacto.
	 *
	 * @param departamento the departamento of this solicitud contacto
	 */
	public void setDepartamento(String departamento);

	/**
	 * Returns the provincia of this solicitud contacto.
	 *
	 * @return the provincia of this solicitud contacto
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this solicitud contacto.
	 *
	 * @param provincia the provincia of this solicitud contacto
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the distrito of this solicitud contacto.
	 *
	 * @return the distrito of this solicitud contacto
	 */
	@AutoEscape
	public String getDistrito();

	/**
	 * Sets the distrito of this solicitud contacto.
	 *
	 * @param distrito the distrito of this solicitud contacto
	 */
	public void setDistrito(String distrito);

	/**
	 * Returns the telefono of this solicitud contacto.
	 *
	 * @return the telefono of this solicitud contacto
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this solicitud contacto.
	 *
	 * @param telefono the telefono of this solicitud contacto
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the fecha of this solicitud contacto.
	 *
	 * @return the fecha of this solicitud contacto
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this solicitud contacto.
	 *
	 * @param fecha the fecha of this solicitud contacto
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the mensaje of this solicitud contacto.
	 *
	 * @return the mensaje of this solicitud contacto
	 */
	@AutoEscape
	public String getMensaje();

	/**
	 * Sets the mensaje of this solicitud contacto.
	 *
	 * @param mensaje the mensaje of this solicitud contacto
	 */
	public void setMensaje(String mensaje);

	/**
	 * Returns the moneda of this solicitud contacto.
	 *
	 * @return the moneda of this solicitud contacto
	 */
	@AutoEscape
	public String getMoneda();

	/**
	 * Sets the moneda of this solicitud contacto.
	 *
	 * @param moneda the moneda of this solicitud contacto
	 */
	public void setMoneda(String moneda);

	/**
	 * Returns the importe of this solicitud contacto.
	 *
	 * @return the importe of this solicitud contacto
	 */
	@AutoEscape
	public String getImporte();

	/**
	 * Sets the importe of this solicitud contacto.
	 *
	 * @param importe the importe of this solicitud contacto
	 */
	public void setImporte(String importe);

	/**
	 * Returns the tipo mensaje of this solicitud contacto.
	 *
	 * @return the tipo mensaje of this solicitud contacto
	 */
	@AutoEscape
	public String getTipoMensaje();

	/**
	 * Sets the tipo mensaje of this solicitud contacto.
	 *
	 * @param tipoMensaje the tipo mensaje of this solicitud contacto
	 */
	public void setTipoMensaje(String tipoMensaje);

	/**
	 * Returns the tipo tema of this solicitud contacto.
	 *
	 * @return the tipo tema of this solicitud contacto
	 */
	@AutoEscape
	public String getTipoTema();

	/**
	 * Sets the tipo tema of this solicitud contacto.
	 *
	 * @param tipoTema the tipo tema of this solicitud contacto
	 */
	public void setTipoTema(String tipoTema);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SolicitudContacto solicitudContacto);

	public int hashCode();

	public CacheModel<SolicitudContacto> toCacheModel();

	public SolicitudContacto toEscapedModel();

	public String toString();

	public String toXmlString();
}