/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudProducto service. Represents a row in the &quot;T_SOLICITUD_PRODUCTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.SolicitudProductoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.SolicitudProductoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see SolicitudProducto
 * @see com.ext.portlet.halcon.model.impl.SolicitudProductoImpl
 * @see com.ext.portlet.halcon.model.impl.SolicitudProductoModelImpl
 * @generated
 */
public interface SolicitudProductoModel extends BaseModel<SolicitudProducto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud producto model instance should use the {@link SolicitudProducto} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud producto.
	 *
	 * @return the primary key of this solicitud producto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud producto.
	 *
	 * @param primaryKey the primary key of this solicitud producto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id solicitud producto of this solicitud producto.
	 *
	 * @return the id solicitud producto of this solicitud producto
	 */
	public long getIdSolicitudProducto();

	/**
	 * Sets the id solicitud producto of this solicitud producto.
	 *
	 * @param idSolicitudProducto the id solicitud producto of this solicitud producto
	 */
	public void setIdSolicitudProducto(long idSolicitudProducto);

	/**
	 * Returns the id tipo documento adq of this solicitud producto.
	 *
	 * @return the id tipo documento adq of this solicitud producto
	 */
	public Integer getIdTipoDocumentoAdq();

	/**
	 * Sets the id tipo documento adq of this solicitud producto.
	 *
	 * @param idTipoDocumentoAdq the id tipo documento adq of this solicitud producto
	 */
	public void setIdTipoDocumentoAdq(Integer idTipoDocumentoAdq);

	/**
	 * Returns the id tipo documento of this solicitud producto.
	 *
	 * @return the id tipo documento of this solicitud producto
	 */
	@AutoEscape
	public String getIdTipoDocumento();

	/**
	 * Sets the id tipo documento of this solicitud producto.
	 *
	 * @param idTipoDocumento the id tipo documento of this solicitud producto
	 */
	public void setIdTipoDocumento(String idTipoDocumento);

	/**
	 * Returns the tipo credito of this solicitud producto.
	 *
	 * @return the tipo credito of this solicitud producto
	 */
	public Integer getTipoCredito();

	/**
	 * Sets the tipo credito of this solicitud producto.
	 *
	 * @param tipoCredito the tipo credito of this solicitud producto
	 */
	public void setTipoCredito(Integer tipoCredito);

	/**
	 * Returns the codigo canal of this solicitud producto.
	 *
	 * @return the codigo canal of this solicitud producto
	 */
	@AutoEscape
	public String getCodigoCanal();

	/**
	 * Sets the codigo canal of this solicitud producto.
	 *
	 * @param codigoCanal the codigo canal of this solicitud producto
	 */
	public void setCodigoCanal(String codigoCanal);

	/**
	 * Returns the tipo envio of this solicitud producto.
	 *
	 * @return the tipo envio of this solicitud producto
	 */
	@AutoEscape
	public String getTipoEnvio();

	/**
	 * Sets the tipo envio of this solicitud producto.
	 *
	 * @param tipoEnvio the tipo envio of this solicitud producto
	 */
	public void setTipoEnvio(String tipoEnvio);

	/**
	 * Returns the numero documento of this solicitud producto.
	 *
	 * @return the numero documento of this solicitud producto
	 */
	@AutoEscape
	public String getNumeroDocumento();

	/**
	 * Sets the numero documento of this solicitud producto.
	 *
	 * @param numeroDocumento the numero documento of this solicitud producto
	 */
	public void setNumeroDocumento(String numeroDocumento);

	/**
	 * Returns the apellido paterno of this solicitud producto.
	 *
	 * @return the apellido paterno of this solicitud producto
	 */
	@AutoEscape
	public String getApellidoPaterno();

	/**
	 * Sets the apellido paterno of this solicitud producto.
	 *
	 * @param apellidoPaterno the apellido paterno of this solicitud producto
	 */
	public void setApellidoPaterno(String apellidoPaterno);

	/**
	 * Returns the apellido materno of this solicitud producto.
	 *
	 * @return the apellido materno of this solicitud producto
	 */
	@AutoEscape
	public String getApellidoMaterno();

	/**
	 * Sets the apellido materno of this solicitud producto.
	 *
	 * @param apellidoMaterno the apellido materno of this solicitud producto
	 */
	public void setApellidoMaterno(String apellidoMaterno);

	/**
	 * Returns the primer nombre of this solicitud producto.
	 *
	 * @return the primer nombre of this solicitud producto
	 */
	@AutoEscape
	public String getPrimerNombre();

	/**
	 * Sets the primer nombre of this solicitud producto.
	 *
	 * @param primerNombre the primer nombre of this solicitud producto
	 */
	public void setPrimerNombre(String primerNombre);

	/**
	 * Returns the segundo nombre of this solicitud producto.
	 *
	 * @return the segundo nombre of this solicitud producto
	 */
	@AutoEscape
	public String getSegundoNombre();

	/**
	 * Sets the segundo nombre of this solicitud producto.
	 *
	 * @param segundoNombre the segundo nombre of this solicitud producto
	 */
	public void setSegundoNombre(String segundoNombre);

	/**
	 * Returns the fecha nacimiento of this solicitud producto.
	 *
	 * @return the fecha nacimiento of this solicitud producto
	 */
	public Date getFechaNacimiento();

	/**
	 * Sets the fecha nacimiento of this solicitud producto.
	 *
	 * @param fechaNacimiento the fecha nacimiento of this solicitud producto
	 */
	public void setFechaNacimiento(Date fechaNacimiento);

	/**
	 * Returns the sexo of this solicitud producto.
	 *
	 * @return the sexo of this solicitud producto
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this solicitud producto.
	 *
	 * @param sexo the sexo of this solicitud producto
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the renta mensual of this solicitud producto.
	 *
	 * @return the renta mensual of this solicitud producto
	 */
	public Double getRentaMensual();

	/**
	 * Sets the renta mensual of this solicitud producto.
	 *
	 * @param rentaMensual the renta mensual of this solicitud producto
	 */
	public void setRentaMensual(Double rentaMensual);

	/**
	 * Returns the celular of this solicitud producto.
	 *
	 * @return the celular of this solicitud producto
	 */
	@AutoEscape
	public String getCelular();

	/**
	 * Sets the celular of this solicitud producto.
	 *
	 * @param celular the celular of this solicitud producto
	 */
	public void setCelular(String celular);

	/**
	 * Returns the telefono casa of this solicitud producto.
	 *
	 * @return the telefono casa of this solicitud producto
	 */
	@AutoEscape
	public String getTelefonoCasa();

	/**
	 * Sets the telefono casa of this solicitud producto.
	 *
	 * @param telefonoCasa the telefono casa of this solicitud producto
	 */
	public void setTelefonoCasa(String telefonoCasa);

	/**
	 * Returns the telefono trabajo of this solicitud producto.
	 *
	 * @return the telefono trabajo of this solicitud producto
	 */
	@AutoEscape
	public String getTelefonoTrabajo();

	/**
	 * Sets the telefono trabajo of this solicitud producto.
	 *
	 * @param telefonoTrabajo the telefono trabajo of this solicitud producto
	 */
	public void setTelefonoTrabajo(String telefonoTrabajo);

	/**
	 * Returns the anexo of this solicitud producto.
	 *
	 * @return the anexo of this solicitud producto
	 */
	@AutoEscape
	public String getAnexo();

	/**
	 * Sets the anexo of this solicitud producto.
	 *
	 * @param anexo the anexo of this solicitud producto
	 */
	public void setAnexo(String anexo);

	/**
	 * Returns the id estado civil adq of this solicitud producto.
	 *
	 * @return the id estado civil adq of this solicitud producto
	 */
	public Integer getIdEstadoCivilAdq();

	/**
	 * Sets the id estado civil adq of this solicitud producto.
	 *
	 * @param idEstadoCivilAdq the id estado civil adq of this solicitud producto
	 */
	public void setIdEstadoCivilAdq(Integer idEstadoCivilAdq);

	/**
	 * Returns the id estado civil of this solicitud producto.
	 *
	 * @return the id estado civil of this solicitud producto
	 */
	@AutoEscape
	public String getIdEstadoCivil();

	/**
	 * Sets the id estado civil of this solicitud producto.
	 *
	 * @param idEstadoCivil the id estado civil of this solicitud producto
	 */
	public void setIdEstadoCivil(String idEstadoCivil);

	/**
	 * Returns the r u c of this solicitud producto.
	 *
	 * @return the r u c of this solicitud producto
	 */
	@AutoEscape
	public String getRUC();

	/**
	 * Sets the r u c of this solicitud producto.
	 *
	 * @param RUC the r u c of this solicitud producto
	 */
	public void setRUC(String RUC);

	/**
	 * Returns the razon social of this solicitud producto.
	 *
	 * @return the razon social of this solicitud producto
	 */
	@AutoEscape
	public String getRazonSocial();

	/**
	 * Sets the razon social of this solicitud producto.
	 *
	 * @param razonSocial the razon social of this solicitud producto
	 */
	public void setRazonSocial(String razonSocial);

	/**
	 * Returns the situacion laboral of this solicitud producto.
	 *
	 * @return the situacion laboral of this solicitud producto
	 */
	@AutoEscape
	public String getSituacionLaboral();

	/**
	 * Sets the situacion laboral of this solicitud producto.
	 *
	 * @param situacionLaboral the situacion laboral of this solicitud producto
	 */
	public void setSituacionLaboral(String situacionLaboral);

	/**
	 * Returns the id situacion laboral of this solicitud producto.
	 *
	 * @return the id situacion laboral of this solicitud producto
	 */
	public Integer getIdSituacionLaboral();

	/**
	 * Sets the id situacion laboral of this solicitud producto.
	 *
	 * @param idSituacionLaboral the id situacion laboral of this solicitud producto
	 */
	public void setIdSituacionLaboral(Integer idSituacionLaboral);

	/**
	 * Returns the id departamento of this solicitud producto.
	 *
	 * @return the id departamento of this solicitud producto
	 */
	@AutoEscape
	public String getIdDepartamento();

	/**
	 * Sets the id departamento of this solicitud producto.
	 *
	 * @param idDepartamento the id departamento of this solicitud producto
	 */
	public void setIdDepartamento(String idDepartamento);

	/**
	 * Returns the id provincia of this solicitud producto.
	 *
	 * @return the id provincia of this solicitud producto
	 */
	@AutoEscape
	public String getIdProvincia();

	/**
	 * Sets the id provincia of this solicitud producto.
	 *
	 * @param idProvincia the id provincia of this solicitud producto
	 */
	public void setIdProvincia(String idProvincia);

	/**
	 * Returns the id distrito of this solicitud producto.
	 *
	 * @return the id distrito of this solicitud producto
	 */
	@AutoEscape
	public String getIdDistrito();

	/**
	 * Sets the id distrito of this solicitud producto.
	 *
	 * @param idDistrito the id distrito of this solicitud producto
	 */
	public void setIdDistrito(String idDistrito);

	/**
	 * Returns the nom departamento of this solicitud producto.
	 *
	 * @return the nom departamento of this solicitud producto
	 */
	@AutoEscape
	public String getNomDepartamento();

	/**
	 * Sets the nom departamento of this solicitud producto.
	 *
	 * @param nomDepartamento the nom departamento of this solicitud producto
	 */
	public void setNomDepartamento(String nomDepartamento);

	/**
	 * Returns the nom provincia of this solicitud producto.
	 *
	 * @return the nom provincia of this solicitud producto
	 */
	@AutoEscape
	public String getNomProvincia();

	/**
	 * Sets the nom provincia of this solicitud producto.
	 *
	 * @param nomProvincia the nom provincia of this solicitud producto
	 */
	public void setNomProvincia(String nomProvincia);

	/**
	 * Returns the nom distrito of this solicitud producto.
	 *
	 * @return the nom distrito of this solicitud producto
	 */
	@AutoEscape
	public String getNomDistrito();

	/**
	 * Sets the nom distrito of this solicitud producto.
	 *
	 * @param nomDistrito the nom distrito of this solicitud producto
	 */
	public void setNomDistrito(String nomDistrito);

	/**
	 * Returns the correo electronico of this solicitud producto.
	 *
	 * @return the correo electronico of this solicitud producto
	 */
	@AutoEscape
	public String getCorreoElectronico();

	/**
	 * Sets the correo electronico of this solicitud producto.
	 *
	 * @param correoElectronico the correo electronico of this solicitud producto
	 */
	public void setCorreoElectronico(String correoElectronico);

	/**
	 * Returns the direccion envio of this solicitud producto.
	 *
	 * @return the direccion envio of this solicitud producto
	 */
	@AutoEscape
	public String getDireccionEnvio();

	/**
	 * Sets the direccion envio of this solicitud producto.
	 *
	 * @param direccionEnvio the direccion envio of this solicitud producto
	 */
	public void setDireccionEnvio(String direccionEnvio);

	/**
	 * Returns the placa vehiculo of this solicitud producto.
	 *
	 * @return the placa vehiculo of this solicitud producto
	 */
	@AutoEscape
	public String getPlacaVehiculo();

	/**
	 * Sets the placa vehiculo of this solicitud producto.
	 *
	 * @param placaVehiculo the placa vehiculo of this solicitud producto
	 */
	public void setPlacaVehiculo(String placaVehiculo);

	/**
	 * Returns the id session of this solicitud producto.
	 *
	 * @return the id session of this solicitud producto
	 */
	@AutoEscape
	public String getIdSession();

	/**
	 * Sets the id session of this solicitud producto.
	 *
	 * @param IdSession the id session of this solicitud producto
	 */
	public void setIdSession(String IdSession);

	/**
	 * Returns the i p cliente of this solicitud producto.
	 *
	 * @return the i p cliente of this solicitud producto
	 */
	@AutoEscape
	public String getIPCliente();

	/**
	 * Sets the i p cliente of this solicitud producto.
	 *
	 * @param IPCliente the i p cliente of this solicitud producto
	 */
	public void setIPCliente(String IPCliente);

	/**
	 * Returns the horario envio of this solicitud producto.
	 *
	 * @return the horario envio of this solicitud producto
	 */
	public Date getHorarioEnvio();

	/**
	 * Sets the horario envio of this solicitud producto.
	 *
	 * @param horarioEnvio the horario envio of this solicitud producto
	 */
	public void setHorarioEnvio(Date horarioEnvio);

	/**
	 * Returns the fecha registro of this solicitud producto.
	 *
	 * @return the fecha registro of this solicitud producto
	 */
	public Date getFechaRegistro();

	/**
	 * Sets the fecha registro of this solicitud producto.
	 *
	 * @param fechaRegistro the fecha registro of this solicitud producto
	 */
	public void setFechaRegistro(Date fechaRegistro);

	/**
	 * Returns the u t m source of this solicitud producto.
	 *
	 * @return the u t m source of this solicitud producto
	 */
	@AutoEscape
	public String getUTMSource();

	/**
	 * Sets the u t m source of this solicitud producto.
	 *
	 * @param UTMSource the u t m source of this solicitud producto
	 */
	public void setUTMSource(String UTMSource);

	/**
	 * Returns the u t m medium of this solicitud producto.
	 *
	 * @return the u t m medium of this solicitud producto
	 */
	@AutoEscape
	public String getUTMMedium();

	/**
	 * Sets the u t m medium of this solicitud producto.
	 *
	 * @param UTMMedium the u t m medium of this solicitud producto
	 */
	public void setUTMMedium(String UTMMedium);

	/**
	 * Returns the u t m campaing of this solicitud producto.
	 *
	 * @return the u t m campaing of this solicitud producto
	 */
	@AutoEscape
	public String getUTMCampaing();

	/**
	 * Sets the u t m campaing of this solicitud producto.
	 *
	 * @param UTMCampaing the u t m campaing of this solicitud producto
	 */
	public void setUTMCampaing(String UTMCampaing);

	/**
	 * Returns the u t m content of this solicitud producto.
	 *
	 * @return the u t m content of this solicitud producto
	 */
	@AutoEscape
	public String getUTMContent();

	/**
	 * Sets the u t m content of this solicitud producto.
	 *
	 * @param UTMContent the u t m content of this solicitud producto
	 */
	public void setUTMContent(String UTMContent);

	/**
	 * Returns the fecha resultado pre calif of this solicitud producto.
	 *
	 * @return the fecha resultado pre calif of this solicitud producto
	 */
	public Date getFechaResultadoPreCalif();

	/**
	 * Sets the fecha resultado pre calif of this solicitud producto.
	 *
	 * @param fechaResultadoPreCalif the fecha resultado pre calif of this solicitud producto
	 */
	public void setFechaResultadoPreCalif(Date fechaResultadoPreCalif);

	/**
	 * Returns the fecha envio lead of this solicitud producto.
	 *
	 * @return the fecha envio lead of this solicitud producto
	 */
	public Date getFechaEnvioLead();

	/**
	 * Sets the fecha envio lead of this solicitud producto.
	 *
	 * @param fechaEnvioLead the fecha envio lead of this solicitud producto
	 */
	public void setFechaEnvioLead(Date fechaEnvioLead);

	/**
	 * Returns the fecha envio emailing of this solicitud producto.
	 *
	 * @return the fecha envio emailing of this solicitud producto
	 */
	public Date getFechaEnvioEmailing();

	/**
	 * Sets the fecha envio emailing of this solicitud producto.
	 *
	 * @param fechaEnvioEmailing the fecha envio emailing of this solicitud producto
	 */
	public void setFechaEnvioEmailing(Date fechaEnvioEmailing);

	/**
	 * Returns the estado pre calificacion of this solicitud producto.
	 *
	 * @return the estado pre calificacion of this solicitud producto
	 */
	public Boolean getEstadoPreCalificacion();

	/**
	 * Sets the estado pre calificacion of this solicitud producto.
	 *
	 * @param estadoPreCalificacion the estado pre calificacion of this solicitud producto
	 */
	public void setEstadoPreCalificacion(Boolean estadoPreCalificacion);

	/**
	 * Returns the estado reg lead of this solicitud producto.
	 *
	 * @return the estado reg lead of this solicitud producto
	 */
	public Boolean getEstadoRegLead();

	/**
	 * Sets the estado reg lead of this solicitud producto.
	 *
	 * @param estadoRegLead the estado reg lead of this solicitud producto
	 */
	public void setEstadoRegLead(Boolean estadoRegLead);

	/**
	 * Returns the estado env correo of this solicitud producto.
	 *
	 * @return the estado env correo of this solicitud producto
	 */
	public Boolean getEstadoEnvCorreo();

	/**
	 * Sets the estado env correo of this solicitud producto.
	 *
	 * @param estadoEnvCorreo the estado env correo of this solicitud producto
	 */
	public void setEstadoEnvCorreo(Boolean estadoEnvCorreo);

	/**
	 * Returns the resp pre calificacion of this solicitud producto.
	 *
	 * @return the resp pre calificacion of this solicitud producto
	 */
	@AutoEscape
	public String getRespPreCalificacion();

	/**
	 * Sets the resp pre calificacion of this solicitud producto.
	 *
	 * @param respPreCalificacion the resp pre calificacion of this solicitud producto
	 */
	public void setRespPreCalificacion(String respPreCalificacion);

	/**
	 * Returns the descripcion lead of this solicitud producto.
	 *
	 * @return the descripcion lead of this solicitud producto
	 */
	@AutoEscape
	public String getDescripcionLead();

	/**
	 * Sets the descripcion lead of this solicitud producto.
	 *
	 * @param descripcionLead the descripcion lead of this solicitud producto
	 */
	public void setDescripcionLead(String descripcionLead);

	/**
	 * Returns the fecha actualizacion of this solicitud producto.
	 *
	 * @return the fecha actualizacion of this solicitud producto
	 */
	public Date getFechaActualizacion();

	/**
	 * Sets the fecha actualizacion of this solicitud producto.
	 *
	 * @param fechaActualizacion the fecha actualizacion of this solicitud producto
	 */
	public void setFechaActualizacion(Date fechaActualizacion);

	/**
	 * Returns the monto prospectado of this solicitud producto.
	 *
	 * @return the monto prospectado of this solicitud producto
	 */
	public Double getMontoProspectado();

	/**
	 * Sets the monto prospectado of this solicitud producto.
	 *
	 * @param montoProspectado the monto prospectado of this solicitud producto
	 */
	public void setMontoProspectado(Double montoProspectado);

	/**
	 * Returns the codigo campania of this solicitud producto.
	 *
	 * @return the codigo campania of this solicitud producto
	 */
	@AutoEscape
	public String getCodigoCampania();

	/**
	 * Sets the codigo campania of this solicitud producto.
	 *
	 * @param codigoCampania the codigo campania of this solicitud producto
	 */
	public void setCodigoCampania(String codigoCampania);

	/**
	 * Returns the codigo moneda of this solicitud producto.
	 *
	 * @return the codigo moneda of this solicitud producto
	 */
	@AutoEscape
	public String getCodigoMoneda();

	/**
	 * Sets the codigo moneda of this solicitud producto.
	 *
	 * @param codigoMoneda the codigo moneda of this solicitud producto
	 */
	public void setCodigoMoneda(String codigoMoneda);

	/**
	 * Returns the nombre supervisor of this solicitud producto.
	 *
	 * @return the nombre supervisor of this solicitud producto
	 */
	@AutoEscape
	public String getNombreSupervisor();

	/**
	 * Sets the nombre supervisor of this solicitud producto.
	 *
	 * @param nombreSupervisor the nombre supervisor of this solicitud producto
	 */
	public void setNombreSupervisor(String nombreSupervisor);

	/**
	 * Returns the resp reg lead of this solicitud producto.
	 *
	 * @return the resp reg lead of this solicitud producto
	 */
	@AutoEscape
	public String getRespRegLead();

	/**
	 * Sets the resp reg lead of this solicitud producto.
	 *
	 * @param respRegLead the resp reg lead of this solicitud producto
	 */
	public void setRespRegLead(String respRegLead);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SolicitudProducto solicitudProducto);

	public int hashCode();

	public CacheModel<SolicitudProducto> toCacheModel();

	public SolicitudProducto toEscapedModel();

	public String toString();

	public String toXmlString();
}