/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ValorCuota service. Represents a row in the &quot;T_VALOR_CUOTA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.halcon.model.impl.ValorCuotaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.halcon.model.impl.ValorCuotaImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see ValorCuota
 * @see com.ext.portlet.halcon.model.impl.ValorCuotaImpl
 * @see com.ext.portlet.halcon.model.impl.ValorCuotaModelImpl
 * @generated
 */
public interface ValorCuotaModel extends BaseModel<ValorCuota> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a valor cuota model instance should use the {@link ValorCuota} interface instead.
	 */

	/**
	 * Returns the primary key of this valor cuota.
	 *
	 * @return the primary key of this valor cuota
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this valor cuota.
	 *
	 * @param primaryKey the primary key of this valor cuota
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id valor cuota of this valor cuota.
	 *
	 * @return the id valor cuota of this valor cuota
	 */
	public long getIdValorCuota();

	/**
	 * Sets the id valor cuota of this valor cuota.
	 *
	 * @param IdValorCuota the id valor cuota of this valor cuota
	 */
	public void setIdValorCuota(long IdValorCuota);

	/**
	 * Returns the tipo fondo mutuo of this valor cuota.
	 *
	 * @return the tipo fondo mutuo of this valor cuota
	 */
	public Integer getTipoFondoMutuo();

	/**
	 * Sets the tipo fondo mutuo of this valor cuota.
	 *
	 * @param tipoFondoMutuo the tipo fondo mutuo of this valor cuota
	 */
	public void setTipoFondoMutuo(Integer tipoFondoMutuo);

	/**
	 * Returns the fecha of this valor cuota.
	 *
	 * @return the fecha of this valor cuota
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this valor cuota.
	 *
	 * @param fecha the fecha of this valor cuota
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the valor cuota of this valor cuota.
	 *
	 * @return the valor cuota of this valor cuota
	 */
	public Double getValorCuota();

	/**
	 * Sets the valor cuota of this valor cuota.
	 *
	 * @param valorCuota the valor cuota of this valor cuota
	 */
	public void setValorCuota(Double valorCuota);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ValorCuota valorCuota);

	public int hashCode();

	public CacheModel<ValorCuota> toCacheModel();

	public ValorCuota toEscapedModel();

	public String toString();

	public String toXmlString();
}