/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.CargaTienda;
import com.ext.portlet.halcon.model.CargaTiendaModel;
import com.ext.portlet.halcon.model.CargaTiendaSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CargaTienda service. Represents a row in the &quot;T_CARGA_TIENDA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.CargaTiendaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CargaTiendaImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see CargaTiendaImpl
 * @see com.ext.portlet.halcon.model.CargaTienda
 * @see com.ext.portlet.halcon.model.CargaTiendaModel
 * @generated
 */
@JSON(strict = true)
public class CargaTiendaModelImpl extends BaseModelImpl<CargaTienda>
	implements CargaTiendaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a carga tienda model instance should use the {@link com.ext.portlet.halcon.model.CargaTienda} interface instead.
	 */
	public static final String TABLE_NAME = "T_CARGA_TIENDA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cati_IdCargaTienda", Types.BIGINT },
			{ "cati_IdPtoServicio", Types.VARCHAR },
			{ "cati_IdCanal", Types.VARCHAR },
			{ "cati_IdSubCanal", Types.VARCHAR },
			{ "cati_IdDepartamento", Types.VARCHAR },
			{ "cati_IdProvincia", Types.VARCHAR },
			{ "cati_IdDistrito", Types.VARCHAR },
			{ "cati_Departamento", Types.VARCHAR },
			{ "cati_Provincia", Types.VARCHAR },
			{ "cati_Distrito", Types.VARCHAR },
			{ "cati_Latitud", Types.VARCHAR },
			{ "cati_Longitud", Types.VARCHAR },
			{ "cati_Direccion", Types.VARCHAR },
			{ "cati_Horario", Types.VARCHAR },
			{ "cati_TipoLocacion", Types.VARCHAR },
			{ "cati_CodTienda", Types.INTEGER },
			{ "cati_IdLocacion", Types.INTEGER },
			{ "cati_Locacion", Types.VARCHAR },
			{ "cati_EmailCom", Types.VARCHAR },
			{ "cati_Telefono", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_CARGA_TIENDA (cati_IdCargaTienda LONG not null primary key IDENTITY,cati_IdPtoServicio VARCHAR(75) null,cati_IdCanal VARCHAR(75) null,cati_IdSubCanal VARCHAR(75) null,cati_IdDepartamento VARCHAR(75) null,cati_IdProvincia VARCHAR(75) null,cati_IdDistrito VARCHAR(75) null,cati_Departamento VARCHAR(75) null,cati_Provincia VARCHAR(75) null,cati_Distrito VARCHAR(75) null,cati_Latitud VARCHAR(75) null,cati_Longitud VARCHAR(75) null,cati_Direccion VARCHAR(75) null,cati_Horario VARCHAR(75) null,cati_TipoLocacion VARCHAR(75) null,cati_CodTienda INTEGER,cati_IdLocacion INTEGER,cati_Locacion VARCHAR(75) null,cati_EmailCom VARCHAR(75) null,cati_Telefono VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_CARGA_TIENDA";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.CargaTienda"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.CargaTienda"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CargaTienda toModel(CargaTiendaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CargaTienda model = new CargaTiendaImpl();

		model.setIdCargaTienda(soapModel.getIdCargaTienda());
		model.setIdPtoServicio(soapModel.getIdPtoServicio());
		model.setIdCanal(soapModel.getIdCanal());
		model.setIdSubCanal(soapModel.getIdSubCanal());
		model.setCodDepartamento(soapModel.getCodDepartamento());
		model.setCodProvincia(soapModel.getCodProvincia());
		model.setCodDistrito(soapModel.getCodDistrito());
		model.setNomDepartamento(soapModel.getNomDepartamento());
		model.setNomProvincia(soapModel.getNomProvincia());
		model.setNomDistrito(soapModel.getNomDistrito());
		model.setLatitud(soapModel.getLatitud());
		model.setLongitud(soapModel.getLongitud());
		model.setDireccion(soapModel.getDireccion());
		model.setHorario(soapModel.getHorario());
		model.setTipoLocacion(soapModel.getTipoLocacion());
		model.setCodTienda(soapModel.getCodTienda());
		model.setIdLocacion(soapModel.getIdLocacion());
		model.setLocacion(soapModel.getLocacion());
		model.setEmailCom(soapModel.getEmailCom());
		model.setTelefono(soapModel.getTelefono());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CargaTienda> toModels(CargaTiendaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CargaTienda> models = new ArrayList<CargaTienda>(soapModels.length);

		for (CargaTiendaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.CargaTienda"));

	public CargaTiendaModelImpl() {
	}

	public long getPrimaryKey() {
		return _idCargaTienda;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdCargaTienda(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idCargaTienda);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CargaTienda.class;
	}

	public String getModelClassName() {
		return CargaTienda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idCargaTienda", getIdCargaTienda());
		attributes.put("idPtoServicio", getIdPtoServicio());
		attributes.put("idCanal", getIdCanal());
		attributes.put("idSubCanal", getIdSubCanal());
		attributes.put("codDepartamento", getCodDepartamento());
		attributes.put("codProvincia", getCodProvincia());
		attributes.put("codDistrito", getCodDistrito());
		attributes.put("nomDepartamento", getNomDepartamento());
		attributes.put("nomProvincia", getNomProvincia());
		attributes.put("nomDistrito", getNomDistrito());
		attributes.put("latitud", getLatitud());
		attributes.put("longitud", getLongitud());
		attributes.put("direccion", getDireccion());
		attributes.put("horario", getHorario());
		attributes.put("tipoLocacion", getTipoLocacion());
		attributes.put("codTienda", getCodTienda());
		attributes.put("idLocacion", getIdLocacion());
		attributes.put("locacion", getLocacion());
		attributes.put("emailCom", getEmailCom());
		attributes.put("telefono", getTelefono());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idCargaTienda = (Long)attributes.get("idCargaTienda");

		if (idCargaTienda != null) {
			setIdCargaTienda(idCargaTienda);
		}

		String idPtoServicio = (String)attributes.get("idPtoServicio");

		if (idPtoServicio != null) {
			setIdPtoServicio(idPtoServicio);
		}

		String idCanal = (String)attributes.get("idCanal");

		if (idCanal != null) {
			setIdCanal(idCanal);
		}

		String idSubCanal = (String)attributes.get("idSubCanal");

		if (idSubCanal != null) {
			setIdSubCanal(idSubCanal);
		}

		String codDepartamento = (String)attributes.get("codDepartamento");

		if (codDepartamento != null) {
			setCodDepartamento(codDepartamento);
		}

		String codProvincia = (String)attributes.get("codProvincia");

		if (codProvincia != null) {
			setCodProvincia(codProvincia);
		}

		String codDistrito = (String)attributes.get("codDistrito");

		if (codDistrito != null) {
			setCodDistrito(codDistrito);
		}

		String nomDepartamento = (String)attributes.get("nomDepartamento");

		if (nomDepartamento != null) {
			setNomDepartamento(nomDepartamento);
		}

		String nomProvincia = (String)attributes.get("nomProvincia");

		if (nomProvincia != null) {
			setNomProvincia(nomProvincia);
		}

		String nomDistrito = (String)attributes.get("nomDistrito");

		if (nomDistrito != null) {
			setNomDistrito(nomDistrito);
		}

		String latitud = (String)attributes.get("latitud");

		if (latitud != null) {
			setLatitud(latitud);
		}

		String longitud = (String)attributes.get("longitud");

		if (longitud != null) {
			setLongitud(longitud);
		}

		String direccion = (String)attributes.get("direccion");

		if (direccion != null) {
			setDireccion(direccion);
		}

		String horario = (String)attributes.get("horario");

		if (horario != null) {
			setHorario(horario);
		}

		String tipoLocacion = (String)attributes.get("tipoLocacion");

		if (tipoLocacion != null) {
			setTipoLocacion(tipoLocacion);
		}

		Integer codTienda = (Integer)attributes.get("codTienda");

		if (codTienda != null) {
			setCodTienda(codTienda);
		}

		Integer idLocacion = (Integer)attributes.get("idLocacion");

		if (idLocacion != null) {
			setIdLocacion(idLocacion);
		}

		String locacion = (String)attributes.get("locacion");

		if (locacion != null) {
			setLocacion(locacion);
		}

		String emailCom = (String)attributes.get("emailCom");

		if (emailCom != null) {
			setEmailCom(emailCom);
		}

		String telefono = (String)attributes.get("telefono");

		if (telefono != null) {
			setTelefono(telefono);
		}
	}

	@JSON
	public long getIdCargaTienda() {
		return _idCargaTienda;
	}

	public void setIdCargaTienda(long idCargaTienda) {
		_idCargaTienda = idCargaTienda;
	}

	@JSON
	public String getIdPtoServicio() {
		if (_idPtoServicio == null) {
			return StringPool.BLANK;
		}
		else {
			return _idPtoServicio;
		}
	}

	public void setIdPtoServicio(String idPtoServicio) {
		_idPtoServicio = idPtoServicio;
	}

	@JSON
	public String getIdCanal() {
		if (_idCanal == null) {
			return StringPool.BLANK;
		}
		else {
			return _idCanal;
		}
	}

	public void setIdCanal(String idCanal) {
		_idCanal = idCanal;
	}

	@JSON
	public String getIdSubCanal() {
		if (_idSubCanal == null) {
			return StringPool.BLANK;
		}
		else {
			return _idSubCanal;
		}
	}

	public void setIdSubCanal(String idSubCanal) {
		_idSubCanal = idSubCanal;
	}

	@JSON
	public String getCodDepartamento() {
		if (_codDepartamento == null) {
			return StringPool.BLANK;
		}
		else {
			return _codDepartamento;
		}
	}

	public void setCodDepartamento(String codDepartamento) {
		_codDepartamento = codDepartamento;
	}

	@JSON
	public String getCodProvincia() {
		if (_codProvincia == null) {
			return StringPool.BLANK;
		}
		else {
			return _codProvincia;
		}
	}

	public void setCodProvincia(String codProvincia) {
		_codProvincia = codProvincia;
	}

	@JSON
	public String getCodDistrito() {
		if (_codDistrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _codDistrito;
		}
	}

	public void setCodDistrito(String codDistrito) {
		_codDistrito = codDistrito;
	}

	@JSON
	public String getNomDepartamento() {
		if (_nomDepartamento == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomDepartamento;
		}
	}

	public void setNomDepartamento(String nomDepartamento) {
		_nomDepartamento = nomDepartamento;
	}

	@JSON
	public String getNomProvincia() {
		if (_nomProvincia == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomProvincia;
		}
	}

	public void setNomProvincia(String nomProvincia) {
		_nomProvincia = nomProvincia;
	}

	@JSON
	public String getNomDistrito() {
		if (_nomDistrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomDistrito;
		}
	}

	public void setNomDistrito(String nomDistrito) {
		_nomDistrito = nomDistrito;
	}

	@JSON
	public String getLatitud() {
		if (_latitud == null) {
			return StringPool.BLANK;
		}
		else {
			return _latitud;
		}
	}

	public void setLatitud(String latitud) {
		_latitud = latitud;
	}

	@JSON
	public String getLongitud() {
		if (_longitud == null) {
			return StringPool.BLANK;
		}
		else {
			return _longitud;
		}
	}

	public void setLongitud(String longitud) {
		_longitud = longitud;
	}

	@JSON
	public String getDireccion() {
		if (_direccion == null) {
			return StringPool.BLANK;
		}
		else {
			return _direccion;
		}
	}

	public void setDireccion(String direccion) {
		_direccion = direccion;
	}

	@JSON
	public String getHorario() {
		if (_horario == null) {
			return StringPool.BLANK;
		}
		else {
			return _horario;
		}
	}

	public void setHorario(String horario) {
		_horario = horario;
	}

	@JSON
	public String getTipoLocacion() {
		if (_tipoLocacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoLocacion;
		}
	}

	public void setTipoLocacion(String tipoLocacion) {
		_tipoLocacion = tipoLocacion;
	}

	@JSON
	public Integer getCodTienda() {
		return _codTienda;
	}

	public void setCodTienda(Integer codTienda) {
		_codTienda = codTienda;
	}

	@JSON
	public Integer getIdLocacion() {
		return _idLocacion;
	}

	public void setIdLocacion(Integer idLocacion) {
		_idLocacion = idLocacion;
	}

	@JSON
	public String getLocacion() {
		if (_locacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _locacion;
		}
	}

	public void setLocacion(String locacion) {
		_locacion = locacion;
	}

	@JSON
	public String getEmailCom() {
		if (_emailCom == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailCom;
		}
	}

	public void setEmailCom(String emailCom) {
		_emailCom = emailCom;
	}

	@JSON
	public String getTelefono() {
		if (_telefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefono;
		}
	}

	public void setTelefono(String telefono) {
		_telefono = telefono;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CargaTienda.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CargaTienda toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CargaTienda)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CargaTiendaImpl cargaTiendaImpl = new CargaTiendaImpl();

		cargaTiendaImpl.setIdCargaTienda(getIdCargaTienda());
		cargaTiendaImpl.setIdPtoServicio(getIdPtoServicio());
		cargaTiendaImpl.setIdCanal(getIdCanal());
		cargaTiendaImpl.setIdSubCanal(getIdSubCanal());
		cargaTiendaImpl.setCodDepartamento(getCodDepartamento());
		cargaTiendaImpl.setCodProvincia(getCodProvincia());
		cargaTiendaImpl.setCodDistrito(getCodDistrito());
		cargaTiendaImpl.setNomDepartamento(getNomDepartamento());
		cargaTiendaImpl.setNomProvincia(getNomProvincia());
		cargaTiendaImpl.setNomDistrito(getNomDistrito());
		cargaTiendaImpl.setLatitud(getLatitud());
		cargaTiendaImpl.setLongitud(getLongitud());
		cargaTiendaImpl.setDireccion(getDireccion());
		cargaTiendaImpl.setHorario(getHorario());
		cargaTiendaImpl.setTipoLocacion(getTipoLocacion());
		cargaTiendaImpl.setCodTienda(getCodTienda());
		cargaTiendaImpl.setIdLocacion(getIdLocacion());
		cargaTiendaImpl.setLocacion(getLocacion());
		cargaTiendaImpl.setEmailCom(getEmailCom());
		cargaTiendaImpl.setTelefono(getTelefono());

		cargaTiendaImpl.resetOriginalValues();

		return cargaTiendaImpl;
	}

	public int compareTo(CargaTienda cargaTienda) {
		long primaryKey = cargaTienda.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CargaTienda cargaTienda = null;

		try {
			cargaTienda = (CargaTienda)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = cargaTienda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CargaTienda> toCacheModel() {
		CargaTiendaCacheModel cargaTiendaCacheModel = new CargaTiendaCacheModel();

		cargaTiendaCacheModel.idCargaTienda = getIdCargaTienda();

		cargaTiendaCacheModel.idPtoServicio = getIdPtoServicio();

		String idPtoServicio = cargaTiendaCacheModel.idPtoServicio;

		if ((idPtoServicio != null) && (idPtoServicio.length() == 0)) {
			cargaTiendaCacheModel.idPtoServicio = null;
		}

		cargaTiendaCacheModel.idCanal = getIdCanal();

		String idCanal = cargaTiendaCacheModel.idCanal;

		if ((idCanal != null) && (idCanal.length() == 0)) {
			cargaTiendaCacheModel.idCanal = null;
		}

		cargaTiendaCacheModel.idSubCanal = getIdSubCanal();

		String idSubCanal = cargaTiendaCacheModel.idSubCanal;

		if ((idSubCanal != null) && (idSubCanal.length() == 0)) {
			cargaTiendaCacheModel.idSubCanal = null;
		}

		cargaTiendaCacheModel.codDepartamento = getCodDepartamento();

		String codDepartamento = cargaTiendaCacheModel.codDepartamento;

		if ((codDepartamento != null) && (codDepartamento.length() == 0)) {
			cargaTiendaCacheModel.codDepartamento = null;
		}

		cargaTiendaCacheModel.codProvincia = getCodProvincia();

		String codProvincia = cargaTiendaCacheModel.codProvincia;

		if ((codProvincia != null) && (codProvincia.length() == 0)) {
			cargaTiendaCacheModel.codProvincia = null;
		}

		cargaTiendaCacheModel.codDistrito = getCodDistrito();

		String codDistrito = cargaTiendaCacheModel.codDistrito;

		if ((codDistrito != null) && (codDistrito.length() == 0)) {
			cargaTiendaCacheModel.codDistrito = null;
		}

		cargaTiendaCacheModel.nomDepartamento = getNomDepartamento();

		String nomDepartamento = cargaTiendaCacheModel.nomDepartamento;

		if ((nomDepartamento != null) && (nomDepartamento.length() == 0)) {
			cargaTiendaCacheModel.nomDepartamento = null;
		}

		cargaTiendaCacheModel.nomProvincia = getNomProvincia();

		String nomProvincia = cargaTiendaCacheModel.nomProvincia;

		if ((nomProvincia != null) && (nomProvincia.length() == 0)) {
			cargaTiendaCacheModel.nomProvincia = null;
		}

		cargaTiendaCacheModel.nomDistrito = getNomDistrito();

		String nomDistrito = cargaTiendaCacheModel.nomDistrito;

		if ((nomDistrito != null) && (nomDistrito.length() == 0)) {
			cargaTiendaCacheModel.nomDistrito = null;
		}

		cargaTiendaCacheModel.latitud = getLatitud();

		String latitud = cargaTiendaCacheModel.latitud;

		if ((latitud != null) && (latitud.length() == 0)) {
			cargaTiendaCacheModel.latitud = null;
		}

		cargaTiendaCacheModel.longitud = getLongitud();

		String longitud = cargaTiendaCacheModel.longitud;

		if ((longitud != null) && (longitud.length() == 0)) {
			cargaTiendaCacheModel.longitud = null;
		}

		cargaTiendaCacheModel.direccion = getDireccion();

		String direccion = cargaTiendaCacheModel.direccion;

		if ((direccion != null) && (direccion.length() == 0)) {
			cargaTiendaCacheModel.direccion = null;
		}

		cargaTiendaCacheModel.horario = getHorario();

		String horario = cargaTiendaCacheModel.horario;

		if ((horario != null) && (horario.length() == 0)) {
			cargaTiendaCacheModel.horario = null;
		}

		cargaTiendaCacheModel.tipoLocacion = getTipoLocacion();

		String tipoLocacion = cargaTiendaCacheModel.tipoLocacion;

		if ((tipoLocacion != null) && (tipoLocacion.length() == 0)) {
			cargaTiendaCacheModel.tipoLocacion = null;
		}

		cargaTiendaCacheModel.codTienda = getCodTienda();

		cargaTiendaCacheModel.idLocacion = getIdLocacion();

		cargaTiendaCacheModel.locacion = getLocacion();

		String locacion = cargaTiendaCacheModel.locacion;

		if ((locacion != null) && (locacion.length() == 0)) {
			cargaTiendaCacheModel.locacion = null;
		}

		cargaTiendaCacheModel.emailCom = getEmailCom();

		String emailCom = cargaTiendaCacheModel.emailCom;

		if ((emailCom != null) && (emailCom.length() == 0)) {
			cargaTiendaCacheModel.emailCom = null;
		}

		cargaTiendaCacheModel.telefono = getTelefono();

		String telefono = cargaTiendaCacheModel.telefono;

		if ((telefono != null) && (telefono.length() == 0)) {
			cargaTiendaCacheModel.telefono = null;
		}

		return cargaTiendaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{idCargaTienda=");
		sb.append(getIdCargaTienda());
		sb.append(", idPtoServicio=");
		sb.append(getIdPtoServicio());
		sb.append(", idCanal=");
		sb.append(getIdCanal());
		sb.append(", idSubCanal=");
		sb.append(getIdSubCanal());
		sb.append(", codDepartamento=");
		sb.append(getCodDepartamento());
		sb.append(", codProvincia=");
		sb.append(getCodProvincia());
		sb.append(", codDistrito=");
		sb.append(getCodDistrito());
		sb.append(", nomDepartamento=");
		sb.append(getNomDepartamento());
		sb.append(", nomProvincia=");
		sb.append(getNomProvincia());
		sb.append(", nomDistrito=");
		sb.append(getNomDistrito());
		sb.append(", latitud=");
		sb.append(getLatitud());
		sb.append(", longitud=");
		sb.append(getLongitud());
		sb.append(", direccion=");
		sb.append(getDireccion());
		sb.append(", horario=");
		sb.append(getHorario());
		sb.append(", tipoLocacion=");
		sb.append(getTipoLocacion());
		sb.append(", codTienda=");
		sb.append(getCodTienda());
		sb.append(", idLocacion=");
		sb.append(getIdLocacion());
		sb.append(", locacion=");
		sb.append(getLocacion());
		sb.append(", emailCom=");
		sb.append(getEmailCom());
		sb.append(", telefono=");
		sb.append(getTelefono());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.CargaTienda");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idCargaTienda</column-name><column-value><![CDATA[");
		sb.append(getIdCargaTienda());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idPtoServicio</column-name><column-value><![CDATA[");
		sb.append(getIdPtoServicio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idCanal</column-name><column-value><![CDATA[");
		sb.append(getIdCanal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idSubCanal</column-name><column-value><![CDATA[");
		sb.append(getIdSubCanal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codDepartamento</column-name><column-value><![CDATA[");
		sb.append(getCodDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codProvincia</column-name><column-value><![CDATA[");
		sb.append(getCodProvincia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codDistrito</column-name><column-value><![CDATA[");
		sb.append(getCodDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomDepartamento</column-name><column-value><![CDATA[");
		sb.append(getNomDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomProvincia</column-name><column-value><![CDATA[");
		sb.append(getNomProvincia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomDistrito</column-name><column-value><![CDATA[");
		sb.append(getNomDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>latitud</column-name><column-value><![CDATA[");
		sb.append(getLatitud());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>longitud</column-name><column-value><![CDATA[");
		sb.append(getLongitud());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direccion</column-name><column-value><![CDATA[");
		sb.append(getDireccion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>horario</column-name><column-value><![CDATA[");
		sb.append(getHorario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoLocacion</column-name><column-value><![CDATA[");
		sb.append(getTipoLocacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codTienda</column-name><column-value><![CDATA[");
		sb.append(getCodTienda());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idLocacion</column-name><column-value><![CDATA[");
		sb.append(getIdLocacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locacion</column-name><column-value><![CDATA[");
		sb.append(getLocacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailCom</column-name><column-value><![CDATA[");
		sb.append(getEmailCom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefono</column-name><column-value><![CDATA[");
		sb.append(getTelefono());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CargaTienda.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CargaTienda.class
		};
	private long _idCargaTienda;
	private String _idPtoServicio;
	private String _idCanal;
	private String _idSubCanal;
	private String _codDepartamento;
	private String _codProvincia;
	private String _codDistrito;
	private String _nomDepartamento;
	private String _nomProvincia;
	private String _nomDistrito;
	private String _latitud;
	private String _longitud;
	private String _direccion;
	private String _horario;
	private String _tipoLocacion;
	private Integer _codTienda;
	private Integer _idLocacion;
	private String _locacion;
	private String _emailCom;
	private String _telefono;
	private CargaTienda _escapedModelProxy;
}