/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.CargaSocioRemesa;
import com.ext.portlet.halcon.model.CargaSocioRemesaModel;
import com.ext.portlet.halcon.model.CargaSocioRemesaSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CargaSocioRemesa service. Represents a row in the &quot;T_CARGA_SOCIO_REMESA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.CargaSocioRemesaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CargaSocioRemesaImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see CargaSocioRemesaImpl
 * @see com.ext.portlet.halcon.model.CargaSocioRemesa
 * @see com.ext.portlet.halcon.model.CargaSocioRemesaModel
 * @generated
 */
@JSON(strict = true)
public class CargaSocioRemesaModelImpl extends BaseModelImpl<CargaSocioRemesa>
	implements CargaSocioRemesaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a carga socio remesa model instance should use the {@link com.ext.portlet.halcon.model.CargaSocioRemesa} interface instead.
	 */
	public static final String TABLE_NAME = "T_CARGA_SOCIO_REMESA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "casr_IdSocioRemesa", Types.BIGINT },
			{ "casr_Empresa", Types.VARCHAR },
			{ "casr_PaisCobertura", Types.VARCHAR },
			{ "casr_PaginaWeb", Types.VARCHAR },
			{ "casr_Telefono", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_CARGA_SOCIO_REMESA (casr_IdSocioRemesa LONG not null primary key IDENTITY,casr_Empresa VARCHAR(75) null,casr_PaisCobertura VARCHAR(75) null,casr_PaginaWeb VARCHAR(75) null,casr_Telefono VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_CARGA_SOCIO_REMESA";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.CargaSocioRemesa"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.CargaSocioRemesa"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CargaSocioRemesa toModel(CargaSocioRemesaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CargaSocioRemesa model = new CargaSocioRemesaImpl();

		model.setIdSocioRemesa(soapModel.getIdSocioRemesa());
		model.setEmpresa(soapModel.getEmpresa());
		model.setPaisCobertura(soapModel.getPaisCobertura());
		model.setPaginaWeb(soapModel.getPaginaWeb());
		model.setTelefono(soapModel.getTelefono());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CargaSocioRemesa> toModels(
		CargaSocioRemesaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CargaSocioRemesa> models = new ArrayList<CargaSocioRemesa>(soapModels.length);

		for (CargaSocioRemesaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.CargaSocioRemesa"));

	public CargaSocioRemesaModelImpl() {
	}

	public long getPrimaryKey() {
		return _idSocioRemesa;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdSocioRemesa(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idSocioRemesa);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CargaSocioRemesa.class;
	}

	public String getModelClassName() {
		return CargaSocioRemesa.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idSocioRemesa", getIdSocioRemesa());
		attributes.put("empresa", getEmpresa());
		attributes.put("paisCobertura", getPaisCobertura());
		attributes.put("paginaWeb", getPaginaWeb());
		attributes.put("telefono", getTelefono());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idSocioRemesa = (Long)attributes.get("idSocioRemesa");

		if (idSocioRemesa != null) {
			setIdSocioRemesa(idSocioRemesa);
		}

		String empresa = (String)attributes.get("empresa");

		if (empresa != null) {
			setEmpresa(empresa);
		}

		String paisCobertura = (String)attributes.get("paisCobertura");

		if (paisCobertura != null) {
			setPaisCobertura(paisCobertura);
		}

		String paginaWeb = (String)attributes.get("paginaWeb");

		if (paginaWeb != null) {
			setPaginaWeb(paginaWeb);
		}

		String telefono = (String)attributes.get("telefono");

		if (telefono != null) {
			setTelefono(telefono);
		}
	}

	@JSON
	public long getIdSocioRemesa() {
		return _idSocioRemesa;
	}

	public void setIdSocioRemesa(long idSocioRemesa) {
		_idSocioRemesa = idSocioRemesa;
	}

	@JSON
	public String getEmpresa() {
		if (_empresa == null) {
			return StringPool.BLANK;
		}
		else {
			return _empresa;
		}
	}

	public void setEmpresa(String empresa) {
		_empresa = empresa;
	}

	@JSON
	public String getPaisCobertura() {
		if (_paisCobertura == null) {
			return StringPool.BLANK;
		}
		else {
			return _paisCobertura;
		}
	}

	public void setPaisCobertura(String paisCobertura) {
		_paisCobertura = paisCobertura;
	}

	@JSON
	public String getPaginaWeb() {
		if (_paginaWeb == null) {
			return StringPool.BLANK;
		}
		else {
			return _paginaWeb;
		}
	}

	public void setPaginaWeb(String paginaWeb) {
		_paginaWeb = paginaWeb;
	}

	@JSON
	public String getTelefono() {
		if (_telefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefono;
		}
	}

	public void setTelefono(String telefono) {
		_telefono = telefono;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CargaSocioRemesa.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CargaSocioRemesa toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CargaSocioRemesa)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CargaSocioRemesaImpl cargaSocioRemesaImpl = new CargaSocioRemesaImpl();

		cargaSocioRemesaImpl.setIdSocioRemesa(getIdSocioRemesa());
		cargaSocioRemesaImpl.setEmpresa(getEmpresa());
		cargaSocioRemesaImpl.setPaisCobertura(getPaisCobertura());
		cargaSocioRemesaImpl.setPaginaWeb(getPaginaWeb());
		cargaSocioRemesaImpl.setTelefono(getTelefono());

		cargaSocioRemesaImpl.resetOriginalValues();

		return cargaSocioRemesaImpl;
	}

	public int compareTo(CargaSocioRemesa cargaSocioRemesa) {
		long primaryKey = cargaSocioRemesa.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CargaSocioRemesa cargaSocioRemesa = null;

		try {
			cargaSocioRemesa = (CargaSocioRemesa)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = cargaSocioRemesa.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CargaSocioRemesa> toCacheModel() {
		CargaSocioRemesaCacheModel cargaSocioRemesaCacheModel = new CargaSocioRemesaCacheModel();

		cargaSocioRemesaCacheModel.idSocioRemesa = getIdSocioRemesa();

		cargaSocioRemesaCacheModel.empresa = getEmpresa();

		String empresa = cargaSocioRemesaCacheModel.empresa;

		if ((empresa != null) && (empresa.length() == 0)) {
			cargaSocioRemesaCacheModel.empresa = null;
		}

		cargaSocioRemesaCacheModel.paisCobertura = getPaisCobertura();

		String paisCobertura = cargaSocioRemesaCacheModel.paisCobertura;

		if ((paisCobertura != null) && (paisCobertura.length() == 0)) {
			cargaSocioRemesaCacheModel.paisCobertura = null;
		}

		cargaSocioRemesaCacheModel.paginaWeb = getPaginaWeb();

		String paginaWeb = cargaSocioRemesaCacheModel.paginaWeb;

		if ((paginaWeb != null) && (paginaWeb.length() == 0)) {
			cargaSocioRemesaCacheModel.paginaWeb = null;
		}

		cargaSocioRemesaCacheModel.telefono = getTelefono();

		String telefono = cargaSocioRemesaCacheModel.telefono;

		if ((telefono != null) && (telefono.length() == 0)) {
			cargaSocioRemesaCacheModel.telefono = null;
		}

		return cargaSocioRemesaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{idSocioRemesa=");
		sb.append(getIdSocioRemesa());
		sb.append(", empresa=");
		sb.append(getEmpresa());
		sb.append(", paisCobertura=");
		sb.append(getPaisCobertura());
		sb.append(", paginaWeb=");
		sb.append(getPaginaWeb());
		sb.append(", telefono=");
		sb.append(getTelefono());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.CargaSocioRemesa");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idSocioRemesa</column-name><column-value><![CDATA[");
		sb.append(getIdSocioRemesa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empresa</column-name><column-value><![CDATA[");
		sb.append(getEmpresa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paisCobertura</column-name><column-value><![CDATA[");
		sb.append(getPaisCobertura());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paginaWeb</column-name><column-value><![CDATA[");
		sb.append(getPaginaWeb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefono</column-name><column-value><![CDATA[");
		sb.append(getTelefono());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CargaSocioRemesa.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CargaSocioRemesa.class
		};
	private long _idSocioRemesa;
	private String _empresa;
	private String _paisCobertura;
	private String _paginaWeb;
	private String _telefono;
	private CargaSocioRemesa _escapedModelProxy;
}