/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.CargaDescuento;
import com.ext.portlet.halcon.model.CargaDescuentoModel;
import com.ext.portlet.halcon.model.CargaDescuentoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CargaDescuento service. Represents a row in the &quot;T_CARGA_DESCUENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.CargaDescuentoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CargaDescuentoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see CargaDescuentoImpl
 * @see com.ext.portlet.halcon.model.CargaDescuento
 * @see com.ext.portlet.halcon.model.CargaDescuentoModel
 * @generated
 */
@JSON(strict = true)
public class CargaDescuentoModelImpl extends BaseModelImpl<CargaDescuento>
	implements CargaDescuentoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a carga descuento model instance should use the {@link com.ext.portlet.halcon.model.CargaDescuento} interface instead.
	 */
	public static final String TABLE_NAME = "T_CARGA_DESCUENTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cade_IdCargaDesc", Types.BIGINT },
			{ "cade_Local", Types.VARCHAR },
			{ "cade_DescuentoGeneral", Types.VARCHAR },
			{ "cade_CondicionesRestricciones", Types.VARCHAR },
			{ "cade_Direccion", Types.VARCHAR },
			{ "cade_IdDistrito", Types.VARCHAR },
			{ "cade_Distrito", Types.VARCHAR },
			{ "cade_Telefono", Types.VARCHAR },
			{ "cade_Web", Types.VARCHAR },
			{ "cade_FinVigencia", Types.TIMESTAMP },
			{ "cade_Categoria", Types.VARCHAR },
			{ "cade_Coordenada", Types.VARCHAR },
			{ "cade_URLImagen", Types.VARCHAR },
			{ "cade_Latitud", Types.VARCHAR },
			{ "cade_Longitud", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_CARGA_DESCUENTO (cade_IdCargaDesc LONG not null primary key IDENTITY,cade_Local VARCHAR(75) null,cade_DescuentoGeneral VARCHAR(75) null,cade_CondicionesRestricciones VARCHAR(75) null,cade_Direccion VARCHAR(75) null,cade_IdDistrito VARCHAR(75) null,cade_Distrito VARCHAR(75) null,cade_Telefono VARCHAR(75) null,cade_Web VARCHAR(75) null,cade_FinVigencia DATE null,cade_Categoria VARCHAR(75) null,cade_Coordenada VARCHAR(75) null,cade_URLImagen VARCHAR(75) null,cade_Latitud VARCHAR(75) null,cade_Longitud VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_CARGA_DESCUENTO";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.CargaDescuento"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.CargaDescuento"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CargaDescuento toModel(CargaDescuentoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CargaDescuento model = new CargaDescuentoImpl();

		model.setIdCargaDesc(soapModel.getIdCargaDesc());
		model.setLocal(soapModel.getLocal());
		model.setDescuentoGeneral(soapModel.getDescuentoGeneral());
		model.setCondicionesRestricciones(soapModel.getCondicionesRestricciones());
		model.setDireccion(soapModel.getDireccion());
		model.setIdDistrito(soapModel.getIdDistrito());
		model.setDistrito(soapModel.getDistrito());
		model.setTelefono(soapModel.getTelefono());
		model.setWeb(soapModel.getWeb());
		model.setFinVigencia(soapModel.getFinVigencia());
		model.setCategoria(soapModel.getCategoria());
		model.setCoordenada(soapModel.getCoordenada());
		model.setURLImagen(soapModel.getURLImagen());
		model.setLatitud(soapModel.getLatitud());
		model.setLongitud(soapModel.getLongitud());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CargaDescuento> toModels(CargaDescuentoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CargaDescuento> models = new ArrayList<CargaDescuento>(soapModels.length);

		for (CargaDescuentoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.CargaDescuento"));

	public CargaDescuentoModelImpl() {
	}

	public long getPrimaryKey() {
		return _idCargaDesc;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdCargaDesc(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idCargaDesc);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CargaDescuento.class;
	}

	public String getModelClassName() {
		return CargaDescuento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idCargaDesc", getIdCargaDesc());
		attributes.put("local", getLocal());
		attributes.put("descuentoGeneral", getDescuentoGeneral());
		attributes.put("condicionesRestricciones", getCondicionesRestricciones());
		attributes.put("direccion", getDireccion());
		attributes.put("idDistrito", getIdDistrito());
		attributes.put("distrito", getDistrito());
		attributes.put("telefono", getTelefono());
		attributes.put("web", getWeb());
		attributes.put("finVigencia", getFinVigencia());
		attributes.put("categoria", getCategoria());
		attributes.put("coordenada", getCoordenada());
		attributes.put("URLImagen", getURLImagen());
		attributes.put("latitud", getLatitud());
		attributes.put("longitud", getLongitud());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idCargaDesc = (Long)attributes.get("idCargaDesc");

		if (idCargaDesc != null) {
			setIdCargaDesc(idCargaDesc);
		}

		String local = (String)attributes.get("local");

		if (local != null) {
			setLocal(local);
		}

		String descuentoGeneral = (String)attributes.get("descuentoGeneral");

		if (descuentoGeneral != null) {
			setDescuentoGeneral(descuentoGeneral);
		}

		String condicionesRestricciones = (String)attributes.get(
				"condicionesRestricciones");

		if (condicionesRestricciones != null) {
			setCondicionesRestricciones(condicionesRestricciones);
		}

		String direccion = (String)attributes.get("direccion");

		if (direccion != null) {
			setDireccion(direccion);
		}

		String idDistrito = (String)attributes.get("idDistrito");

		if (idDistrito != null) {
			setIdDistrito(idDistrito);
		}

		String distrito = (String)attributes.get("distrito");

		if (distrito != null) {
			setDistrito(distrito);
		}

		String telefono = (String)attributes.get("telefono");

		if (telefono != null) {
			setTelefono(telefono);
		}

		String web = (String)attributes.get("web");

		if (web != null) {
			setWeb(web);
		}

		Date finVigencia = (Date)attributes.get("finVigencia");

		if (finVigencia != null) {
			setFinVigencia(finVigencia);
		}

		String categoria = (String)attributes.get("categoria");

		if (categoria != null) {
			setCategoria(categoria);
		}

		String coordenada = (String)attributes.get("coordenada");

		if (coordenada != null) {
			setCoordenada(coordenada);
		}

		String URLImagen = (String)attributes.get("URLImagen");

		if (URLImagen != null) {
			setURLImagen(URLImagen);
		}

		String latitud = (String)attributes.get("latitud");

		if (latitud != null) {
			setLatitud(latitud);
		}

		String longitud = (String)attributes.get("longitud");

		if (longitud != null) {
			setLongitud(longitud);
		}
	}

	@JSON
	public long getIdCargaDesc() {
		return _idCargaDesc;
	}

	public void setIdCargaDesc(long idCargaDesc) {
		_idCargaDesc = idCargaDesc;
	}

	@JSON
	public String getLocal() {
		if (_local == null) {
			return StringPool.BLANK;
		}
		else {
			return _local;
		}
	}

	public void setLocal(String local) {
		_local = local;
	}

	@JSON
	public String getDescuentoGeneral() {
		if (_descuentoGeneral == null) {
			return StringPool.BLANK;
		}
		else {
			return _descuentoGeneral;
		}
	}

	public void setDescuentoGeneral(String descuentoGeneral) {
		_descuentoGeneral = descuentoGeneral;
	}

	@JSON
	public String getCondicionesRestricciones() {
		if (_condicionesRestricciones == null) {
			return StringPool.BLANK;
		}
		else {
			return _condicionesRestricciones;
		}
	}

	public void setCondicionesRestricciones(String condicionesRestricciones) {
		_condicionesRestricciones = condicionesRestricciones;
	}

	@JSON
	public String getDireccion() {
		if (_direccion == null) {
			return StringPool.BLANK;
		}
		else {
			return _direccion;
		}
	}

	public void setDireccion(String direccion) {
		_direccion = direccion;
	}

	@JSON
	public String getIdDistrito() {
		if (_idDistrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _idDistrito;
		}
	}

	public void setIdDistrito(String idDistrito) {
		_idDistrito = idDistrito;
	}

	@JSON
	public String getDistrito() {
		if (_distrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _distrito;
		}
	}

	public void setDistrito(String distrito) {
		_distrito = distrito;
	}

	@JSON
	public String getTelefono() {
		if (_telefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefono;
		}
	}

	public void setTelefono(String telefono) {
		_telefono = telefono;
	}

	@JSON
	public String getWeb() {
		if (_web == null) {
			return StringPool.BLANK;
		}
		else {
			return _web;
		}
	}

	public void setWeb(String web) {
		_web = web;
	}

	@JSON
	public Date getFinVigencia() {
		return _finVigencia;
	}

	public void setFinVigencia(Date finVigencia) {
		_finVigencia = finVigencia;
	}

	@JSON
	public String getCategoria() {
		if (_categoria == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoria;
		}
	}

	public void setCategoria(String categoria) {
		_categoria = categoria;
	}

	@JSON
	public String getCoordenada() {
		if (_coordenada == null) {
			return StringPool.BLANK;
		}
		else {
			return _coordenada;
		}
	}

	public void setCoordenada(String coordenada) {
		_coordenada = coordenada;
	}

	@JSON
	public String getURLImagen() {
		if (_URLImagen == null) {
			return StringPool.BLANK;
		}
		else {
			return _URLImagen;
		}
	}

	public void setURLImagen(String URLImagen) {
		_URLImagen = URLImagen;
	}

	@JSON
	public String getLatitud() {
		if (_latitud == null) {
			return StringPool.BLANK;
		}
		else {
			return _latitud;
		}
	}

	public void setLatitud(String latitud) {
		_latitud = latitud;
	}

	@JSON
	public String getLongitud() {
		if (_longitud == null) {
			return StringPool.BLANK;
		}
		else {
			return _longitud;
		}
	}

	public void setLongitud(String longitud) {
		_longitud = longitud;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CargaDescuento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CargaDescuento toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CargaDescuento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CargaDescuentoImpl cargaDescuentoImpl = new CargaDescuentoImpl();

		cargaDescuentoImpl.setIdCargaDesc(getIdCargaDesc());
		cargaDescuentoImpl.setLocal(getLocal());
		cargaDescuentoImpl.setDescuentoGeneral(getDescuentoGeneral());
		cargaDescuentoImpl.setCondicionesRestricciones(getCondicionesRestricciones());
		cargaDescuentoImpl.setDireccion(getDireccion());
		cargaDescuentoImpl.setIdDistrito(getIdDistrito());
		cargaDescuentoImpl.setDistrito(getDistrito());
		cargaDescuentoImpl.setTelefono(getTelefono());
		cargaDescuentoImpl.setWeb(getWeb());
		cargaDescuentoImpl.setFinVigencia(getFinVigencia());
		cargaDescuentoImpl.setCategoria(getCategoria());
		cargaDescuentoImpl.setCoordenada(getCoordenada());
		cargaDescuentoImpl.setURLImagen(getURLImagen());
		cargaDescuentoImpl.setLatitud(getLatitud());
		cargaDescuentoImpl.setLongitud(getLongitud());

		cargaDescuentoImpl.resetOriginalValues();

		return cargaDescuentoImpl;
	}

	public int compareTo(CargaDescuento cargaDescuento) {
		long primaryKey = cargaDescuento.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CargaDescuento cargaDescuento = null;

		try {
			cargaDescuento = (CargaDescuento)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = cargaDescuento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CargaDescuento> toCacheModel() {
		CargaDescuentoCacheModel cargaDescuentoCacheModel = new CargaDescuentoCacheModel();

		cargaDescuentoCacheModel.idCargaDesc = getIdCargaDesc();

		cargaDescuentoCacheModel.local = getLocal();

		String local = cargaDescuentoCacheModel.local;

		if ((local != null) && (local.length() == 0)) {
			cargaDescuentoCacheModel.local = null;
		}

		cargaDescuentoCacheModel.descuentoGeneral = getDescuentoGeneral();

		String descuentoGeneral = cargaDescuentoCacheModel.descuentoGeneral;

		if ((descuentoGeneral != null) && (descuentoGeneral.length() == 0)) {
			cargaDescuentoCacheModel.descuentoGeneral = null;
		}

		cargaDescuentoCacheModel.condicionesRestricciones = getCondicionesRestricciones();

		String condicionesRestricciones = cargaDescuentoCacheModel.condicionesRestricciones;

		if ((condicionesRestricciones != null) &&
				(condicionesRestricciones.length() == 0)) {
			cargaDescuentoCacheModel.condicionesRestricciones = null;
		}

		cargaDescuentoCacheModel.direccion = getDireccion();

		String direccion = cargaDescuentoCacheModel.direccion;

		if ((direccion != null) && (direccion.length() == 0)) {
			cargaDescuentoCacheModel.direccion = null;
		}

		cargaDescuentoCacheModel.idDistrito = getIdDistrito();

		String idDistrito = cargaDescuentoCacheModel.idDistrito;

		if ((idDistrito != null) && (idDistrito.length() == 0)) {
			cargaDescuentoCacheModel.idDistrito = null;
		}

		cargaDescuentoCacheModel.distrito = getDistrito();

		String distrito = cargaDescuentoCacheModel.distrito;

		if ((distrito != null) && (distrito.length() == 0)) {
			cargaDescuentoCacheModel.distrito = null;
		}

		cargaDescuentoCacheModel.telefono = getTelefono();

		String telefono = cargaDescuentoCacheModel.telefono;

		if ((telefono != null) && (telefono.length() == 0)) {
			cargaDescuentoCacheModel.telefono = null;
		}

		cargaDescuentoCacheModel.web = getWeb();

		String web = cargaDescuentoCacheModel.web;

		if ((web != null) && (web.length() == 0)) {
			cargaDescuentoCacheModel.web = null;
		}

		Date finVigencia = getFinVigencia();

		if (finVigencia != null) {
			cargaDescuentoCacheModel.finVigencia = finVigencia.getTime();
		}
		else {
			cargaDescuentoCacheModel.finVigencia = Long.MIN_VALUE;
		}

		cargaDescuentoCacheModel.categoria = getCategoria();

		String categoria = cargaDescuentoCacheModel.categoria;

		if ((categoria != null) && (categoria.length() == 0)) {
			cargaDescuentoCacheModel.categoria = null;
		}

		cargaDescuentoCacheModel.coordenada = getCoordenada();

		String coordenada = cargaDescuentoCacheModel.coordenada;

		if ((coordenada != null) && (coordenada.length() == 0)) {
			cargaDescuentoCacheModel.coordenada = null;
		}

		cargaDescuentoCacheModel.URLImagen = getURLImagen();

		String URLImagen = cargaDescuentoCacheModel.URLImagen;

		if ((URLImagen != null) && (URLImagen.length() == 0)) {
			cargaDescuentoCacheModel.URLImagen = null;
		}

		cargaDescuentoCacheModel.latitud = getLatitud();

		String latitud = cargaDescuentoCacheModel.latitud;

		if ((latitud != null) && (latitud.length() == 0)) {
			cargaDescuentoCacheModel.latitud = null;
		}

		cargaDescuentoCacheModel.longitud = getLongitud();

		String longitud = cargaDescuentoCacheModel.longitud;

		if ((longitud != null) && (longitud.length() == 0)) {
			cargaDescuentoCacheModel.longitud = null;
		}

		return cargaDescuentoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{idCargaDesc=");
		sb.append(getIdCargaDesc());
		sb.append(", local=");
		sb.append(getLocal());
		sb.append(", descuentoGeneral=");
		sb.append(getDescuentoGeneral());
		sb.append(", condicionesRestricciones=");
		sb.append(getCondicionesRestricciones());
		sb.append(", direccion=");
		sb.append(getDireccion());
		sb.append(", idDistrito=");
		sb.append(getIdDistrito());
		sb.append(", distrito=");
		sb.append(getDistrito());
		sb.append(", telefono=");
		sb.append(getTelefono());
		sb.append(", web=");
		sb.append(getWeb());
		sb.append(", finVigencia=");
		sb.append(getFinVigencia());
		sb.append(", categoria=");
		sb.append(getCategoria());
		sb.append(", coordenada=");
		sb.append(getCoordenada());
		sb.append(", URLImagen=");
		sb.append(getURLImagen());
		sb.append(", latitud=");
		sb.append(getLatitud());
		sb.append(", longitud=");
		sb.append(getLongitud());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.CargaDescuento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idCargaDesc</column-name><column-value><![CDATA[");
		sb.append(getIdCargaDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>local</column-name><column-value><![CDATA[");
		sb.append(getLocal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descuentoGeneral</column-name><column-value><![CDATA[");
		sb.append(getDescuentoGeneral());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>condicionesRestricciones</column-name><column-value><![CDATA[");
		sb.append(getCondicionesRestricciones());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direccion</column-name><column-value><![CDATA[");
		sb.append(getDireccion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDistrito</column-name><column-value><![CDATA[");
		sb.append(getIdDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>distrito</column-name><column-value><![CDATA[");
		sb.append(getDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefono</column-name><column-value><![CDATA[");
		sb.append(getTelefono());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>web</column-name><column-value><![CDATA[");
		sb.append(getWeb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>finVigencia</column-name><column-value><![CDATA[");
		sb.append(getFinVigencia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoria</column-name><column-value><![CDATA[");
		sb.append(getCategoria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coordenada</column-name><column-value><![CDATA[");
		sb.append(getCoordenada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>URLImagen</column-name><column-value><![CDATA[");
		sb.append(getURLImagen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>latitud</column-name><column-value><![CDATA[");
		sb.append(getLatitud());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>longitud</column-name><column-value><![CDATA[");
		sb.append(getLongitud());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CargaDescuento.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CargaDescuento.class
		};
	private long _idCargaDesc;
	private String _local;
	private String _descuentoGeneral;
	private String _condicionesRestricciones;
	private String _direccion;
	private String _idDistrito;
	private String _distrito;
	private String _telefono;
	private String _web;
	private Date _finVigencia;
	private String _categoria;
	private String _coordenada;
	private String _URLImagen;
	private String _latitud;
	private String _longitud;
	private CargaDescuento _escapedModelProxy;
}