/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.FondosMutuosZonas;
import com.ext.portlet.halcon.model.FondosMutuosZonasModel;
import com.ext.portlet.halcon.model.FondosMutuosZonasSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FondosMutuosZonas service. Represents a row in the &quot;T_FONDOS_MUTUOS_ZONAS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.FondosMutuosZonasModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FondosMutuosZonasImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see FondosMutuosZonasImpl
 * @see com.ext.portlet.halcon.model.FondosMutuosZonas
 * @see com.ext.portlet.halcon.model.FondosMutuosZonasModel
 * @generated
 */
@JSON(strict = true)
public class FondosMutuosZonasModelImpl extends BaseModelImpl<FondosMutuosZonas>
	implements FondosMutuosZonasModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fondos mutuos zonas model instance should use the {@link com.ext.portlet.halcon.model.FondosMutuosZonas} interface instead.
	 */
	public static final String TABLE_NAME = "T_FONDOS_MUTUOS_ZONAS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fomz_IdFondoMutuoZona", Types.BIGINT },
			{ "fomz_CodigoZona", Types.VARCHAR },
			{ "fomz_Zona", Types.VARCHAR },
			{ "fomz_PuntajeInicial", Types.INTEGER },
			{ "fomz_PuntajeFinal", Types.INTEGER },
			{ "fomz_DescripcionZona", Types.VARCHAR },
			{ "fomz_Moneda", Types.VARCHAR },
			{ "fomz_Riesgo", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_FONDOS_MUTUOS_ZONAS (fomz_IdFondoMutuoZona LONG not null primary key IDENTITY,fomz_CodigoZona VARCHAR(75) null,fomz_Zona VARCHAR(75) null,fomz_PuntajeInicial INTEGER,fomz_PuntajeFinal INTEGER,fomz_DescripcionZona VARCHAR(75) null,fomz_Moneda VARCHAR(75) null,fomz_Riesgo VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_FONDOS_MUTUOS_ZONAS";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.FondosMutuosZonas"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.FondosMutuosZonas"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FondosMutuosZonas toModel(FondosMutuosZonasSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FondosMutuosZonas model = new FondosMutuosZonasImpl();

		model.setIdFondoMutuoZona(soapModel.getIdFondoMutuoZona());
		model.setCodigoZona(soapModel.getCodigoZona());
		model.setZona(soapModel.getZona());
		model.setPuntajeInicial(soapModel.getPuntajeInicial());
		model.setPuntajeFinal(soapModel.getPuntajeFinal());
		model.setDescripcionZona(soapModel.getDescripcionZona());
		model.setMoneda(soapModel.getMoneda());
		model.setRiesgo(soapModel.getRiesgo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FondosMutuosZonas> toModels(
		FondosMutuosZonasSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FondosMutuosZonas> models = new ArrayList<FondosMutuosZonas>(soapModels.length);

		for (FondosMutuosZonasSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.FondosMutuosZonas"));

	public FondosMutuosZonasModelImpl() {
	}

	public long getPrimaryKey() {
		return _idFondoMutuoZona;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdFondoMutuoZona(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idFondoMutuoZona);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FondosMutuosZonas.class;
	}

	public String getModelClassName() {
		return FondosMutuosZonas.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idFondoMutuoZona", getIdFondoMutuoZona());
		attributes.put("codigoZona", getCodigoZona());
		attributes.put("zona", getZona());
		attributes.put("puntajeInicial", getPuntajeInicial());
		attributes.put("puntajeFinal", getPuntajeFinal());
		attributes.put("descripcionZona", getDescripcionZona());
		attributes.put("moneda", getMoneda());
		attributes.put("riesgo", getRiesgo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idFondoMutuoZona = (Long)attributes.get("idFondoMutuoZona");

		if (idFondoMutuoZona != null) {
			setIdFondoMutuoZona(idFondoMutuoZona);
		}

		String codigoZona = (String)attributes.get("codigoZona");

		if (codigoZona != null) {
			setCodigoZona(codigoZona);
		}

		String zona = (String)attributes.get("zona");

		if (zona != null) {
			setZona(zona);
		}

		Integer puntajeInicial = (Integer)attributes.get("puntajeInicial");

		if (puntajeInicial != null) {
			setPuntajeInicial(puntajeInicial);
		}

		Integer puntajeFinal = (Integer)attributes.get("puntajeFinal");

		if (puntajeFinal != null) {
			setPuntajeFinal(puntajeFinal);
		}

		String descripcionZona = (String)attributes.get("descripcionZona");

		if (descripcionZona != null) {
			setDescripcionZona(descripcionZona);
		}

		String moneda = (String)attributes.get("moneda");

		if (moneda != null) {
			setMoneda(moneda);
		}

		String riesgo = (String)attributes.get("riesgo");

		if (riesgo != null) {
			setRiesgo(riesgo);
		}
	}

	@JSON
	public long getIdFondoMutuoZona() {
		return _idFondoMutuoZona;
	}

	public void setIdFondoMutuoZona(long idFondoMutuoZona) {
		_idFondoMutuoZona = idFondoMutuoZona;
	}

	@JSON
	public String getCodigoZona() {
		if (_codigoZona == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoZona;
		}
	}

	public void setCodigoZona(String codigoZona) {
		_codigoZona = codigoZona;
	}

	@JSON
	public String getZona() {
		if (_zona == null) {
			return StringPool.BLANK;
		}
		else {
			return _zona;
		}
	}

	public void setZona(String zona) {
		_zona = zona;
	}

	@JSON
	public Integer getPuntajeInicial() {
		return _puntajeInicial;
	}

	public void setPuntajeInicial(Integer puntajeInicial) {
		_puntajeInicial = puntajeInicial;
	}

	@JSON
	public Integer getPuntajeFinal() {
		return _puntajeFinal;
	}

	public void setPuntajeFinal(Integer puntajeFinal) {
		_puntajeFinal = puntajeFinal;
	}

	@JSON
	public String getDescripcionZona() {
		if (_descripcionZona == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcionZona;
		}
	}

	public void setDescripcionZona(String descripcionZona) {
		_descripcionZona = descripcionZona;
	}

	@JSON
	public String getMoneda() {
		if (_moneda == null) {
			return StringPool.BLANK;
		}
		else {
			return _moneda;
		}
	}

	public void setMoneda(String moneda) {
		_moneda = moneda;
	}

	@JSON
	public String getRiesgo() {
		if (_riesgo == null) {
			return StringPool.BLANK;
		}
		else {
			return _riesgo;
		}
	}

	public void setRiesgo(String riesgo) {
		_riesgo = riesgo;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FondosMutuosZonas.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FondosMutuosZonas toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FondosMutuosZonas)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FondosMutuosZonasImpl fondosMutuosZonasImpl = new FondosMutuosZonasImpl();

		fondosMutuosZonasImpl.setIdFondoMutuoZona(getIdFondoMutuoZona());
		fondosMutuosZonasImpl.setCodigoZona(getCodigoZona());
		fondosMutuosZonasImpl.setZona(getZona());
		fondosMutuosZonasImpl.setPuntajeInicial(getPuntajeInicial());
		fondosMutuosZonasImpl.setPuntajeFinal(getPuntajeFinal());
		fondosMutuosZonasImpl.setDescripcionZona(getDescripcionZona());
		fondosMutuosZonasImpl.setMoneda(getMoneda());
		fondosMutuosZonasImpl.setRiesgo(getRiesgo());

		fondosMutuosZonasImpl.resetOriginalValues();

		return fondosMutuosZonasImpl;
	}

	public int compareTo(FondosMutuosZonas fondosMutuosZonas) {
		long primaryKey = fondosMutuosZonas.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FondosMutuosZonas fondosMutuosZonas = null;

		try {
			fondosMutuosZonas = (FondosMutuosZonas)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = fondosMutuosZonas.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<FondosMutuosZonas> toCacheModel() {
		FondosMutuosZonasCacheModel fondosMutuosZonasCacheModel = new FondosMutuosZonasCacheModel();

		fondosMutuosZonasCacheModel.idFondoMutuoZona = getIdFondoMutuoZona();

		fondosMutuosZonasCacheModel.codigoZona = getCodigoZona();

		String codigoZona = fondosMutuosZonasCacheModel.codigoZona;

		if ((codigoZona != null) && (codigoZona.length() == 0)) {
			fondosMutuosZonasCacheModel.codigoZona = null;
		}

		fondosMutuosZonasCacheModel.zona = getZona();

		String zona = fondosMutuosZonasCacheModel.zona;

		if ((zona != null) && (zona.length() == 0)) {
			fondosMutuosZonasCacheModel.zona = null;
		}

		fondosMutuosZonasCacheModel.puntajeInicial = getPuntajeInicial();

		fondosMutuosZonasCacheModel.puntajeFinal = getPuntajeFinal();

		fondosMutuosZonasCacheModel.descripcionZona = getDescripcionZona();

		String descripcionZona = fondosMutuosZonasCacheModel.descripcionZona;

		if ((descripcionZona != null) && (descripcionZona.length() == 0)) {
			fondosMutuosZonasCacheModel.descripcionZona = null;
		}

		fondosMutuosZonasCacheModel.moneda = getMoneda();

		String moneda = fondosMutuosZonasCacheModel.moneda;

		if ((moneda != null) && (moneda.length() == 0)) {
			fondosMutuosZonasCacheModel.moneda = null;
		}

		fondosMutuosZonasCacheModel.riesgo = getRiesgo();

		String riesgo = fondosMutuosZonasCacheModel.riesgo;

		if ((riesgo != null) && (riesgo.length() == 0)) {
			fondosMutuosZonasCacheModel.riesgo = null;
		}

		return fondosMutuosZonasCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{idFondoMutuoZona=");
		sb.append(getIdFondoMutuoZona());
		sb.append(", codigoZona=");
		sb.append(getCodigoZona());
		sb.append(", zona=");
		sb.append(getZona());
		sb.append(", puntajeInicial=");
		sb.append(getPuntajeInicial());
		sb.append(", puntajeFinal=");
		sb.append(getPuntajeFinal());
		sb.append(", descripcionZona=");
		sb.append(getDescripcionZona());
		sb.append(", moneda=");
		sb.append(getMoneda());
		sb.append(", riesgo=");
		sb.append(getRiesgo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.FondosMutuosZonas");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idFondoMutuoZona</column-name><column-value><![CDATA[");
		sb.append(getIdFondoMutuoZona());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoZona</column-name><column-value><![CDATA[");
		sb.append(getCodigoZona());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zona</column-name><column-value><![CDATA[");
		sb.append(getZona());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puntajeInicial</column-name><column-value><![CDATA[");
		sb.append(getPuntajeInicial());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puntajeFinal</column-name><column-value><![CDATA[");
		sb.append(getPuntajeFinal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcionZona</column-name><column-value><![CDATA[");
		sb.append(getDescripcionZona());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moneda</column-name><column-value><![CDATA[");
		sb.append(getMoneda());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>riesgo</column-name><column-value><![CDATA[");
		sb.append(getRiesgo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FondosMutuosZonas.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FondosMutuosZonas.class
		};
	private long _idFondoMutuoZona;
	private String _codigoZona;
	private String _zona;
	private Integer _puntajeInicial;
	private Integer _puntajeFinal;
	private String _descripcionZona;
	private String _moneda;
	private String _riesgo;
	private FondosMutuosZonas _escapedModelProxy;
}