/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.SolicitudProducto;
import com.ext.portlet.halcon.model.SolicitudProductoModel;
import com.ext.portlet.halcon.model.SolicitudProductoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudProducto service. Represents a row in the &quot;T_SOLICITUD_PRODUCTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.SolicitudProductoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudProductoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see SolicitudProductoImpl
 * @see com.ext.portlet.halcon.model.SolicitudProducto
 * @see com.ext.portlet.halcon.model.SolicitudProductoModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudProductoModelImpl extends BaseModelImpl<SolicitudProducto>
	implements SolicitudProductoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud producto model instance should use the {@link com.ext.portlet.halcon.model.SolicitudProducto} interface instead.
	 */
	public static final String TABLE_NAME = "T_SOLICITUD_PRODUCTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "slpr_IdSolicitudProducto", Types.BIGINT },
			{ "slpr_IdTipoDocumentoAdq", Types.INTEGER },
			{ "slpr_IdTipoDocumento", Types.VARCHAR },
			{ "slpr_TipoCredito", Types.INTEGER },
			{ "slpr_CodigoCanal", Types.VARCHAR },
			{ "slpr_TipoEnvio", Types.VARCHAR },
			{ "slpr_NumeroDocumento", Types.VARCHAR },
			{ "slpr_ApellidoPaterno", Types.VARCHAR },
			{ "slpr_ApellidoMaterno", Types.VARCHAR },
			{ "slpr_PrimerNombre", Types.VARCHAR },
			{ "slpr_SegundoNombre", Types.VARCHAR },
			{ "slpr_FechaNacimiento", Types.TIMESTAMP },
			{ "slpr_Sexo", Types.VARCHAR },
			{ "slpr_RentaMensual", Types.DOUBLE },
			{ "slpr_Celular", Types.VARCHAR },
			{ "slpr_TelefonoCasa", Types.VARCHAR },
			{ "slpr_TelefonoTrabajo", Types.VARCHAR },
			{ "slpr_Anexo", Types.VARCHAR },
			{ "slpr_IdEstadoCivilAdq", Types.INTEGER },
			{ "slpr_IdEstadoCivil", Types.VARCHAR },
			{ "slpr_RUC", Types.VARCHAR },
			{ "slpr_RazonSocial", Types.VARCHAR },
			{ "slpr_SituacionLaboral", Types.VARCHAR },
			{ "slpr_IdSituacionLaboral", Types.INTEGER },
			{ "slpr_IdDepartamento", Types.VARCHAR },
			{ "slpr_IdProvincia", Types.VARCHAR },
			{ "slpr_IdDistrito", Types.VARCHAR },
			{ "slpr_Departamento", Types.VARCHAR },
			{ "slpr_Provincia", Types.VARCHAR },
			{ "slpr_Distrito", Types.VARCHAR },
			{ "slpr_CorreoElectronico", Types.VARCHAR },
			{ "slpr_DireccionEnvio", Types.VARCHAR },
			{ "slpr_PlacaVehiculo", Types.VARCHAR },
			{ "slpr_Session", Types.VARCHAR },
			{ "slpr_IPCliente", Types.VARCHAR },
			{ "slpr_HorarioEnvio", Types.TIMESTAMP },
			{ "slpr_FechaRegistro", Types.TIMESTAMP },
			{ "slpr_UTMSource", Types.VARCHAR },
			{ "slpr_UTMMedium", Types.VARCHAR },
			{ "slpr_UTMCampaing", Types.VARCHAR },
			{ "slpr_UTMContent", Types.VARCHAR },
			{ "slpr_FechaResultadoPreCalif", Types.TIMESTAMP },
			{ "slpr_FechaEnvioLead", Types.TIMESTAMP },
			{ "slpr_FechaEnvioEmailing", Types.TIMESTAMP },
			{ "slpr_EstadoPreCalificacion", Types.BOOLEAN },
			{ "slpr_EstadoRegLead", Types.BOOLEAN },
			{ "slpr_EstadoEnvCorreo", Types.BOOLEAN },
			{ "slpr_RespPreCalificacion", Types.VARCHAR },
			{ "slpr_DescripcionLead", Types.VARCHAR },
			{ "slpr_FechaActualizacion", Types.TIMESTAMP },
			{ "slpr_MontoProspectado", Types.DOUBLE },
			{ "slpr_CodigoCampania", Types.VARCHAR },
			{ "slpr_CodigoMoneda", Types.VARCHAR },
			{ "slpr_NombreSupervisor", Types.VARCHAR },
			{ "slpr_RespRegLead", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_SOLICITUD_PRODUCTO (slpr_IdSolicitudProducto LONG not null primary key IDENTITY,slpr_IdTipoDocumentoAdq INTEGER,slpr_IdTipoDocumento VARCHAR(75) null,slpr_TipoCredito INTEGER,slpr_CodigoCanal VARCHAR(75) null,slpr_TipoEnvio VARCHAR(75) null,slpr_NumeroDocumento VARCHAR(75) null,slpr_ApellidoPaterno VARCHAR(75) null,slpr_ApellidoMaterno VARCHAR(75) null,slpr_PrimerNombre VARCHAR(75) null,slpr_SegundoNombre VARCHAR(75) null,slpr_FechaNacimiento DATE null,slpr_Sexo VARCHAR(75) null,slpr_RentaMensual DOUBLE,slpr_Celular VARCHAR(75) null,slpr_TelefonoCasa VARCHAR(75) null,slpr_TelefonoTrabajo VARCHAR(75) null,slpr_Anexo VARCHAR(75) null,slpr_IdEstadoCivilAdq INTEGER,slpr_IdEstadoCivil VARCHAR(75) null,slpr_RUC VARCHAR(75) null,slpr_RazonSocial VARCHAR(75) null,slpr_SituacionLaboral VARCHAR(75) null,slpr_IdSituacionLaboral INTEGER,slpr_IdDepartamento VARCHAR(75) null,slpr_IdProvincia VARCHAR(75) null,slpr_IdDistrito VARCHAR(75) null,slpr_Departamento VARCHAR(75) null,slpr_Provincia VARCHAR(75) null,slpr_Distrito VARCHAR(75) null,slpr_CorreoElectronico VARCHAR(75) null,slpr_DireccionEnvio VARCHAR(75) null,slpr_PlacaVehiculo VARCHAR(75) null,slpr_Session VARCHAR(75) null,slpr_IPCliente VARCHAR(75) null,slpr_HorarioEnvio DATE null,slpr_FechaRegistro DATE null,slpr_UTMSource VARCHAR(75) null,slpr_UTMMedium VARCHAR(75) null,slpr_UTMCampaing VARCHAR(75) null,slpr_UTMContent VARCHAR(75) null,slpr_FechaResultadoPreCalif DATE null,slpr_FechaEnvioLead DATE null,slpr_FechaEnvioEmailing DATE null,slpr_EstadoPreCalificacion BOOLEAN,slpr_EstadoRegLead BOOLEAN,slpr_EstadoEnvCorreo BOOLEAN,slpr_RespPreCalificacion VARCHAR(75) null,slpr_DescripcionLead VARCHAR(75) null,slpr_FechaActualizacion DATE null,slpr_MontoProspectado DOUBLE,slpr_CodigoCampania VARCHAR(75) null,slpr_CodigoMoneda VARCHAR(75) null,slpr_NombreSupervisor VARCHAR(75) null,slpr_RespRegLead VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_SOLICITUD_PRODUCTO";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.SolicitudProducto"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.SolicitudProducto"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudProducto toModel(SolicitudProductoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudProducto model = new SolicitudProductoImpl();

		model.setIdSolicitudProducto(soapModel.getIdSolicitudProducto());
		model.setIdTipoDocumentoAdq(soapModel.getIdTipoDocumentoAdq());
		model.setIdTipoDocumento(soapModel.getIdTipoDocumento());
		model.setTipoCredito(soapModel.getTipoCredito());
		model.setCodigoCanal(soapModel.getCodigoCanal());
		model.setTipoEnvio(soapModel.getTipoEnvio());
		model.setNumeroDocumento(soapModel.getNumeroDocumento());
		model.setApellidoPaterno(soapModel.getApellidoPaterno());
		model.setApellidoMaterno(soapModel.getApellidoMaterno());
		model.setPrimerNombre(soapModel.getPrimerNombre());
		model.setSegundoNombre(soapModel.getSegundoNombre());
		model.setFechaNacimiento(soapModel.getFechaNacimiento());
		model.setSexo(soapModel.getSexo());
		model.setRentaMensual(soapModel.getRentaMensual());
		model.setCelular(soapModel.getCelular());
		model.setTelefonoCasa(soapModel.getTelefonoCasa());
		model.setTelefonoTrabajo(soapModel.getTelefonoTrabajo());
		model.setAnexo(soapModel.getAnexo());
		model.setIdEstadoCivilAdq(soapModel.getIdEstadoCivilAdq());
		model.setIdEstadoCivil(soapModel.getIdEstadoCivil());
		model.setRUC(soapModel.getRUC());
		model.setRazonSocial(soapModel.getRazonSocial());
		model.setSituacionLaboral(soapModel.getSituacionLaboral());
		model.setIdSituacionLaboral(soapModel.getIdSituacionLaboral());
		model.setIdDepartamento(soapModel.getIdDepartamento());
		model.setIdProvincia(soapModel.getIdProvincia());
		model.setIdDistrito(soapModel.getIdDistrito());
		model.setNomDepartamento(soapModel.getNomDepartamento());
		model.setNomProvincia(soapModel.getNomProvincia());
		model.setNomDistrito(soapModel.getNomDistrito());
		model.setCorreoElectronico(soapModel.getCorreoElectronico());
		model.setDireccionEnvio(soapModel.getDireccionEnvio());
		model.setPlacaVehiculo(soapModel.getPlacaVehiculo());
		model.setIdSession(soapModel.getIdSession());
		model.setIPCliente(soapModel.getIPCliente());
		model.setHorarioEnvio(soapModel.getHorarioEnvio());
		model.setFechaRegistro(soapModel.getFechaRegistro());
		model.setUTMSource(soapModel.getUTMSource());
		model.setUTMMedium(soapModel.getUTMMedium());
		model.setUTMCampaing(soapModel.getUTMCampaing());
		model.setUTMContent(soapModel.getUTMContent());
		model.setFechaResultadoPreCalif(soapModel.getFechaResultadoPreCalif());
		model.setFechaEnvioLead(soapModel.getFechaEnvioLead());
		model.setFechaEnvioEmailing(soapModel.getFechaEnvioEmailing());
		model.setEstadoPreCalificacion(soapModel.getEstadoPreCalificacion());
		model.setEstadoRegLead(soapModel.getEstadoRegLead());
		model.setEstadoEnvCorreo(soapModel.getEstadoEnvCorreo());
		model.setRespPreCalificacion(soapModel.getRespPreCalificacion());
		model.setDescripcionLead(soapModel.getDescripcionLead());
		model.setFechaActualizacion(soapModel.getFechaActualizacion());
		model.setMontoProspectado(soapModel.getMontoProspectado());
		model.setCodigoCampania(soapModel.getCodigoCampania());
		model.setCodigoMoneda(soapModel.getCodigoMoneda());
		model.setNombreSupervisor(soapModel.getNombreSupervisor());
		model.setRespRegLead(soapModel.getRespRegLead());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudProducto> toModels(
		SolicitudProductoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudProducto> models = new ArrayList<SolicitudProducto>(soapModels.length);

		for (SolicitudProductoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.SolicitudProducto"));

	public SolicitudProductoModelImpl() {
	}

	public long getPrimaryKey() {
		return _idSolicitudProducto;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdSolicitudProducto(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idSolicitudProducto);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SolicitudProducto.class;
	}

	public String getModelClassName() {
		return SolicitudProducto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idSolicitudProducto", getIdSolicitudProducto());
		attributes.put("idTipoDocumentoAdq", getIdTipoDocumentoAdq());
		attributes.put("idTipoDocumento", getIdTipoDocumento());
		attributes.put("tipoCredito", getTipoCredito());
		attributes.put("codigoCanal", getCodigoCanal());
		attributes.put("tipoEnvio", getTipoEnvio());
		attributes.put("numeroDocumento", getNumeroDocumento());
		attributes.put("apellidoPaterno", getApellidoPaterno());
		attributes.put("apellidoMaterno", getApellidoMaterno());
		attributes.put("primerNombre", getPrimerNombre());
		attributes.put("segundoNombre", getSegundoNombre());
		attributes.put("fechaNacimiento", getFechaNacimiento());
		attributes.put("sexo", getSexo());
		attributes.put("rentaMensual", getRentaMensual());
		attributes.put("celular", getCelular());
		attributes.put("telefonoCasa", getTelefonoCasa());
		attributes.put("telefonoTrabajo", getTelefonoTrabajo());
		attributes.put("anexo", getAnexo());
		attributes.put("idEstadoCivilAdq", getIdEstadoCivilAdq());
		attributes.put("idEstadoCivil", getIdEstadoCivil());
		attributes.put("RUC", getRUC());
		attributes.put("razonSocial", getRazonSocial());
		attributes.put("situacionLaboral", getSituacionLaboral());
		attributes.put("idSituacionLaboral", getIdSituacionLaboral());
		attributes.put("idDepartamento", getIdDepartamento());
		attributes.put("idProvincia", getIdProvincia());
		attributes.put("idDistrito", getIdDistrito());
		attributes.put("nomDepartamento", getNomDepartamento());
		attributes.put("nomProvincia", getNomProvincia());
		attributes.put("nomDistrito", getNomDistrito());
		attributes.put("correoElectronico", getCorreoElectronico());
		attributes.put("direccionEnvio", getDireccionEnvio());
		attributes.put("placaVehiculo", getPlacaVehiculo());
		attributes.put("IdSession", getIdSession());
		attributes.put("IPCliente", getIPCliente());
		attributes.put("horarioEnvio", getHorarioEnvio());
		attributes.put("fechaRegistro", getFechaRegistro());
		attributes.put("UTMSource", getUTMSource());
		attributes.put("UTMMedium", getUTMMedium());
		attributes.put("UTMCampaing", getUTMCampaing());
		attributes.put("UTMContent", getUTMContent());
		attributes.put("fechaResultadoPreCalif", getFechaResultadoPreCalif());
		attributes.put("fechaEnvioLead", getFechaEnvioLead());
		attributes.put("fechaEnvioEmailing", getFechaEnvioEmailing());
		attributes.put("estadoPreCalificacion", getEstadoPreCalificacion());
		attributes.put("estadoRegLead", getEstadoRegLead());
		attributes.put("estadoEnvCorreo", getEstadoEnvCorreo());
		attributes.put("respPreCalificacion", getRespPreCalificacion());
		attributes.put("descripcionLead", getDescripcionLead());
		attributes.put("fechaActualizacion", getFechaActualizacion());
		attributes.put("montoProspectado", getMontoProspectado());
		attributes.put("codigoCampania", getCodigoCampania());
		attributes.put("codigoMoneda", getCodigoMoneda());
		attributes.put("nombreSupervisor", getNombreSupervisor());
		attributes.put("respRegLead", getRespRegLead());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idSolicitudProducto = (Long)attributes.get("idSolicitudProducto");

		if (idSolicitudProducto != null) {
			setIdSolicitudProducto(idSolicitudProducto);
		}

		Integer idTipoDocumentoAdq = (Integer)attributes.get(
				"idTipoDocumentoAdq");

		if (idTipoDocumentoAdq != null) {
			setIdTipoDocumentoAdq(idTipoDocumentoAdq);
		}

		String idTipoDocumento = (String)attributes.get("idTipoDocumento");

		if (idTipoDocumento != null) {
			setIdTipoDocumento(idTipoDocumento);
		}

		Integer tipoCredito = (Integer)attributes.get("tipoCredito");

		if (tipoCredito != null) {
			setTipoCredito(tipoCredito);
		}

		String codigoCanal = (String)attributes.get("codigoCanal");

		if (codigoCanal != null) {
			setCodigoCanal(codigoCanal);
		}

		String tipoEnvio = (String)attributes.get("tipoEnvio");

		if (tipoEnvio != null) {
			setTipoEnvio(tipoEnvio);
		}

		String numeroDocumento = (String)attributes.get("numeroDocumento");

		if (numeroDocumento != null) {
			setNumeroDocumento(numeroDocumento);
		}

		String apellidoPaterno = (String)attributes.get("apellidoPaterno");

		if (apellidoPaterno != null) {
			setApellidoPaterno(apellidoPaterno);
		}

		String apellidoMaterno = (String)attributes.get("apellidoMaterno");

		if (apellidoMaterno != null) {
			setApellidoMaterno(apellidoMaterno);
		}

		String primerNombre = (String)attributes.get("primerNombre");

		if (primerNombre != null) {
			setPrimerNombre(primerNombre);
		}

		String segundoNombre = (String)attributes.get("segundoNombre");

		if (segundoNombre != null) {
			setSegundoNombre(segundoNombre);
		}

		Date fechaNacimiento = (Date)attributes.get("fechaNacimiento");

		if (fechaNacimiento != null) {
			setFechaNacimiento(fechaNacimiento);
		}

		String sexo = (String)attributes.get("sexo");

		if (sexo != null) {
			setSexo(sexo);
		}

		Double rentaMensual = (Double)attributes.get("rentaMensual");

		if (rentaMensual != null) {
			setRentaMensual(rentaMensual);
		}

		String celular = (String)attributes.get("celular");

		if (celular != null) {
			setCelular(celular);
		}

		String telefonoCasa = (String)attributes.get("telefonoCasa");

		if (telefonoCasa != null) {
			setTelefonoCasa(telefonoCasa);
		}

		String telefonoTrabajo = (String)attributes.get("telefonoTrabajo");

		if (telefonoTrabajo != null) {
			setTelefonoTrabajo(telefonoTrabajo);
		}

		String anexo = (String)attributes.get("anexo");

		if (anexo != null) {
			setAnexo(anexo);
		}

		Integer idEstadoCivilAdq = (Integer)attributes.get("idEstadoCivilAdq");

		if (idEstadoCivilAdq != null) {
			setIdEstadoCivilAdq(idEstadoCivilAdq);
		}

		String idEstadoCivil = (String)attributes.get("idEstadoCivil");

		if (idEstadoCivil != null) {
			setIdEstadoCivil(idEstadoCivil);
		}

		String RUC = (String)attributes.get("RUC");

		if (RUC != null) {
			setRUC(RUC);
		}

		String razonSocial = (String)attributes.get("razonSocial");

		if (razonSocial != null) {
			setRazonSocial(razonSocial);
		}

		String situacionLaboral = (String)attributes.get("situacionLaboral");

		if (situacionLaboral != null) {
			setSituacionLaboral(situacionLaboral);
		}

		Integer idSituacionLaboral = (Integer)attributes.get(
				"idSituacionLaboral");

		if (idSituacionLaboral != null) {
			setIdSituacionLaboral(idSituacionLaboral);
		}

		String idDepartamento = (String)attributes.get("idDepartamento");

		if (idDepartamento != null) {
			setIdDepartamento(idDepartamento);
		}

		String idProvincia = (String)attributes.get("idProvincia");

		if (idProvincia != null) {
			setIdProvincia(idProvincia);
		}

		String idDistrito = (String)attributes.get("idDistrito");

		if (idDistrito != null) {
			setIdDistrito(idDistrito);
		}

		String nomDepartamento = (String)attributes.get("nomDepartamento");

		if (nomDepartamento != null) {
			setNomDepartamento(nomDepartamento);
		}

		String nomProvincia = (String)attributes.get("nomProvincia");

		if (nomProvincia != null) {
			setNomProvincia(nomProvincia);
		}

		String nomDistrito = (String)attributes.get("nomDistrito");

		if (nomDistrito != null) {
			setNomDistrito(nomDistrito);
		}

		String correoElectronico = (String)attributes.get("correoElectronico");

		if (correoElectronico != null) {
			setCorreoElectronico(correoElectronico);
		}

		String direccionEnvio = (String)attributes.get("direccionEnvio");

		if (direccionEnvio != null) {
			setDireccionEnvio(direccionEnvio);
		}

		String placaVehiculo = (String)attributes.get("placaVehiculo");

		if (placaVehiculo != null) {
			setPlacaVehiculo(placaVehiculo);
		}

		String IdSession = (String)attributes.get("IdSession");

		if (IdSession != null) {
			setIdSession(IdSession);
		}

		String IPCliente = (String)attributes.get("IPCliente");

		if (IPCliente != null) {
			setIPCliente(IPCliente);
		}

		Date horarioEnvio = (Date)attributes.get("horarioEnvio");

		if (horarioEnvio != null) {
			setHorarioEnvio(horarioEnvio);
		}

		Date fechaRegistro = (Date)attributes.get("fechaRegistro");

		if (fechaRegistro != null) {
			setFechaRegistro(fechaRegistro);
		}

		String UTMSource = (String)attributes.get("UTMSource");

		if (UTMSource != null) {
			setUTMSource(UTMSource);
		}

		String UTMMedium = (String)attributes.get("UTMMedium");

		if (UTMMedium != null) {
			setUTMMedium(UTMMedium);
		}

		String UTMCampaing = (String)attributes.get("UTMCampaing");

		if (UTMCampaing != null) {
			setUTMCampaing(UTMCampaing);
		}

		String UTMContent = (String)attributes.get("UTMContent");

		if (UTMContent != null) {
			setUTMContent(UTMContent);
		}

		Date fechaResultadoPreCalif = (Date)attributes.get(
				"fechaResultadoPreCalif");

		if (fechaResultadoPreCalif != null) {
			setFechaResultadoPreCalif(fechaResultadoPreCalif);
		}

		Date fechaEnvioLead = (Date)attributes.get("fechaEnvioLead");

		if (fechaEnvioLead != null) {
			setFechaEnvioLead(fechaEnvioLead);
		}

		Date fechaEnvioEmailing = (Date)attributes.get("fechaEnvioEmailing");

		if (fechaEnvioEmailing != null) {
			setFechaEnvioEmailing(fechaEnvioEmailing);
		}

		Boolean estadoPreCalificacion = (Boolean)attributes.get(
				"estadoPreCalificacion");

		if (estadoPreCalificacion != null) {
			setEstadoPreCalificacion(estadoPreCalificacion);
		}

		Boolean estadoRegLead = (Boolean)attributes.get("estadoRegLead");

		if (estadoRegLead != null) {
			setEstadoRegLead(estadoRegLead);
		}

		Boolean estadoEnvCorreo = (Boolean)attributes.get("estadoEnvCorreo");

		if (estadoEnvCorreo != null) {
			setEstadoEnvCorreo(estadoEnvCorreo);
		}

		String respPreCalificacion = (String)attributes.get(
				"respPreCalificacion");

		if (respPreCalificacion != null) {
			setRespPreCalificacion(respPreCalificacion);
		}

		String descripcionLead = (String)attributes.get("descripcionLead");

		if (descripcionLead != null) {
			setDescripcionLead(descripcionLead);
		}

		Date fechaActualizacion = (Date)attributes.get("fechaActualizacion");

		if (fechaActualizacion != null) {
			setFechaActualizacion(fechaActualizacion);
		}

		Double montoProspectado = (Double)attributes.get("montoProspectado");

		if (montoProspectado != null) {
			setMontoProspectado(montoProspectado);
		}

		String codigoCampania = (String)attributes.get("codigoCampania");

		if (codigoCampania != null) {
			setCodigoCampania(codigoCampania);
		}

		String codigoMoneda = (String)attributes.get("codigoMoneda");

		if (codigoMoneda != null) {
			setCodigoMoneda(codigoMoneda);
		}

		String nombreSupervisor = (String)attributes.get("nombreSupervisor");

		if (nombreSupervisor != null) {
			setNombreSupervisor(nombreSupervisor);
		}

		String respRegLead = (String)attributes.get("respRegLead");

		if (respRegLead != null) {
			setRespRegLead(respRegLead);
		}
	}

	@JSON
	public long getIdSolicitudProducto() {
		return _idSolicitudProducto;
	}

	public void setIdSolicitudProducto(long idSolicitudProducto) {
		_idSolicitudProducto = idSolicitudProducto;
	}

	@JSON
	public Integer getIdTipoDocumentoAdq() {
		return _idTipoDocumentoAdq;
	}

	public void setIdTipoDocumentoAdq(Integer idTipoDocumentoAdq) {
		_idTipoDocumentoAdq = idTipoDocumentoAdq;
	}

	@JSON
	public String getIdTipoDocumento() {
		if (_idTipoDocumento == null) {
			return StringPool.BLANK;
		}
		else {
			return _idTipoDocumento;
		}
	}

	public void setIdTipoDocumento(String idTipoDocumento) {
		_idTipoDocumento = idTipoDocumento;
	}

	@JSON
	public Integer getTipoCredito() {
		return _tipoCredito;
	}

	public void setTipoCredito(Integer tipoCredito) {
		_tipoCredito = tipoCredito;
	}

	@JSON
	public String getCodigoCanal() {
		if (_codigoCanal == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoCanal;
		}
	}

	public void setCodigoCanal(String codigoCanal) {
		_codigoCanal = codigoCanal;
	}

	@JSON
	public String getTipoEnvio() {
		if (_tipoEnvio == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoEnvio;
		}
	}

	public void setTipoEnvio(String tipoEnvio) {
		_tipoEnvio = tipoEnvio;
	}

	@JSON
	public String getNumeroDocumento() {
		if (_numeroDocumento == null) {
			return StringPool.BLANK;
		}
		else {
			return _numeroDocumento;
		}
	}

	public void setNumeroDocumento(String numeroDocumento) {
		_numeroDocumento = numeroDocumento;
	}

	@JSON
	public String getApellidoPaterno() {
		if (_apellidoPaterno == null) {
			return StringPool.BLANK;
		}
		else {
			return _apellidoPaterno;
		}
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		_apellidoPaterno = apellidoPaterno;
	}

	@JSON
	public String getApellidoMaterno() {
		if (_apellidoMaterno == null) {
			return StringPool.BLANK;
		}
		else {
			return _apellidoMaterno;
		}
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		_apellidoMaterno = apellidoMaterno;
	}

	@JSON
	public String getPrimerNombre() {
		if (_primerNombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _primerNombre;
		}
	}

	public void setPrimerNombre(String primerNombre) {
		_primerNombre = primerNombre;
	}

	@JSON
	public String getSegundoNombre() {
		if (_segundoNombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _segundoNombre;
		}
	}

	public void setSegundoNombre(String segundoNombre) {
		_segundoNombre = segundoNombre;
	}

	@JSON
	public Date getFechaNacimiento() {
		return _fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		_fechaNacimiento = fechaNacimiento;
	}

	@JSON
	public String getSexo() {
		if (_sexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _sexo;
		}
	}

	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	@JSON
	public Double getRentaMensual() {
		return _rentaMensual;
	}

	public void setRentaMensual(Double rentaMensual) {
		_rentaMensual = rentaMensual;
	}

	@JSON
	public String getCelular() {
		if (_celular == null) {
			return StringPool.BLANK;
		}
		else {
			return _celular;
		}
	}

	public void setCelular(String celular) {
		_celular = celular;
	}

	@JSON
	public String getTelefonoCasa() {
		if (_telefonoCasa == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonoCasa;
		}
	}

	public void setTelefonoCasa(String telefonoCasa) {
		_telefonoCasa = telefonoCasa;
	}

	@JSON
	public String getTelefonoTrabajo() {
		if (_telefonoTrabajo == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonoTrabajo;
		}
	}

	public void setTelefonoTrabajo(String telefonoTrabajo) {
		_telefonoTrabajo = telefonoTrabajo;
	}

	@JSON
	public String getAnexo() {
		if (_anexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _anexo;
		}
	}

	public void setAnexo(String anexo) {
		_anexo = anexo;
	}

	@JSON
	public Integer getIdEstadoCivilAdq() {
		return _idEstadoCivilAdq;
	}

	public void setIdEstadoCivilAdq(Integer idEstadoCivilAdq) {
		_idEstadoCivilAdq = idEstadoCivilAdq;
	}

	@JSON
	public String getIdEstadoCivil() {
		if (_idEstadoCivil == null) {
			return StringPool.BLANK;
		}
		else {
			return _idEstadoCivil;
		}
	}

	public void setIdEstadoCivil(String idEstadoCivil) {
		_idEstadoCivil = idEstadoCivil;
	}

	@JSON
	public String getRUC() {
		if (_RUC == null) {
			return StringPool.BLANK;
		}
		else {
			return _RUC;
		}
	}

	public void setRUC(String RUC) {
		_RUC = RUC;
	}

	@JSON
	public String getRazonSocial() {
		if (_razonSocial == null) {
			return StringPool.BLANK;
		}
		else {
			return _razonSocial;
		}
	}

	public void setRazonSocial(String razonSocial) {
		_razonSocial = razonSocial;
	}

	@JSON
	public String getSituacionLaboral() {
		if (_situacionLaboral == null) {
			return StringPool.BLANK;
		}
		else {
			return _situacionLaboral;
		}
	}

	public void setSituacionLaboral(String situacionLaboral) {
		_situacionLaboral = situacionLaboral;
	}

	@JSON
	public Integer getIdSituacionLaboral() {
		return _idSituacionLaboral;
	}

	public void setIdSituacionLaboral(Integer idSituacionLaboral) {
		_idSituacionLaboral = idSituacionLaboral;
	}

	@JSON
	public String getIdDepartamento() {
		if (_idDepartamento == null) {
			return StringPool.BLANK;
		}
		else {
			return _idDepartamento;
		}
	}

	public void setIdDepartamento(String idDepartamento) {
		_idDepartamento = idDepartamento;
	}

	@JSON
	public String getIdProvincia() {
		if (_idProvincia == null) {
			return StringPool.BLANK;
		}
		else {
			return _idProvincia;
		}
	}

	public void setIdProvincia(String idProvincia) {
		_idProvincia = idProvincia;
	}

	@JSON
	public String getIdDistrito() {
		if (_idDistrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _idDistrito;
		}
	}

	public void setIdDistrito(String idDistrito) {
		_idDistrito = idDistrito;
	}

	@JSON
	public String getNomDepartamento() {
		if (_nomDepartamento == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomDepartamento;
		}
	}

	public void setNomDepartamento(String nomDepartamento) {
		_nomDepartamento = nomDepartamento;
	}

	@JSON
	public String getNomProvincia() {
		if (_nomProvincia == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomProvincia;
		}
	}

	public void setNomProvincia(String nomProvincia) {
		_nomProvincia = nomProvincia;
	}

	@JSON
	public String getNomDistrito() {
		if (_nomDistrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomDistrito;
		}
	}

	public void setNomDistrito(String nomDistrito) {
		_nomDistrito = nomDistrito;
	}

	@JSON
	public String getCorreoElectronico() {
		if (_correoElectronico == null) {
			return StringPool.BLANK;
		}
		else {
			return _correoElectronico;
		}
	}

	public void setCorreoElectronico(String correoElectronico) {
		_correoElectronico = correoElectronico;
	}

	@JSON
	public String getDireccionEnvio() {
		if (_direccionEnvio == null) {
			return StringPool.BLANK;
		}
		else {
			return _direccionEnvio;
		}
	}

	public void setDireccionEnvio(String direccionEnvio) {
		_direccionEnvio = direccionEnvio;
	}

	@JSON
	public String getPlacaVehiculo() {
		if (_placaVehiculo == null) {
			return StringPool.BLANK;
		}
		else {
			return _placaVehiculo;
		}
	}

	public void setPlacaVehiculo(String placaVehiculo) {
		_placaVehiculo = placaVehiculo;
	}

	@JSON
	public String getIdSession() {
		if (_IdSession == null) {
			return StringPool.BLANK;
		}
		else {
			return _IdSession;
		}
	}

	public void setIdSession(String IdSession) {
		_IdSession = IdSession;
	}

	@JSON
	public String getIPCliente() {
		if (_IPCliente == null) {
			return StringPool.BLANK;
		}
		else {
			return _IPCliente;
		}
	}

	public void setIPCliente(String IPCliente) {
		_IPCliente = IPCliente;
	}

	@JSON
	public Date getHorarioEnvio() {
		return _horarioEnvio;
	}

	public void setHorarioEnvio(Date horarioEnvio) {
		_horarioEnvio = horarioEnvio;
	}

	@JSON
	public Date getFechaRegistro() {
		return _fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		_fechaRegistro = fechaRegistro;
	}

	@JSON
	public String getUTMSource() {
		if (_UTMSource == null) {
			return StringPool.BLANK;
		}
		else {
			return _UTMSource;
		}
	}

	public void setUTMSource(String UTMSource) {
		_UTMSource = UTMSource;
	}

	@JSON
	public String getUTMMedium() {
		if (_UTMMedium == null) {
			return StringPool.BLANK;
		}
		else {
			return _UTMMedium;
		}
	}

	public void setUTMMedium(String UTMMedium) {
		_UTMMedium = UTMMedium;
	}

	@JSON
	public String getUTMCampaing() {
		if (_UTMCampaing == null) {
			return StringPool.BLANK;
		}
		else {
			return _UTMCampaing;
		}
	}

	public void setUTMCampaing(String UTMCampaing) {
		_UTMCampaing = UTMCampaing;
	}

	@JSON
	public String getUTMContent() {
		if (_UTMContent == null) {
			return StringPool.BLANK;
		}
		else {
			return _UTMContent;
		}
	}

	public void setUTMContent(String UTMContent) {
		_UTMContent = UTMContent;
	}

	@JSON
	public Date getFechaResultadoPreCalif() {
		return _fechaResultadoPreCalif;
	}

	public void setFechaResultadoPreCalif(Date fechaResultadoPreCalif) {
		_fechaResultadoPreCalif = fechaResultadoPreCalif;
	}

	@JSON
	public Date getFechaEnvioLead() {
		return _fechaEnvioLead;
	}

	public void setFechaEnvioLead(Date fechaEnvioLead) {
		_fechaEnvioLead = fechaEnvioLead;
	}

	@JSON
	public Date getFechaEnvioEmailing() {
		return _fechaEnvioEmailing;
	}

	public void setFechaEnvioEmailing(Date fechaEnvioEmailing) {
		_fechaEnvioEmailing = fechaEnvioEmailing;
	}

	@JSON
	public Boolean getEstadoPreCalificacion() {
		return _estadoPreCalificacion;
	}

	public void setEstadoPreCalificacion(Boolean estadoPreCalificacion) {
		_estadoPreCalificacion = estadoPreCalificacion;
	}

	@JSON
	public Boolean getEstadoRegLead() {
		return _estadoRegLead;
	}

	public void setEstadoRegLead(Boolean estadoRegLead) {
		_estadoRegLead = estadoRegLead;
	}

	@JSON
	public Boolean getEstadoEnvCorreo() {
		return _estadoEnvCorreo;
	}

	public void setEstadoEnvCorreo(Boolean estadoEnvCorreo) {
		_estadoEnvCorreo = estadoEnvCorreo;
	}

	@JSON
	public String getRespPreCalificacion() {
		if (_respPreCalificacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _respPreCalificacion;
		}
	}

	public void setRespPreCalificacion(String respPreCalificacion) {
		_respPreCalificacion = respPreCalificacion;
	}

	@JSON
	public String getDescripcionLead() {
		if (_descripcionLead == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcionLead;
		}
	}

	public void setDescripcionLead(String descripcionLead) {
		_descripcionLead = descripcionLead;
	}

	@JSON
	public Date getFechaActualizacion() {
		return _fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		_fechaActualizacion = fechaActualizacion;
	}

	@JSON
	public Double getMontoProspectado() {
		return _montoProspectado;
	}

	public void setMontoProspectado(Double montoProspectado) {
		_montoProspectado = montoProspectado;
	}

	@JSON
	public String getCodigoCampania() {
		if (_codigoCampania == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoCampania;
		}
	}

	public void setCodigoCampania(String codigoCampania) {
		_codigoCampania = codigoCampania;
	}

	@JSON
	public String getCodigoMoneda() {
		if (_codigoMoneda == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoMoneda;
		}
	}

	public void setCodigoMoneda(String codigoMoneda) {
		_codigoMoneda = codigoMoneda;
	}

	@JSON
	public String getNombreSupervisor() {
		if (_nombreSupervisor == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombreSupervisor;
		}
	}

	public void setNombreSupervisor(String nombreSupervisor) {
		_nombreSupervisor = nombreSupervisor;
	}

	@JSON
	public String getRespRegLead() {
		if (_respRegLead == null) {
			return StringPool.BLANK;
		}
		else {
			return _respRegLead;
		}
	}

	public void setRespRegLead(String respRegLead) {
		_respRegLead = respRegLead;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SolicitudProducto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SolicitudProducto toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SolicitudProducto)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SolicitudProductoImpl solicitudProductoImpl = new SolicitudProductoImpl();

		solicitudProductoImpl.setIdSolicitudProducto(getIdSolicitudProducto());
		solicitudProductoImpl.setIdTipoDocumentoAdq(getIdTipoDocumentoAdq());
		solicitudProductoImpl.setIdTipoDocumento(getIdTipoDocumento());
		solicitudProductoImpl.setTipoCredito(getTipoCredito());
		solicitudProductoImpl.setCodigoCanal(getCodigoCanal());
		solicitudProductoImpl.setTipoEnvio(getTipoEnvio());
		solicitudProductoImpl.setNumeroDocumento(getNumeroDocumento());
		solicitudProductoImpl.setApellidoPaterno(getApellidoPaterno());
		solicitudProductoImpl.setApellidoMaterno(getApellidoMaterno());
		solicitudProductoImpl.setPrimerNombre(getPrimerNombre());
		solicitudProductoImpl.setSegundoNombre(getSegundoNombre());
		solicitudProductoImpl.setFechaNacimiento(getFechaNacimiento());
		solicitudProductoImpl.setSexo(getSexo());
		solicitudProductoImpl.setRentaMensual(getRentaMensual());
		solicitudProductoImpl.setCelular(getCelular());
		solicitudProductoImpl.setTelefonoCasa(getTelefonoCasa());
		solicitudProductoImpl.setTelefonoTrabajo(getTelefonoTrabajo());
		solicitudProductoImpl.setAnexo(getAnexo());
		solicitudProductoImpl.setIdEstadoCivilAdq(getIdEstadoCivilAdq());
		solicitudProductoImpl.setIdEstadoCivil(getIdEstadoCivil());
		solicitudProductoImpl.setRUC(getRUC());
		solicitudProductoImpl.setRazonSocial(getRazonSocial());
		solicitudProductoImpl.setSituacionLaboral(getSituacionLaboral());
		solicitudProductoImpl.setIdSituacionLaboral(getIdSituacionLaboral());
		solicitudProductoImpl.setIdDepartamento(getIdDepartamento());
		solicitudProductoImpl.setIdProvincia(getIdProvincia());
		solicitudProductoImpl.setIdDistrito(getIdDistrito());
		solicitudProductoImpl.setNomDepartamento(getNomDepartamento());
		solicitudProductoImpl.setNomProvincia(getNomProvincia());
		solicitudProductoImpl.setNomDistrito(getNomDistrito());
		solicitudProductoImpl.setCorreoElectronico(getCorreoElectronico());
		solicitudProductoImpl.setDireccionEnvio(getDireccionEnvio());
		solicitudProductoImpl.setPlacaVehiculo(getPlacaVehiculo());
		solicitudProductoImpl.setIdSession(getIdSession());
		solicitudProductoImpl.setIPCliente(getIPCliente());
		solicitudProductoImpl.setHorarioEnvio(getHorarioEnvio());
		solicitudProductoImpl.setFechaRegistro(getFechaRegistro());
		solicitudProductoImpl.setUTMSource(getUTMSource());
		solicitudProductoImpl.setUTMMedium(getUTMMedium());
		solicitudProductoImpl.setUTMCampaing(getUTMCampaing());
		solicitudProductoImpl.setUTMContent(getUTMContent());
		solicitudProductoImpl.setFechaResultadoPreCalif(getFechaResultadoPreCalif());
		solicitudProductoImpl.setFechaEnvioLead(getFechaEnvioLead());
		solicitudProductoImpl.setFechaEnvioEmailing(getFechaEnvioEmailing());
		solicitudProductoImpl.setEstadoPreCalificacion(getEstadoPreCalificacion());
		solicitudProductoImpl.setEstadoRegLead(getEstadoRegLead());
		solicitudProductoImpl.setEstadoEnvCorreo(getEstadoEnvCorreo());
		solicitudProductoImpl.setRespPreCalificacion(getRespPreCalificacion());
		solicitudProductoImpl.setDescripcionLead(getDescripcionLead());
		solicitudProductoImpl.setFechaActualizacion(getFechaActualizacion());
		solicitudProductoImpl.setMontoProspectado(getMontoProspectado());
		solicitudProductoImpl.setCodigoCampania(getCodigoCampania());
		solicitudProductoImpl.setCodigoMoneda(getCodigoMoneda());
		solicitudProductoImpl.setNombreSupervisor(getNombreSupervisor());
		solicitudProductoImpl.setRespRegLead(getRespRegLead());

		solicitudProductoImpl.resetOriginalValues();

		return solicitudProductoImpl;
	}

	public int compareTo(SolicitudProducto solicitudProducto) {
		long primaryKey = solicitudProducto.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SolicitudProducto solicitudProducto = null;

		try {
			solicitudProducto = (SolicitudProducto)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = solicitudProducto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SolicitudProducto> toCacheModel() {
		SolicitudProductoCacheModel solicitudProductoCacheModel = new SolicitudProductoCacheModel();

		solicitudProductoCacheModel.idSolicitudProducto = getIdSolicitudProducto();

		solicitudProductoCacheModel.idTipoDocumentoAdq = getIdTipoDocumentoAdq();

		solicitudProductoCacheModel.idTipoDocumento = getIdTipoDocumento();

		String idTipoDocumento = solicitudProductoCacheModel.idTipoDocumento;

		if ((idTipoDocumento != null) && (idTipoDocumento.length() == 0)) {
			solicitudProductoCacheModel.idTipoDocumento = null;
		}

		solicitudProductoCacheModel.tipoCredito = getTipoCredito();

		solicitudProductoCacheModel.codigoCanal = getCodigoCanal();

		String codigoCanal = solicitudProductoCacheModel.codigoCanal;

		if ((codigoCanal != null) && (codigoCanal.length() == 0)) {
			solicitudProductoCacheModel.codigoCanal = null;
		}

		solicitudProductoCacheModel.tipoEnvio = getTipoEnvio();

		String tipoEnvio = solicitudProductoCacheModel.tipoEnvio;

		if ((tipoEnvio != null) && (tipoEnvio.length() == 0)) {
			solicitudProductoCacheModel.tipoEnvio = null;
		}

		solicitudProductoCacheModel.numeroDocumento = getNumeroDocumento();

		String numeroDocumento = solicitudProductoCacheModel.numeroDocumento;

		if ((numeroDocumento != null) && (numeroDocumento.length() == 0)) {
			solicitudProductoCacheModel.numeroDocumento = null;
		}

		solicitudProductoCacheModel.apellidoPaterno = getApellidoPaterno();

		String apellidoPaterno = solicitudProductoCacheModel.apellidoPaterno;

		if ((apellidoPaterno != null) && (apellidoPaterno.length() == 0)) {
			solicitudProductoCacheModel.apellidoPaterno = null;
		}

		solicitudProductoCacheModel.apellidoMaterno = getApellidoMaterno();

		String apellidoMaterno = solicitudProductoCacheModel.apellidoMaterno;

		if ((apellidoMaterno != null) && (apellidoMaterno.length() == 0)) {
			solicitudProductoCacheModel.apellidoMaterno = null;
		}

		solicitudProductoCacheModel.primerNombre = getPrimerNombre();

		String primerNombre = solicitudProductoCacheModel.primerNombre;

		if ((primerNombre != null) && (primerNombre.length() == 0)) {
			solicitudProductoCacheModel.primerNombre = null;
		}

		solicitudProductoCacheModel.segundoNombre = getSegundoNombre();

		String segundoNombre = solicitudProductoCacheModel.segundoNombre;

		if ((segundoNombre != null) && (segundoNombre.length() == 0)) {
			solicitudProductoCacheModel.segundoNombre = null;
		}

		Date fechaNacimiento = getFechaNacimiento();

		if (fechaNacimiento != null) {
			solicitudProductoCacheModel.fechaNacimiento = fechaNacimiento.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaNacimiento = Long.MIN_VALUE;
		}

		solicitudProductoCacheModel.sexo = getSexo();

		String sexo = solicitudProductoCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			solicitudProductoCacheModel.sexo = null;
		}

		solicitudProductoCacheModel.rentaMensual = getRentaMensual();

		solicitudProductoCacheModel.celular = getCelular();

		String celular = solicitudProductoCacheModel.celular;

		if ((celular != null) && (celular.length() == 0)) {
			solicitudProductoCacheModel.celular = null;
		}

		solicitudProductoCacheModel.telefonoCasa = getTelefonoCasa();

		String telefonoCasa = solicitudProductoCacheModel.telefonoCasa;

		if ((telefonoCasa != null) && (telefonoCasa.length() == 0)) {
			solicitudProductoCacheModel.telefonoCasa = null;
		}

		solicitudProductoCacheModel.telefonoTrabajo = getTelefonoTrabajo();

		String telefonoTrabajo = solicitudProductoCacheModel.telefonoTrabajo;

		if ((telefonoTrabajo != null) && (telefonoTrabajo.length() == 0)) {
			solicitudProductoCacheModel.telefonoTrabajo = null;
		}

		solicitudProductoCacheModel.anexo = getAnexo();

		String anexo = solicitudProductoCacheModel.anexo;

		if ((anexo != null) && (anexo.length() == 0)) {
			solicitudProductoCacheModel.anexo = null;
		}

		solicitudProductoCacheModel.idEstadoCivilAdq = getIdEstadoCivilAdq();

		solicitudProductoCacheModel.idEstadoCivil = getIdEstadoCivil();

		String idEstadoCivil = solicitudProductoCacheModel.idEstadoCivil;

		if ((idEstadoCivil != null) && (idEstadoCivil.length() == 0)) {
			solicitudProductoCacheModel.idEstadoCivil = null;
		}

		solicitudProductoCacheModel.RUC = getRUC();

		String RUC = solicitudProductoCacheModel.RUC;

		if ((RUC != null) && (RUC.length() == 0)) {
			solicitudProductoCacheModel.RUC = null;
		}

		solicitudProductoCacheModel.razonSocial = getRazonSocial();

		String razonSocial = solicitudProductoCacheModel.razonSocial;

		if ((razonSocial != null) && (razonSocial.length() == 0)) {
			solicitudProductoCacheModel.razonSocial = null;
		}

		solicitudProductoCacheModel.situacionLaboral = getSituacionLaboral();

		String situacionLaboral = solicitudProductoCacheModel.situacionLaboral;

		if ((situacionLaboral != null) && (situacionLaboral.length() == 0)) {
			solicitudProductoCacheModel.situacionLaboral = null;
		}

		solicitudProductoCacheModel.idSituacionLaboral = getIdSituacionLaboral();

		solicitudProductoCacheModel.idDepartamento = getIdDepartamento();

		String idDepartamento = solicitudProductoCacheModel.idDepartamento;

		if ((idDepartamento != null) && (idDepartamento.length() == 0)) {
			solicitudProductoCacheModel.idDepartamento = null;
		}

		solicitudProductoCacheModel.idProvincia = getIdProvincia();

		String idProvincia = solicitudProductoCacheModel.idProvincia;

		if ((idProvincia != null) && (idProvincia.length() == 0)) {
			solicitudProductoCacheModel.idProvincia = null;
		}

		solicitudProductoCacheModel.idDistrito = getIdDistrito();

		String idDistrito = solicitudProductoCacheModel.idDistrito;

		if ((idDistrito != null) && (idDistrito.length() == 0)) {
			solicitudProductoCacheModel.idDistrito = null;
		}

		solicitudProductoCacheModel.nomDepartamento = getNomDepartamento();

		String nomDepartamento = solicitudProductoCacheModel.nomDepartamento;

		if ((nomDepartamento != null) && (nomDepartamento.length() == 0)) {
			solicitudProductoCacheModel.nomDepartamento = null;
		}

		solicitudProductoCacheModel.nomProvincia = getNomProvincia();

		String nomProvincia = solicitudProductoCacheModel.nomProvincia;

		if ((nomProvincia != null) && (nomProvincia.length() == 0)) {
			solicitudProductoCacheModel.nomProvincia = null;
		}

		solicitudProductoCacheModel.nomDistrito = getNomDistrito();

		String nomDistrito = solicitudProductoCacheModel.nomDistrito;

		if ((nomDistrito != null) && (nomDistrito.length() == 0)) {
			solicitudProductoCacheModel.nomDistrito = null;
		}

		solicitudProductoCacheModel.correoElectronico = getCorreoElectronico();

		String correoElectronico = solicitudProductoCacheModel.correoElectronico;

		if ((correoElectronico != null) && (correoElectronico.length() == 0)) {
			solicitudProductoCacheModel.correoElectronico = null;
		}

		solicitudProductoCacheModel.direccionEnvio = getDireccionEnvio();

		String direccionEnvio = solicitudProductoCacheModel.direccionEnvio;

		if ((direccionEnvio != null) && (direccionEnvio.length() == 0)) {
			solicitudProductoCacheModel.direccionEnvio = null;
		}

		solicitudProductoCacheModel.placaVehiculo = getPlacaVehiculo();

		String placaVehiculo = solicitudProductoCacheModel.placaVehiculo;

		if ((placaVehiculo != null) && (placaVehiculo.length() == 0)) {
			solicitudProductoCacheModel.placaVehiculo = null;
		}

		solicitudProductoCacheModel.IdSession = getIdSession();

		String IdSession = solicitudProductoCacheModel.IdSession;

		if ((IdSession != null) && (IdSession.length() == 0)) {
			solicitudProductoCacheModel.IdSession = null;
		}

		solicitudProductoCacheModel.IPCliente = getIPCliente();

		String IPCliente = solicitudProductoCacheModel.IPCliente;

		if ((IPCliente != null) && (IPCliente.length() == 0)) {
			solicitudProductoCacheModel.IPCliente = null;
		}

		Date horarioEnvio = getHorarioEnvio();

		if (horarioEnvio != null) {
			solicitudProductoCacheModel.horarioEnvio = horarioEnvio.getTime();
		}
		else {
			solicitudProductoCacheModel.horarioEnvio = Long.MIN_VALUE;
		}

		Date fechaRegistro = getFechaRegistro();

		if (fechaRegistro != null) {
			solicitudProductoCacheModel.fechaRegistro = fechaRegistro.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaRegistro = Long.MIN_VALUE;
		}

		solicitudProductoCacheModel.UTMSource = getUTMSource();

		String UTMSource = solicitudProductoCacheModel.UTMSource;

		if ((UTMSource != null) && (UTMSource.length() == 0)) {
			solicitudProductoCacheModel.UTMSource = null;
		}

		solicitudProductoCacheModel.UTMMedium = getUTMMedium();

		String UTMMedium = solicitudProductoCacheModel.UTMMedium;

		if ((UTMMedium != null) && (UTMMedium.length() == 0)) {
			solicitudProductoCacheModel.UTMMedium = null;
		}

		solicitudProductoCacheModel.UTMCampaing = getUTMCampaing();

		String UTMCampaing = solicitudProductoCacheModel.UTMCampaing;

		if ((UTMCampaing != null) && (UTMCampaing.length() == 0)) {
			solicitudProductoCacheModel.UTMCampaing = null;
		}

		solicitudProductoCacheModel.UTMContent = getUTMContent();

		String UTMContent = solicitudProductoCacheModel.UTMContent;

		if ((UTMContent != null) && (UTMContent.length() == 0)) {
			solicitudProductoCacheModel.UTMContent = null;
		}

		Date fechaResultadoPreCalif = getFechaResultadoPreCalif();

		if (fechaResultadoPreCalif != null) {
			solicitudProductoCacheModel.fechaResultadoPreCalif = fechaResultadoPreCalif.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaResultadoPreCalif = Long.MIN_VALUE;
		}

		Date fechaEnvioLead = getFechaEnvioLead();

		if (fechaEnvioLead != null) {
			solicitudProductoCacheModel.fechaEnvioLead = fechaEnvioLead.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaEnvioLead = Long.MIN_VALUE;
		}

		Date fechaEnvioEmailing = getFechaEnvioEmailing();

		if (fechaEnvioEmailing != null) {
			solicitudProductoCacheModel.fechaEnvioEmailing = fechaEnvioEmailing.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaEnvioEmailing = Long.MIN_VALUE;
		}

		solicitudProductoCacheModel.estadoPreCalificacion = getEstadoPreCalificacion();

		solicitudProductoCacheModel.estadoRegLead = getEstadoRegLead();

		solicitudProductoCacheModel.estadoEnvCorreo = getEstadoEnvCorreo();

		solicitudProductoCacheModel.respPreCalificacion = getRespPreCalificacion();

		String respPreCalificacion = solicitudProductoCacheModel.respPreCalificacion;

		if ((respPreCalificacion != null) &&
				(respPreCalificacion.length() == 0)) {
			solicitudProductoCacheModel.respPreCalificacion = null;
		}

		solicitudProductoCacheModel.descripcionLead = getDescripcionLead();

		String descripcionLead = solicitudProductoCacheModel.descripcionLead;

		if ((descripcionLead != null) && (descripcionLead.length() == 0)) {
			solicitudProductoCacheModel.descripcionLead = null;
		}

		Date fechaActualizacion = getFechaActualizacion();

		if (fechaActualizacion != null) {
			solicitudProductoCacheModel.fechaActualizacion = fechaActualizacion.getTime();
		}
		else {
			solicitudProductoCacheModel.fechaActualizacion = Long.MIN_VALUE;
		}

		solicitudProductoCacheModel.montoProspectado = getMontoProspectado();

		solicitudProductoCacheModel.codigoCampania = getCodigoCampania();

		String codigoCampania = solicitudProductoCacheModel.codigoCampania;

		if ((codigoCampania != null) && (codigoCampania.length() == 0)) {
			solicitudProductoCacheModel.codigoCampania = null;
		}

		solicitudProductoCacheModel.codigoMoneda = getCodigoMoneda();

		String codigoMoneda = solicitudProductoCacheModel.codigoMoneda;

		if ((codigoMoneda != null) && (codigoMoneda.length() == 0)) {
			solicitudProductoCacheModel.codigoMoneda = null;
		}

		solicitudProductoCacheModel.nombreSupervisor = getNombreSupervisor();

		String nombreSupervisor = solicitudProductoCacheModel.nombreSupervisor;

		if ((nombreSupervisor != null) && (nombreSupervisor.length() == 0)) {
			solicitudProductoCacheModel.nombreSupervisor = null;
		}

		solicitudProductoCacheModel.respRegLead = getRespRegLead();

		String respRegLead = solicitudProductoCacheModel.respRegLead;

		if ((respRegLead != null) && (respRegLead.length() == 0)) {
			solicitudProductoCacheModel.respRegLead = null;
		}

		return solicitudProductoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(111);

		sb.append("{idSolicitudProducto=");
		sb.append(getIdSolicitudProducto());
		sb.append(", idTipoDocumentoAdq=");
		sb.append(getIdTipoDocumentoAdq());
		sb.append(", idTipoDocumento=");
		sb.append(getIdTipoDocumento());
		sb.append(", tipoCredito=");
		sb.append(getTipoCredito());
		sb.append(", codigoCanal=");
		sb.append(getCodigoCanal());
		sb.append(", tipoEnvio=");
		sb.append(getTipoEnvio());
		sb.append(", numeroDocumento=");
		sb.append(getNumeroDocumento());
		sb.append(", apellidoPaterno=");
		sb.append(getApellidoPaterno());
		sb.append(", apellidoMaterno=");
		sb.append(getApellidoMaterno());
		sb.append(", primerNombre=");
		sb.append(getPrimerNombre());
		sb.append(", segundoNombre=");
		sb.append(getSegundoNombre());
		sb.append(", fechaNacimiento=");
		sb.append(getFechaNacimiento());
		sb.append(", sexo=");
		sb.append(getSexo());
		sb.append(", rentaMensual=");
		sb.append(getRentaMensual());
		sb.append(", celular=");
		sb.append(getCelular());
		sb.append(", telefonoCasa=");
		sb.append(getTelefonoCasa());
		sb.append(", telefonoTrabajo=");
		sb.append(getTelefonoTrabajo());
		sb.append(", anexo=");
		sb.append(getAnexo());
		sb.append(", idEstadoCivilAdq=");
		sb.append(getIdEstadoCivilAdq());
		sb.append(", idEstadoCivil=");
		sb.append(getIdEstadoCivil());
		sb.append(", RUC=");
		sb.append(getRUC());
		sb.append(", razonSocial=");
		sb.append(getRazonSocial());
		sb.append(", situacionLaboral=");
		sb.append(getSituacionLaboral());
		sb.append(", idSituacionLaboral=");
		sb.append(getIdSituacionLaboral());
		sb.append(", idDepartamento=");
		sb.append(getIdDepartamento());
		sb.append(", idProvincia=");
		sb.append(getIdProvincia());
		sb.append(", idDistrito=");
		sb.append(getIdDistrito());
		sb.append(", nomDepartamento=");
		sb.append(getNomDepartamento());
		sb.append(", nomProvincia=");
		sb.append(getNomProvincia());
		sb.append(", nomDistrito=");
		sb.append(getNomDistrito());
		sb.append(", correoElectronico=");
		sb.append(getCorreoElectronico());
		sb.append(", direccionEnvio=");
		sb.append(getDireccionEnvio());
		sb.append(", placaVehiculo=");
		sb.append(getPlacaVehiculo());
		sb.append(", IdSession=");
		sb.append(getIdSession());
		sb.append(", IPCliente=");
		sb.append(getIPCliente());
		sb.append(", horarioEnvio=");
		sb.append(getHorarioEnvio());
		sb.append(", fechaRegistro=");
		sb.append(getFechaRegistro());
		sb.append(", UTMSource=");
		sb.append(getUTMSource());
		sb.append(", UTMMedium=");
		sb.append(getUTMMedium());
		sb.append(", UTMCampaing=");
		sb.append(getUTMCampaing());
		sb.append(", UTMContent=");
		sb.append(getUTMContent());
		sb.append(", fechaResultadoPreCalif=");
		sb.append(getFechaResultadoPreCalif());
		sb.append(", fechaEnvioLead=");
		sb.append(getFechaEnvioLead());
		sb.append(", fechaEnvioEmailing=");
		sb.append(getFechaEnvioEmailing());
		sb.append(", estadoPreCalificacion=");
		sb.append(getEstadoPreCalificacion());
		sb.append(", estadoRegLead=");
		sb.append(getEstadoRegLead());
		sb.append(", estadoEnvCorreo=");
		sb.append(getEstadoEnvCorreo());
		sb.append(", respPreCalificacion=");
		sb.append(getRespPreCalificacion());
		sb.append(", descripcionLead=");
		sb.append(getDescripcionLead());
		sb.append(", fechaActualizacion=");
		sb.append(getFechaActualizacion());
		sb.append(", montoProspectado=");
		sb.append(getMontoProspectado());
		sb.append(", codigoCampania=");
		sb.append(getCodigoCampania());
		sb.append(", codigoMoneda=");
		sb.append(getCodigoMoneda());
		sb.append(", nombreSupervisor=");
		sb.append(getNombreSupervisor());
		sb.append(", respRegLead=");
		sb.append(getRespRegLead());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(169);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.SolicitudProducto");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idSolicitudProducto</column-name><column-value><![CDATA[");
		sb.append(getIdSolicitudProducto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idTipoDocumentoAdq</column-name><column-value><![CDATA[");
		sb.append(getIdTipoDocumentoAdq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idTipoDocumento</column-name><column-value><![CDATA[");
		sb.append(getIdTipoDocumento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoCredito</column-name><column-value><![CDATA[");
		sb.append(getTipoCredito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoCanal</column-name><column-value><![CDATA[");
		sb.append(getCodigoCanal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoEnvio</column-name><column-value><![CDATA[");
		sb.append(getTipoEnvio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroDocumento</column-name><column-value><![CDATA[");
		sb.append(getNumeroDocumento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellidoPaterno</column-name><column-value><![CDATA[");
		sb.append(getApellidoPaterno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellidoMaterno</column-name><column-value><![CDATA[");
		sb.append(getApellidoMaterno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primerNombre</column-name><column-value><![CDATA[");
		sb.append(getPrimerNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>segundoNombre</column-name><column-value><![CDATA[");
		sb.append(getSegundoNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaNacimiento</column-name><column-value><![CDATA[");
		sb.append(getFechaNacimiento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexo</column-name><column-value><![CDATA[");
		sb.append(getSexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rentaMensual</column-name><column-value><![CDATA[");
		sb.append(getRentaMensual());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>celular</column-name><column-value><![CDATA[");
		sb.append(getCelular());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonoCasa</column-name><column-value><![CDATA[");
		sb.append(getTelefonoCasa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonoTrabajo</column-name><column-value><![CDATA[");
		sb.append(getTelefonoTrabajo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anexo</column-name><column-value><![CDATA[");
		sb.append(getAnexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idEstadoCivilAdq</column-name><column-value><![CDATA[");
		sb.append(getIdEstadoCivilAdq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idEstadoCivil</column-name><column-value><![CDATA[");
		sb.append(getIdEstadoCivil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RUC</column-name><column-value><![CDATA[");
		sb.append(getRUC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>razonSocial</column-name><column-value><![CDATA[");
		sb.append(getRazonSocial());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>situacionLaboral</column-name><column-value><![CDATA[");
		sb.append(getSituacionLaboral());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idSituacionLaboral</column-name><column-value><![CDATA[");
		sb.append(getIdSituacionLaboral());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDepartamento</column-name><column-value><![CDATA[");
		sb.append(getIdDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idProvincia</column-name><column-value><![CDATA[");
		sb.append(getIdProvincia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDistrito</column-name><column-value><![CDATA[");
		sb.append(getIdDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomDepartamento</column-name><column-value><![CDATA[");
		sb.append(getNomDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomProvincia</column-name><column-value><![CDATA[");
		sb.append(getNomProvincia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomDistrito</column-name><column-value><![CDATA[");
		sb.append(getNomDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correoElectronico</column-name><column-value><![CDATA[");
		sb.append(getCorreoElectronico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direccionEnvio</column-name><column-value><![CDATA[");
		sb.append(getDireccionEnvio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>placaVehiculo</column-name><column-value><![CDATA[");
		sb.append(getPlacaVehiculo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IdSession</column-name><column-value><![CDATA[");
		sb.append(getIdSession());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IPCliente</column-name><column-value><![CDATA[");
		sb.append(getIPCliente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>horarioEnvio</column-name><column-value><![CDATA[");
		sb.append(getHorarioEnvio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaRegistro</column-name><column-value><![CDATA[");
		sb.append(getFechaRegistro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UTMSource</column-name><column-value><![CDATA[");
		sb.append(getUTMSource());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UTMMedium</column-name><column-value><![CDATA[");
		sb.append(getUTMMedium());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UTMCampaing</column-name><column-value><![CDATA[");
		sb.append(getUTMCampaing());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UTMContent</column-name><column-value><![CDATA[");
		sb.append(getUTMContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaResultadoPreCalif</column-name><column-value><![CDATA[");
		sb.append(getFechaResultadoPreCalif());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaEnvioLead</column-name><column-value><![CDATA[");
		sb.append(getFechaEnvioLead());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaEnvioEmailing</column-name><column-value><![CDATA[");
		sb.append(getFechaEnvioEmailing());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoPreCalificacion</column-name><column-value><![CDATA[");
		sb.append(getEstadoPreCalificacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoRegLead</column-name><column-value><![CDATA[");
		sb.append(getEstadoRegLead());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoEnvCorreo</column-name><column-value><![CDATA[");
		sb.append(getEstadoEnvCorreo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respPreCalificacion</column-name><column-value><![CDATA[");
		sb.append(getRespPreCalificacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcionLead</column-name><column-value><![CDATA[");
		sb.append(getDescripcionLead());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaActualizacion</column-name><column-value><![CDATA[");
		sb.append(getFechaActualizacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>montoProspectado</column-name><column-value><![CDATA[");
		sb.append(getMontoProspectado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoCampania</column-name><column-value><![CDATA[");
		sb.append(getCodigoCampania());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoMoneda</column-name><column-value><![CDATA[");
		sb.append(getCodigoMoneda());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombreSupervisor</column-name><column-value><![CDATA[");
		sb.append(getNombreSupervisor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respRegLead</column-name><column-value><![CDATA[");
		sb.append(getRespRegLead());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudProducto.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SolicitudProducto.class
		};
	private long _idSolicitudProducto;
	private Integer _idTipoDocumentoAdq;
	private String _idTipoDocumento;
	private Integer _tipoCredito;
	private String _codigoCanal;
	private String _tipoEnvio;
	private String _numeroDocumento;
	private String _apellidoPaterno;
	private String _apellidoMaterno;
	private String _primerNombre;
	private String _segundoNombre;
	private Date _fechaNacimiento;
	private String _sexo;
	private Double _rentaMensual;
	private String _celular;
	private String _telefonoCasa;
	private String _telefonoTrabajo;
	private String _anexo;
	private Integer _idEstadoCivilAdq;
	private String _idEstadoCivil;
	private String _RUC;
	private String _razonSocial;
	private String _situacionLaboral;
	private Integer _idSituacionLaboral;
	private String _idDepartamento;
	private String _idProvincia;
	private String _idDistrito;
	private String _nomDepartamento;
	private String _nomProvincia;
	private String _nomDistrito;
	private String _correoElectronico;
	private String _direccionEnvio;
	private String _placaVehiculo;
	private String _IdSession;
	private String _IPCliente;
	private Date _horarioEnvio;
	private Date _fechaRegistro;
	private String _UTMSource;
	private String _UTMMedium;
	private String _UTMCampaing;
	private String _UTMContent;
	private Date _fechaResultadoPreCalif;
	private Date _fechaEnvioLead;
	private Date _fechaEnvioEmailing;
	private Boolean _estadoPreCalificacion;
	private Boolean _estadoRegLead;
	private Boolean _estadoEnvCorreo;
	private String _respPreCalificacion;
	private String _descripcionLead;
	private Date _fechaActualizacion;
	private Double _montoProspectado;
	private String _codigoCampania;
	private String _codigoMoneda;
	private String _nombreSupervisor;
	private String _respRegLead;
	private SolicitudProducto _escapedModelProxy;
}