/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ext.portlet.halcon.model.impl;

import com.ext.portlet.halcon.model.TelefonoSolicitudProducto;
import com.ext.portlet.halcon.model.TelefonoSolicitudProductoModel;
import com.ext.portlet.halcon.model.TelefonoSolicitudProductoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TelefonoSolicitudProducto service. Represents a row in the &quot;T_TELEFONO_SOLICITUD_PRODUCTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.halcon.model.TelefonoSolicitudProductoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TelefonoSolicitudProductoImpl}.
 * </p>
 *
 * @author Infonet-Consulting
 * @see TelefonoSolicitudProductoImpl
 * @see com.ext.portlet.halcon.model.TelefonoSolicitudProducto
 * @see com.ext.portlet.halcon.model.TelefonoSolicitudProductoModel
 * @generated
 */
@JSON(strict = true)
public class TelefonoSolicitudProductoModelImpl extends BaseModelImpl<TelefonoSolicitudProducto>
	implements TelefonoSolicitudProductoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a telefono solicitud producto model instance should use the {@link com.ext.portlet.halcon.model.TelefonoSolicitudProducto} interface instead.
	 */
	public static final String TABLE_NAME = "T_TELEFONO_SOLICITUD_PRODUCTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tslp_IdTelefSolicitudProducto", Types.BIGINT },
			{ "tslp_IdSolicitudProducto", Types.BIGINT },
			{ "tslp_TipoTelefono", Types.VARCHAR },
			{ "tslp_NumeroTelefono", Types.VARCHAR },
			{ "tslp_Anexo", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T_TELEFONO_SOLICITUD_PRODUCTO (tslp_IdTelefSolicitudProducto LONG not null primary key IDENTITY,tslp_IdSolicitudProducto LONG,tslp_TipoTelefono VARCHAR(75) null,tslp_NumeroTelefono VARCHAR(75) null,tslp_Anexo VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T_TELEFONO_SOLICITUD_PRODUCTO";
	public static final String DATA_SOURCE = "halconDataSource";
	public static final String SESSION_FACTORY = "halconSessionFactory";
	public static final String TX_MANAGER = "halconTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ext.portlet.halcon.model.TelefonoSolicitudProducto"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ext.portlet.halcon.model.TelefonoSolicitudProducto"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TelefonoSolicitudProducto toModel(
		TelefonoSolicitudProductoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TelefonoSolicitudProducto model = new TelefonoSolicitudProductoImpl();

		model.setIdTelefSolicitudProducto(soapModel.getIdTelefSolicitudProducto());
		model.setIdSolicitudProducto(soapModel.getIdSolicitudProducto());
		model.setTipoTelefono(soapModel.getTipoTelefono());
		model.setNumeroTelefono(soapModel.getNumeroTelefono());
		model.setAnexo(soapModel.getAnexo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TelefonoSolicitudProducto> toModels(
		TelefonoSolicitudProductoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TelefonoSolicitudProducto> models = new ArrayList<TelefonoSolicitudProducto>(soapModels.length);

		for (TelefonoSolicitudProductoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ext.portlet.halcon.model.TelefonoSolicitudProducto"));

	public TelefonoSolicitudProductoModelImpl() {
	}

	public long getPrimaryKey() {
		return _idTelefSolicitudProducto;
	}

	public void setPrimaryKey(long primaryKey) {
		setIdTelefSolicitudProducto(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_idTelefSolicitudProducto);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TelefonoSolicitudProducto.class;
	}

	public String getModelClassName() {
		return TelefonoSolicitudProducto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idTelefSolicitudProducto", getIdTelefSolicitudProducto());
		attributes.put("idSolicitudProducto", getIdSolicitudProducto());
		attributes.put("tipoTelefono", getTipoTelefono());
		attributes.put("numeroTelefono", getNumeroTelefono());
		attributes.put("anexo", getAnexo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idTelefSolicitudProducto = (Long)attributes.get(
				"idTelefSolicitudProducto");

		if (idTelefSolicitudProducto != null) {
			setIdTelefSolicitudProducto(idTelefSolicitudProducto);
		}

		Long idSolicitudProducto = (Long)attributes.get("idSolicitudProducto");

		if (idSolicitudProducto != null) {
			setIdSolicitudProducto(idSolicitudProducto);
		}

		String tipoTelefono = (String)attributes.get("tipoTelefono");

		if (tipoTelefono != null) {
			setTipoTelefono(tipoTelefono);
		}

		String numeroTelefono = (String)attributes.get("numeroTelefono");

		if (numeroTelefono != null) {
			setNumeroTelefono(numeroTelefono);
		}

		String anexo = (String)attributes.get("anexo");

		if (anexo != null) {
			setAnexo(anexo);
		}
	}

	@JSON
	public long getIdTelefSolicitudProducto() {
		return _idTelefSolicitudProducto;
	}

	public void setIdTelefSolicitudProducto(long idTelefSolicitudProducto) {
		_idTelefSolicitudProducto = idTelefSolicitudProducto;
	}

	@JSON
	public long getIdSolicitudProducto() {
		return _idSolicitudProducto;
	}

	public void setIdSolicitudProducto(long idSolicitudProducto) {
		_idSolicitudProducto = idSolicitudProducto;
	}

	@JSON
	public String getTipoTelefono() {
		if (_tipoTelefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoTelefono;
		}
	}

	public void setTipoTelefono(String tipoTelefono) {
		_tipoTelefono = tipoTelefono;
	}

	@JSON
	public String getNumeroTelefono() {
		if (_numeroTelefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _numeroTelefono;
		}
	}

	public void setNumeroTelefono(String numeroTelefono) {
		_numeroTelefono = numeroTelefono;
	}

	@JSON
	public String getAnexo() {
		if (_anexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _anexo;
		}
	}

	public void setAnexo(String anexo) {
		_anexo = anexo;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TelefonoSolicitudProducto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TelefonoSolicitudProducto toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TelefonoSolicitudProducto)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TelefonoSolicitudProductoImpl telefonoSolicitudProductoImpl = new TelefonoSolicitudProductoImpl();

		telefonoSolicitudProductoImpl.setIdTelefSolicitudProducto(getIdTelefSolicitudProducto());
		telefonoSolicitudProductoImpl.setIdSolicitudProducto(getIdSolicitudProducto());
		telefonoSolicitudProductoImpl.setTipoTelefono(getTipoTelefono());
		telefonoSolicitudProductoImpl.setNumeroTelefono(getNumeroTelefono());
		telefonoSolicitudProductoImpl.setAnexo(getAnexo());

		telefonoSolicitudProductoImpl.resetOriginalValues();

		return telefonoSolicitudProductoImpl;
	}

	public int compareTo(TelefonoSolicitudProducto telefonoSolicitudProducto) {
		long primaryKey = telefonoSolicitudProducto.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TelefonoSolicitudProducto telefonoSolicitudProducto = null;

		try {
			telefonoSolicitudProducto = (TelefonoSolicitudProducto)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = telefonoSolicitudProducto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TelefonoSolicitudProducto> toCacheModel() {
		TelefonoSolicitudProductoCacheModel telefonoSolicitudProductoCacheModel = new TelefonoSolicitudProductoCacheModel();

		telefonoSolicitudProductoCacheModel.idTelefSolicitudProducto = getIdTelefSolicitudProducto();

		telefonoSolicitudProductoCacheModel.idSolicitudProducto = getIdSolicitudProducto();

		telefonoSolicitudProductoCacheModel.tipoTelefono = getTipoTelefono();

		String tipoTelefono = telefonoSolicitudProductoCacheModel.tipoTelefono;

		if ((tipoTelefono != null) && (tipoTelefono.length() == 0)) {
			telefonoSolicitudProductoCacheModel.tipoTelefono = null;
		}

		telefonoSolicitudProductoCacheModel.numeroTelefono = getNumeroTelefono();

		String numeroTelefono = telefonoSolicitudProductoCacheModel.numeroTelefono;

		if ((numeroTelefono != null) && (numeroTelefono.length() == 0)) {
			telefonoSolicitudProductoCacheModel.numeroTelefono = null;
		}

		telefonoSolicitudProductoCacheModel.anexo = getAnexo();

		String anexo = telefonoSolicitudProductoCacheModel.anexo;

		if ((anexo != null) && (anexo.length() == 0)) {
			telefonoSolicitudProductoCacheModel.anexo = null;
		}

		return telefonoSolicitudProductoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{idTelefSolicitudProducto=");
		sb.append(getIdTelefSolicitudProducto());
		sb.append(", idSolicitudProducto=");
		sb.append(getIdSolicitudProducto());
		sb.append(", tipoTelefono=");
		sb.append(getTipoTelefono());
		sb.append(", numeroTelefono=");
		sb.append(getNumeroTelefono());
		sb.append(", anexo=");
		sb.append(getAnexo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.ext.portlet.halcon.model.TelefonoSolicitudProducto");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idTelefSolicitudProducto</column-name><column-value><![CDATA[");
		sb.append(getIdTelefSolicitudProducto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idSolicitudProducto</column-name><column-value><![CDATA[");
		sb.append(getIdSolicitudProducto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoTelefono</column-name><column-value><![CDATA[");
		sb.append(getTipoTelefono());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroTelefono</column-name><column-value><![CDATA[");
		sb.append(getNumeroTelefono());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anexo</column-name><column-value><![CDATA[");
		sb.append(getAnexo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TelefonoSolicitudProducto.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TelefonoSolicitudProducto.class
		};
	private long _idTelefSolicitudProducto;
	private long _idSolicitudProducto;
	private String _tipoTelefono;
	private String _numeroTelefono;
	private String _anexo;
	private TelefonoSolicitudProducto _escapedModelProxy;
}